-- | Focused facade for the O2I semantic language.
--
-- The language defines elements, context-sensitive interpretations, and typed
-- relations independently of concrete graph instances and validation stages.
module O2I.Language
  ( module O2I.Language.Claim
  , module O2I.Language.Element
  , Interpretation(..)
  , InterpretationCode(..)
  , InterpretationSpec
  , SomeInterpretation
  , interpretationCode
  , interpretationContext
  , interpretationPrimitive
  , interpretationWitness
  , interpretationSpec
  , interpretationCodeOf
  , interpretationIdentity
  , allInterpretations
  , lookupInterpretation
  , StrategyPrimitiveRole(..)
  , MacroClaim
  , MacroEvidenceRule
  , macroEvidenceRules
  , macroEvidenceRuleConclusion
  , macroClaimConclusion
  , Relation
  , SomeRelation
  , FixedRelationCode(..)
  , AnchorRelationFamily(..)
  , RelationCode(..)
  , RelationSemantics(..)
  , MacroEvidenceKind(..)
  , RelationName(..)
  , RelationSpec
  , relationCode
  , relationSemantics
  , relationName
  , relationLabel
  , relationFrom
  , relationTo
  , relationSpec
  , relationCodeOf
  , relationSemanticsOf
  , relationNameOf
  , relationNameFor
  , anchorRelationFamilyName
  , relationIdentity
  , guidesMission
  , groundsVision
  , guidesVision
  , orientsStrategy
  , directsStrategy
  , contributesToStrategy
  , qualifiesNeed
  , surfacesNeed
  , addressesNeed
  , directsIntervention
  , changesSituation
  , setsTargetForMeasure
  , measuresSituation
  , framesMeasure
  , constitutedByAnchor
  , guidesEthosPrincipleToMissionDriver
  , guidesEthosPrincipleToVisionObjective
  , groundsMissionDriverToVisionObjective
  , orientsVisionObjectiveToStrategyObjective
  , groundsStrategyDriverToObjective
  , substantiatesStrategyKeyResultObjective
  , guidesStrategyPrincipleToAction
  , contributesStrategyActionToKeyResult
  , guidesStrategyPrincipleToPrinciple
  , contributesStrategyKeyResultToKeyResult
  , contributesStrategyActionToAction
  , translatesStrategyKeyResultToNeedObjective
  , groundsNeedDriverToObjective
  , anchorsNeedDriver
  , indicatesMeasurePerformanceDimension
  , determinesMeasurePerformanceDimension
  , containsPerformanceDimension
  , guidesStrategyActionToInterventionAction
  , contributesInterventionActionToKeyResult
  , substantiatesInterventionKeyResultNeedObjective
  , contributesInterventionKeyResultToStrategyKeyResult
  , setsTargetForMeasureKPI
  , changesAnchor
  , measuresAnchor
  , allRelationCodes
  , reifyRelation
  , allRelations
  , lookupRelations
  ) where

import O2I.Language.Claim
import O2I.Language.Element hiding (mkContextRef, mkNodeId)
import O2I.Language.Interpretation
import O2I.Language.Macro
import O2I.Language.Relation
