-- | Curated facade for O2I validation.
--
-- The normative model validation pipeline progresses from structural
-- elaboration through semantic completeness, effect traceability, ex-ante
-- readiness, and ex-post evidence assessment. 'validateNeedQualificationProposal'
-- is an auxiliary pre-persistence validation gate over a
-- 'SemanticallyValidModel'; it creates no model stage and remains outside that
-- pipeline.
module O2I.Validation
  ( Validation(..)
  , Check
  , StructuralError(..)
  , StructureInternalError(..)
  , StructuralAssessment
  , StructureResult(..)
  , StrategyAnchoring(..)
  , RawStrategyFormulation(..)
  , StrategyFormulation
  , Elaboration(..)
  , Maturity(..)
  , CandidateModelProposition(..)
  , ModelAssessment
  , ClaimId(..)
  , CollectiveFitEvidenceRef(..)
  , RawMutualCoherenceEvidence(..)
  , RawContributorCompatibilityEvidence(..)
  , RawCollectiveFitEvidence(..)
  , RawCollectiveStrategyRealization(..)
  , CollectiveParticipantRole(..)
  , CollectiveFitDimension(..)
  , CollectiveStrategyRealizationIssue(..)
  , CollectiveStrategyRealizationError(..)
  , CollectiveStrategyRealization
  , CandidateCollectiveStrategyRealization
  , CollectiveStrategyRealizationAssessment
  , RawNeedQualificationProposal(..)
  , NeedQualificationSourceReference
  , NeedQualificationCandidate
  , NeedQualificationError(..)
  , StrategyTextField(..)
  , StrategyPrimitiveRole(..)
  , ModelInvariantError(..)
  , SemanticallyValidModel
  , strategyFormulations
  , strategyFormulationData
  , lookupSemanticContextRef
  , needQualificationCandidateStrategy
  , needQualificationCandidateNeed
  , needQualificationCandidateKeyResult
  , needQualificationCandidateObjective
  , needQualificationCandidateRationale
  , needQualificationCandidateSourceReference
  , needQualificationSourceReferenceText
  , validateNeedQualificationProposal
  , qualifyingStrategies
  , EffectTrace
  , EffectTraceId
  , SomeSituationAnchorRef
  , TraceableEffectModel
  , TraceabilityError(..)
  , MacroEvidenceWitness
  , macroEvidenceWitnesses
  , witnessPremises
  , effectTraces
  , lookupEffectTrace
  , traceIdentifier
  , effectTraceIdText
  , traceVision
  , traceVisionObjective
  , traceStrategy
  , traceStrategyDriver
  , traceStrategyObjective
  , traceStrategyKeyResult
  , traceStrategyAction
  , traceNeed
  , traceNeedDriver
  , traceNeedObjective
  , traceIntervention
  , traceInterventionAction
  , traceInterventionKeyResult
  , traceMeasure
  , traceMeasurePerformanceDimension
  , traceKPI
  , traceSituation
  , traceSituationAnchor
  , situationAnchorRefId
  , situationAnchorRefKind
  , Unit(..)
  , Level(..)
  , Delta(..)
  , ValueDomain(..)
  , RelativeChange(..)
  , RawKPIDefinition(..)
  , KPIDefinition
  , kpiDefinitionKPI
  , kpiDefinitionUnit
  , kpiDefinitionDomain
  , kpiDefinitionMeasurementMethod
  , kpiDefinitionInterpretation
  , EvidenceSource(..)
  , Observation(..)
  , EffectCriterion(..)
  , TargetCriterion(..)
  , PlannedInterventionStart(..)
  , EvidencePlan(..)
  , EvidenceReadyModel
  , kpiDefinitions
  , lookupKPIDefinition
  , evidencePlans
  , readinessCheckedAt
  , plannedInterventionStarts
  , readyEffectTraces
  , readyInterventions
  , readyTracesForIntervention
  , ActualInterventionStart(..)
  , FollowUpObservation(..)
  , CriterionResult(..)
  , TargetResult(..)
  , EffectAssessment
  , assessedFollowUp
  , effectResult
  , targetResult
  , EvidenceAssessedModel
  , EvidenceReadinessError(..)
  , EvidenceError(..)
  , evidenceAssessedAt
  , actualInterventionStarts
  , effectAssessments
  , isEffectiveNeed
  , validateStructure
  , validateClaimStructure
  , structuralGraph
  , structuralCandidatePropositions
  , validateModelSemantics
  , assessModelSemantics
  , assessedSemanticModel
  , assessmentInvariantErrors
  , assessmentCandidatePropositions
  , contextElaboration
  , modelMaturity
  , validateCollectiveStrategyRealizations
  , collectiveStrategyRealizations
  , candidateCollectiveStrategyRealizations
  , lookupCollectiveStrategyRealization
  , collectiveRealizationsForTarget
  , collectiveRealizationId
  , collectiveContributors
  , collectiveTarget
  , collectiveFitEvidenceReference
  , collectiveContributionEvidence
  , candidateCollectiveClaim
  , candidateCollectiveIssues
  , validateTraceability
  , validateEvidenceReadinessAt
  , assessEffectEvidenceAt
  ) where

import Data.List.NonEmpty (NonEmpty)
import Data.Validation (Validation(..))
import O2I.Validation.Collective
import O2I.Validation.Evidence
import O2I.Validation.Qualification
import O2I.Validation.Readiness
import O2I.Validation.Semantics
import O2I.Validation.Structure
import O2I.Validation.Trace

-- | Validation result that accumulates one or more independent errors.
type Check error result = Validation (NonEmpty error) result
