-- | Adapter-parametric O2I profile projection.
module O2I.Inspection.Profile
  ( O2IProfileVersion
  , O2IProfileVersionError(..)
  , mkO2IProfileVersion
  , o2iProfileVersionLiteral
  , profileVersionText
  , ObservedO2IProfile(..)
  , ResolvedO2IProfile
  , resolvedProfileVersion
  , resolveProfileVersion
  , ProfileSnapshot
  , profileSnapshot
  , snapshotFact
  , DefectApplicability(..)
  , DeferredProfileDefect(..)
  , RootProjection(..)
  , PersistedDependencyReason(..)
  , IndexedProfileFact
  , indexOccurrence
  , indexNode
  , indexEdge
  , indexPresentation
  , indexDependency
  , indexReference
  , ProfileProjection(..)
  , O2IProfileContract(..)
  , ResolvedProfileProjection
  , ProfileResolution(..)
  , resolveRootProfile
  , ProfileIndex
  , buildProfileIndex
  ) where

import O2I.Inspection.Profile.Internal
