-- | Stable report domain and machine-readable rendering.
module O2I.Inspection.Report
  ( StageState(..)
  , BlockReason(..)
  , StageReport(..)
  , StageReports
  , InspectionResult(..)
  , NativeBindingFailure(..)
  , NativeAdapterBinding(..)
  , FailedViewResolution(..)
  , ResolvedViewResolution(..)
  , ViewResolution(..)
  , RejectedO2IProfile(..)
  , O2IProfileResolution(..)
  , ScopeFailure(..)
  , ResolvedScope(..)
  , ScopeResolution(..)
  , InspectionRequestInfo(..)
  , InspectionSemanticAssessment
  , InspectionReport
  , CommandErrorClassification(..)
  , InvocationDefect(..)
  , CommandError(..)
  , reportRequestInfo
  , reportNativeBinding
  , reportViewResolution
  , reportProfileResolution
  , reportScopeResolution
  , reportClosedScopeProvenance
  , reportSupplementalSources
  , reportSemanticAssessment
  , reportMaturity
  , reportMaturityText
  , semanticCollectiveStrategyRealizations
  , reportStageReports
  , reportDiagnostics
  , reportResult
  , reportExitCode
  , commandErrorExitCode
  , stageReportsList
  , renderInspectionReportJSON
  , renderCommandErrorJSON
  ) where

import O2I.Inspection.Report.Internal
