"""Focused tests for deterministic ArchiMate profile publication."""

from contextlib import redirect_stderr, redirect_stdout
import importlib.util
import io
import json
from pathlib import Path
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
UTILITY = ROOT / "utl" / "model"
CONTRACT_PATH = ROOT / "spc" / "ctr" / "archimate" / "profile.json"
FRAGMENT_PATH = ROOT / "spc" / "ctr" / "archimate" / "profile.md"
sys.path.insert(0, str(UTILITY))

from archimate_profile import (  # noqa: E402
    decode_profile_contract,
    load_profile_contract,
)


SPEC = importlib.util.spec_from_file_location(
    "render_archimate_profile",
    UTILITY / "render-archimate-profile.py",
)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("cannot load render-archimate-profile.py")
RENDERER = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = RENDERER
SPEC.loader.exec_module(RENDERER)


class RenderArchimateProfileTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.contract = load_profile_contract(CONTRACT_PATH)
        cls.rendered = RENDERER.render_contract(cls.contract)

    def payload(self) -> dict:
        return json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))

    def test_output_is_deterministic_and_publication_ready(self) -> None:
        self.assertEqual(
            self.rendered,
            RENDERER.render_contract(self.contract),
        )
        self.assertTrue(self.rendered.endswith("\n"))
        self.assertIn("<!-- Generated by", self.rendered)
        self.assertIn(
            "(spc/ctr/archimate/profile.json)",
            self.rendered,
        )
        self.assertNotIn("[!IMPORTANT]", self.rendered)
        self.assertNotIn("deterministisch", self.rendered)
        self.assertNotIn("(./profile.json)", self.rendered)
        self.assertNotIn('"carrierMappings":', self.rendered)
        self.assertNotIn("```json", self.rendered)
        self.assertNotIn(r"\|", self.rendered)
        self.assertNotIn("| --- | --- |", self.rendered)
        self.assertIn(
            "`Context --contextualizes--> {Primitive, Structuring}`",
            self.rendered,
        )
        self.assertIn(
            "`o2i.commitment = {candidate, asserted}`",
            self.rendered,
        )
        self.assertIn(
            "`Strategy --directs--> Strategy`",
            self.rendered,
        )
        self.assertIn(
            "`Grouping -> Grouping`",
            self.rendered,
        )
        self.assertIn(
            "`n -> InfluenceRelationship`",
            self.rendered,
        )

    def test_renders_only_used_revision_bound_applicability_evidence(
        self,
    ) -> None:
        provenance = self.contract.applicability_provenance
        self.assertEqual(1, len(provenance["symbolInterpretations"]))
        self.assertEqual(1, len(provenance["decisions"]))
        self.assertIn(
            "archimatetool/archi@"
            "b5bd0038922ab68b26eb78c97ff7efc2ff0bba82:",
            self.rendered,
        )
        self.assertNotIn("relationships-keys.xml", self.rendered)
        self.assertNotIn('"symbolInterpretations"', self.rendered)
        self.assertNotIn('"decisions"', self.rendered)

    def test_committed_fragment_is_current(self) -> None:
        self.assertEqual(
            self.rendered,
            FRAGMENT_PATH.read_text(encoding="utf-8"),
        )
        self.assertTrue(
            RENDERER.check_fragment(CONTRACT_PATH, FRAGMENT_PATH)
        )

    def test_write_and_check_modes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "profile.md"
            stdout = io.StringIO()
            with redirect_stdout(stdout):
                result = RENDERER.main(
                    [
                        "--contract",
                        str(CONTRACT_PATH),
                        "--output",
                        str(output),
                    ]
                )
            self.assertEqual(0, result)
            self.assertEqual(self.rendered, output.read_text(encoding="utf-8"))
            self.assertIn("[o2i|info] Wrote", stdout.getvalue())

            stdout = io.StringIO()
            with redirect_stdout(stdout):
                result = RENDERER.main(
                    [
                        "--contract",
                        str(CONTRACT_PATH),
                        "--output",
                        str(output),
                        "--check",
                    ]
                )
            self.assertEqual(0, result)
            self.assertIn("is current", stdout.getvalue())

            output.write_text(self.rendered + "stale\n", encoding="utf-8")
            stderr = io.StringIO()
            with redirect_stderr(stderr):
                result = RENDERER.main(
                    [
                        "--contract",
                        str(CONTRACT_PATH),
                        "--output",
                        str(output),
                        "--check",
                    ]
                )
            self.assertEqual(1, result)
            self.assertIn("[o2i|error]", stderr.getvalue())
            self.assertIn("is stale", stderr.getvalue())

    def test_every_mapping_has_exactly_one_publication_category(self) -> None:
        headings = (
            (
                "##### Anwendbarkeitsprovenienz "
                "{#o2i-profile-applicability-provenance .unnumbered}"
            ),
            (
                "##### Syntaxträgerabbildungen "
                "{#o2i-profile-carriers .unnumbered}"
            ),
            (
                "##### Kontextrelationen "
                "{#o2i-profile-context-relations .unnumbered}"
            ),
            (
                "##### Primitive und strukturierende Relationen "
                "{#o2i-profile-primitive-relations .unnumbered}"
            ),
            (
                "##### Situationsanker "
                "{#o2i-profile-situation-anchors .unnumbered}"
            ),
            (
                "##### Kontextualisierung "
                "{#o2i-profile-contextualization .unnumbered}"
            ),
            (
                "##### Kollektive Strategierealisierung "
                "{#o2i-profile-collective-strategy-realization .unnumbered}"
            ),
        )
        for heading in headings:
            self.assertEqual(1, self.rendered.count(heading))

        self.assertEqual(
            1,
            self.rendered.count(
                "###### Orientierung und Strategieformierung "
                "{#o2i-profile-orientation-relations .unnumbered}"
            ),
        )
        self.assertEqual(2, self.rendered.count("\\Needspace{10\\baselineskip}"))
        self.assertEqual(
            1,
            self.rendered.count(
                "###### Bedarfsqualifikation, Intervention, Messung und "
                "Strukturierung "
                "{#o2i-profile-operational-relations .unnumbered}"
            ),
        )

        for carrier in self.contract.carrier_mappings:
            row = "| " + " | ".join(
                (
                    RENDERER._code(carrier["o2iKind"]),
                    RENDERER._code_join(carrier["o2iTypes"]),
                    RENDERER._code(carrier["archimateElement"]),
                    RENDERER._code(
                        RENDERER._german(carrier["contextOwnership"])
                    ),
                )
            ) + " |"
            self.assertEqual(1, self.rendered.count(row))

        anchor_ids = {
            carrier["id"]
            for carrier in self.contract.carrier_mappings
            if carrier["o2iKind"] == "SituationAnchor"
        }
        anchor_families = set()
        decision_ids = {
            decision["relationMappingId"]
            for decision in self.contract.applicability_provenance[
                "decisions"
            ]
        }
        for relation in self.contract.relation_mappings:
            if {
                relation["source"],
                relation["target"],
            }.intersection(anchor_ids):
                anchor_families.add(relation["relationName"])
            else:
                signature = RENDERER._signature(
                    relation,
                    self.endpoint_names(),
                )
                self.assertEqual(
                    1,
                    self.rendered.count(RENDERER._code(signature)),
                )
            expected_id_count = 1 if relation["id"] in decision_ids else 0
            self.assertEqual(
                expected_id_count,
                self.rendered.count(f"`{relation['id']}`"),
            )
        self.assertEqual(4, len(anchor_families))

        self.assertNotIn("Mapping-ID", self.rendered)
        self.assertNotIn("ID-Muster", self.rendered)

    def test_primitive_relation_split_is_semantic_and_complete(self) -> None:
        patterns = RENDERER._patterns_by_id(self.contract)
        endpoint_names = RENDERER._endpoint_names(
            self.contract.carrier_mappings,
            patterns["contextualization"],
        )
        anchor_ids = {
            carrier["id"]
            for carrier in self.contract.carrier_mappings
            if carrier["o2iKind"] == "SituationAnchor"
        }
        primitive_relations = [
            relation
            for relation in self.contract.relation_mappings
            if not (
                relation["source"].startswith("context.")
                and relation["target"].startswith("context.")
            )
            and not {
                relation["source"],
                relation["target"],
            }.intersection(anchor_ids)
        ]
        orientation = [
            relation
            for relation in primitive_relations
            if not RENDERER._is_operational_relation(relation)
        ]
        operational = [
            relation
            for relation in primitive_relations
            if RENDERER._is_operational_relation(relation)
        ]

        self.assertTrue(orientation)
        self.assertTrue(operational)
        self.assertEqual(
            len(primitive_relations),
            len(orientation) + len(operational),
        )
        for relation in orientation:
            self.assertNotIn("primitive.intervention.", relation["source"])
            self.assertNotIn("primitive.intervention.", relation["target"])
            self.assertNotIn("primitive.measure.", relation["source"])
            self.assertNotIn("primitive.measure.", relation["target"])
            self.assertNotIn("primitive.need.", relation["source"])
            self.assertNotIn("primitive.need.", relation["target"])
            self.assertNotIn("structuring.", relation["source"])
            self.assertNotIn("structuring.", relation["target"])
        for relation in primitive_relations:
            signature = RENDERER._signature(relation, endpoint_names)
            self.assertEqual(
                1,
                self.rendered.count(RENDERER._code(signature)),
            )

    def test_anchor_expansion_is_complete_and_compressed(self) -> None:
        patterns = RENDERER._patterns_by_id(self.contract)
        endpoint_names = RENDERER._endpoint_names(
            self.contract.carrier_mappings,
            patterns["contextualization"],
        )
        carriers, families, relation_ids = RENDERER._anchor_contract(
            self.contract,
            endpoint_names,
        )
        self.assertEqual(4, len(carriers))
        self.assertEqual(4, len(families))
        self.assertEqual(16, len(relation_ids))
        for family in families:
            signature = (
                f"{family.source} --{family.label}--> {family.target}"
            )
            self.assertEqual(
                1,
                self.rendered.count(RENDERER._code(signature)),
            )

        payload = self.payload()
        removed = sorted(relation_ids)[0]
        payload["relationMappings"] = [
            relation
            for relation in payload["relationMappings"]
            if relation["id"] != removed
        ]
        incomplete = decode_profile_contract(json.dumps(payload))
        with self.assertRaisesRegex(
            RENDERER.ProfileRenderError,
            "does not cover every anchor form",
        ):
            RENDERER.render_contract(incomplete)

    def test_uses_readable_names_and_german_contract_terms(self) -> None:
        expected_names = (
            "Key Result @ Strategy",
            "Performance Dimension @ Measure",
            "Situation Anchor",
            "Business Capability",
            "Business Process",
            "Business Object",
            "Value Stream",
        )
        for name in expected_names:
            self.assertIn(name, self.rendered)
        self.assertNotIn("KeyResult @", self.rendered)
        self.assertNotIn("PerformanceDimension @", self.rendered)
        self.assertNotIn("--> SituationAnchor", self.rendered)

        for abstract_term in (
            "required",
            "forbidden",
            "exactly-one",
            "at-least-two",
            "context-ownership",
            "structured-proposition",
        ):
            self.assertNotIn(abstract_term, self.rendered)
        self.assertIn("candidate", self.rendered)
        self.assertIn("asserted", self.rendered)
        self.assertIn("o2i.commitment", self.rendered)

    def test_inline_code_escapes_table_and_fence_content(self) -> None:
        payload = self.payload()
        payload["profileVersion"] = "v|`x\nnext"
        rendered = RENDERER.render_contract(
            decode_profile_contract(json.dumps(payload))
        )

        self.assertIn(r"v\|`x next", rendered)
        profile_line = next(
            line for line in rendered.splitlines() if "Profilversion" in line
        )
        self.assertNotIn("\n", profile_line)
        self.assertGreaterEqual(profile_line.count("``"), 2)

    def endpoint_names(self) -> dict:
        patterns = RENDERER._patterns_by_id(self.contract)
        return RENDERER._endpoint_names(
            self.contract.carrier_mappings,
            patterns["contextualization"],
        )


if __name__ == "__main__":
    unittest.main()
