{-# LANGUAGE TemplateHaskell #-}

-- | External-client contracts for the public ArchiMate Profile API.
module Main
  ( main
  ) where

import ApiContractTH (assertAbstractTypes, assertOrdinaryFunctions)
import qualified O2I.ArchiMate.Profile as Profile
import qualified O2I.ArchiMate.Profile.Closure as Closure
import qualified O2I.ArchiMate.Profile.Draft as Draft
import qualified O2I.ArchiMate.Profile.Mapping as Mapping
import qualified O2I.ArchiMate.Profile.Notation as Notation
import qualified O2I.ArchiMate.Profile.Projection as Projection
import qualified O2I.ArchiMate.Profile.Resolution as Resolution
import qualified O2I.ArchiMate.Profile.Rule.Catalog as RuleCatalog
import qualified O2I.ArchiMate.Profile.Rule.Explanation as RuleExplanation

$(assertAbstractTypes
    [ "Profile.ProfileDescriptor"
    , "Draft.ProfileDraft"
    , "Draft.DraftRecord"
    , "Draft.DraftRecordFamilyValue"
    , "Draft.ModelRootRole"
    , "Draft.PropertyDefinitionRole"
    , "Draft.ElementRole"
    , "Draft.RelationshipRole"
    , "Draft.ViewRole"
    , "Draft.ViewNodeRole"
    , "Draft.ViewConnectionRole"
    , "Draft.ModelRootDraft"
    , "Draft.PropertyDefinitionDraft"
    , "Draft.ElementDraft"
    , "Draft.RelationshipDraft"
    , "Draft.ViewDraft"
    , "Draft.ViewNodeDraft"
    , "Draft.ViewConnectionDraft"
    , "Draft.DraftIdentity"
    , "Draft.DraftValueKind"
    , "Draft.DraftScalar"
    , "Draft.DraftFieldValue"
    , "Draft.DraftMember"
    , "Draft.DraftReference"
    , "Draft.DraftReferenceFieldValue"
    , "Draft.DraftPropertyKey"
    , "Draft.DraftProperty"
    , "Draft.DraftNativeName"
    , "Draft.DraftOpaquePosition"
    , "Draft.DraftOpaqueEvidence"
    , "Draft.DraftPathStep"
    , "Draft.DraftSourcePath"
    , "Draft.DraftLocation"
    , "Draft.DraftSourcePosition"
    , "Draft.DraftSourceSpan"
    , "Notation.CanonicalDocument"
    , "Notation.CanonicalOccurrence"
    , "Notation.CanonicalOccurrenceKind"
    , "Notation.CanonicalRecord"
    , "Notation.CanonicalProperty"
    , "Notation.CanonicalField"
    , "Notation.IdentityInvalidReason"
    , "Notation.IdentityOutcome"
    , "Notation.CanonicalTarget"
    , "Notation.ReferenceOutcome"
    , "Notation.CanonicalReference"
    , "Notation.CanonicalView"
    , "Notation.MarkerKeyOutcome"
    , "Notation.MarkerCandidate"
    , "Notation.MarkerEvidenceAssessment"
    , "Notation.ArchiMateNotationIssueKind"
    , "Notation.ViewInventoryIssueKind"
    , "Notation.ProfileMarkerIssueKind"
    , "Notation.SelectedUniverseIssueKind"
    , "Notation.ArchiMateNotationIssue"
    , "Notation.ArchiMateNotationEvidence"
    , "Notation.StageResult"
    , "Notation.NotationResult"
    , "Notation.NotationConformantUniverse"
    , "Resolution.ProfileDescriptor"
    , "Resolution.SelectedArchiMateProfile"
    , "Closure.DisplayedOccurrence"
    , "Closure.ClosureBranch"
    , "Closure.ActivationProvenance"
    , "Closure.ClosureProvenance"
    , "Closure.ProfileAssessmentUniverse"
    , "Mapping.CarrierMapping"
    , "Mapping.RelationMapping"
    , "Projection.ProfileEvidenceKind"
    , "Projection.ProfileEvidence"
    , "Projection.ProfileDefect"
    , "Projection.ProfileContractFailure"
    , "Projection.ProfileProjectionAssessment"
    , "Projection.ProfileProjection"
    , "Projection.ProfileMappingProvenance"
    , "Projection.QualificationProposal"
    , "Projection.QualificationRationale"
    , "Projection.QualificationSource"
    , "Projection.QualificationReference"
    , "RuleCatalog.ProfileRuleCatalog"
    , "RuleExplanation.ProfileRuleId"
    , "RuleExplanation.ProfileRuleAuthority"
    , "RuleExplanation.ProfileRuleStage"
    , "RuleExplanation.ProfileRuleExplanation"
    ])

$(assertOrdinaryFunctions
    [ 'Profile.compiledProfileInventory
    , 'Profile.profileDescriptorIdentity
    , 'Profile.profileDescriptorToken
    , 'Profile.profileDescriptorReference
    , 'Profile.profileDescriptorVersion
    , 'Profile.profileDescriptorNotation
    , 'Profile.profileDescriptorAdapterIds
    , 'Profile.profileDescriptorContractDigest
    , 'Draft.profileDraft
    , 'Draft.profileDraftRoot
    , 'Draft.foldDraftRecordFamilyValue
    , 'Draft.draftRecordFamily
    , 'Draft.draftRecordIdentity
    , 'Draft.draftRecordLocation
    , 'Draft.draftRecordMembers
    , 'Draft.foldDraftRecord
    , 'Draft.modelRootDraft
    , 'Draft.propertyDefinitionDraft
    , 'Draft.elementDraft
    , 'Draft.relationshipDraft
    , 'Draft.viewDraft
    , 'Draft.viewNodeDraft
    , 'Draft.viewConnectionDraft
    , 'Draft.draftIdentity
    , 'Draft.foldDraftIdentity
    , 'Draft.draftTextKind
    , 'Draft.draftBooleanKind
    , 'Draft.draftNumberKind
    , 'Draft.draftNativeNameKind
    , 'Draft.draftOtherKind
    , 'Draft.foldDraftValueKind
    , 'Draft.draftTextScalar
    , 'Draft.draftBooleanScalar
    , 'Draft.draftNumberScalar
    , 'Draft.draftNativeNameScalar
    , 'Draft.draftOtherScalar
    , 'Draft.foldDraftScalarValue
    , 'Draft.draftScalarKind
    , 'Draft.draftScalarText
    , 'Draft.draftScalarLocation
    , 'Draft.foldDraftFieldValue
    , 'Draft.typeFieldMember
    , 'Draft.nameFieldMember
    , 'Draft.elementDocumentationFieldMember
    , 'Draft.relationshipDocumentationFieldMember
    , 'Draft.directedFieldMember
    , 'Draft.influenceStrengthFieldMember
    , 'Draft.propertyMember
    , 'Draft.referenceMember
    , 'Draft.childRecordMember
    , 'Draft.opaqueMember
    , 'Draft.foldDraftMember
    , 'Draft.foldDraftReferenceFieldValue
    , 'Draft.propertyDefinitionReference
    , 'Draft.relationshipSourceReference
    , 'Draft.relationshipTargetReference
    , 'Draft.viewNodeElementReference
    , 'Draft.viewConnectionRelationshipReference
    , 'Draft.viewConnectionSourceReference
    , 'Draft.viewConnectionTargetReference
    , 'Draft.draftReferenceField
    , 'Draft.draftReferenceIdentity
    , 'Draft.draftReferenceLocation
    , 'Draft.draftReferenceExpectedFamily
    , 'Draft.foldDraftReference
    , 'Draft.directPropertyKey
    , 'Draft.propertyDefinitionKey
    , 'Draft.foldDraftPropertyKey
    , 'Draft.draftProperty
    , 'Draft.draftPropertyKey
    , 'Draft.draftPropertyValues
    , 'Draft.draftPropertyLocation
    , 'Draft.draftPropertyOpaqueEvidence
    , 'Draft.draftNativeName
    , 'Draft.draftNativeNamespace
    , 'Draft.draftNativeLocalName
    , 'Draft.opaqueAttribute
    , 'Draft.opaqueChild
    , 'Draft.foldDraftOpaquePosition
    , 'Draft.draftOpaqueEvidence
    , 'Draft.draftOpaquePosition
    , 'Draft.draftOpaqueName
    , 'Draft.draftOpaqueScalars
    , 'Draft.draftOpaqueLocation
    , 'Draft.draftPathStep
    , 'Draft.draftPathStepName
    , 'Draft.draftPathStepOrdinal
    , 'Draft.draftSourcePath
    , 'Draft.foldDraftSourcePath
    , 'Draft.draftLocation
    , 'Draft.draftLocationPath
    , 'Draft.draftLocationSpan
    , 'Draft.draftSourcePosition
    , 'Draft.draftSourceLine
    , 'Draft.draftSourceColumn
    , 'Draft.draftSourceOffset
    , 'Draft.draftSourceSpan
    , 'Draft.draftSpanStart
    , 'Draft.draftSpanEnd
    , 'Notation.withCanonicalDocument
    , 'Notation.canonicalDocumentDraft
    , 'Notation.canonicalDocumentRecords
    , 'Notation.canonicalDocumentProperties
    , 'Notation.canonicalDocumentReferences
    , 'Notation.foldCanonicalOccurrenceKind
    , 'Notation.canonicalOccurrenceKind
    , 'Notation.canonicalOccurrenceOrdinal
    , 'Notation.foldCanonicalRecord
    , 'Notation.canonicalPropertyOccurrence
    , 'Notation.canonicalPropertyOwner
    , 'Notation.canonicalPropertyOwnerFamily
    , 'Notation.canonicalPropertyLocation
    , 'Notation.canonicalPropertyValues
    , 'Notation.canonicalPropertyOpaqueEvidence
    , 'Notation.foldCanonicalPropertyKey
    , 'Notation.canonicalFieldKind
    , 'Notation.canonicalFieldScalars
    , 'Notation.canonicalFieldLocation
    , 'Notation.foldIdentityInvalidReason
    , 'Notation.foldIdentityOutcome
    , 'Notation.canonicalTargetOccurrence
    , 'Notation.canonicalTargetFamily
    , 'Notation.canonicalTargetIdentity
    , 'Notation.canonicalTargetLocation
    , 'Notation.canonicalTargetFields
    , 'Notation.foldReferenceOutcome
    , 'Notation.canonicalReferenceOccurrence
    , 'Notation.canonicalReferenceOwner
    , 'Notation.canonicalReferenceField
    , 'Notation.canonicalReferenceExpectedFamily
    , 'Notation.canonicalReferenceLocation
    , 'Notation.canonicalReferenceOutcome
    , 'Notation.canonicalViewOccurrence
    , 'Notation.canonicalViewIdentity
    , 'Notation.canonicalViewNameFields
    , 'Notation.canonicalViewLocation
    , 'Notation.canonicalViews
    , 'Notation.foldMarkerKeyOutcome
    , 'Notation.markerCandidateProperty
    , 'Notation.markerCandidateDefinitionFields
    , 'Notation.markerCandidateKeyOutcome
    , 'Notation.assessMarkerEvidence
    , 'Notation.foldMarkerEvidenceAssessment
    , 'Notation.allArchiMateNotationIssueKinds
    , 'Notation.allViewInventoryIssueKinds
    , 'Notation.allProfileMarkerIssueKinds
    , 'Notation.allSelectedUniverseIssueKinds
    , 'Notation.foldArchiMateNotationIssueKind
    , 'Notation.archiMateNotationIssueKindToken
    , 'Notation.viewInventoryIssueKindToken
    , 'Notation.profileMarkerIssueKindToken
    , 'Notation.selectedUniverseIssueKindToken
    , 'Notation.foldArchiMateNotationEvidence
    , 'Notation.archiMateNotationIssueKind
    , 'Notation.archiMateNotationIssueSubject
    , 'Notation.archiMateNotationIssueEvidence
    , 'Notation.assessCanonicalViewInventory
    , 'Notation.profileMarkerNotationIssues
    , 'Notation.foldStageResult
    , 'Notation.assessArchiMateNotation
    , 'Notation.notationIssues
    , 'Notation.notationConformance
    , 'Resolution.compiledProfileDescriptor
    , 'Resolution.profileDescriptorIdentity
    , 'Resolution.profileDescriptorToken
    , 'Resolution.profileDescriptorReference
    , 'Resolution.profileDescriptorVersion
    , 'Resolution.profileDescriptorNotation
    , 'Resolution.profileDescriptorAdapterIds
    , 'Resolution.profileDescriptorContractDigest
    , 'Resolution.foldProfileDescriptor
    , 'Resolution.withSelectedArchiMateProfile
    , 'Resolution.selectedArchiMateProfileDescriptor
    , 'Closure.displayedViewOccurrence
    , 'Closure.displayedSubjectOccurrence
    , 'Closure.foldClosureBranch
    , 'Closure.foldActivationProvenance
    , 'Closure.foldClosureProvenance
    , 'Closure.deriveProfileAssessmentUniverse
    , 'Closure.assessmentCanonicalDocument
    , 'Closure.assessmentSelectedViewOccurrence
    , 'Closure.assessmentDisplayedOccurrences
    , 'Closure.assessmentGraphOccurrences
    , 'Closure.assessmentQualificationOccurrences
    , 'Closure.assessmentUniverse
    , 'Closure.assessmentActivationProvenance
    , 'Closure.assessmentClosureProvenance
    , 'Mapping.normalizeRelationshipLabel
    , 'Mapping.carrierMappings
    , 'Mapping.carrierMappingId
    , 'Mapping.carrierMappingElement
    , 'Mapping.carrierMappingCategory
    , 'Mapping.carrierMappingTypes
    , 'Mapping.relationMappings
    , 'Mapping.relationMappingId
    , 'Mapping.relationMappingRelationship
    , 'Mapping.relationMappingAssociationDirected
    , 'Mapping.relationMappingLabel
    , 'Mapping.relationMappingToken
    , 'Projection.foldProfileEvidenceKind
    , 'Projection.profileEvidenceKind
    , 'Projection.foldProfileEvidence
    , 'Projection.profileDefectRuleId
    , 'Projection.foldProfileDefect
    , 'Projection.foldProfileContractFailure
    , 'Projection.assessSelectedView
    , 'Projection.foldProfileProjectionAssessment
    , 'Projection.profileStructureProjection
    , 'Projection.profileMappingProvenance
    , 'Projection.foldProfileMappingProvenance
    , 'Projection.profileQualificationProposals
    , 'Projection.qualificationProposalOccurrence
    , 'Projection.qualificationProposalIdentity
    , 'Projection.qualificationProposalRationale
    , 'Projection.qualificationRationaleLocation
    , 'Projection.qualificationRationaleValue
    , 'Projection.qualificationProposalSources
    , 'Projection.qualificationProposalReferences
    , 'Projection.qualificationSourceOccurrence
    , 'Projection.qualificationSourceValue
    , 'Projection.qualificationReferenceOccurrence
    , 'Projection.qualificationReferenceRole
    , 'Projection.qualificationReferenceTarget
    , 'RuleCatalog.selectedProfileRuleCatalog
    , 'RuleCatalog.selectedProfileRuleCatalogProfileReference
    , 'RuleCatalog.selectedProfileRuleCatalogContractDigest
    , 'RuleCatalog.selectedProfileRuleCatalogEntries
    , 'RuleCatalog.selectedProfileRuleCatalogSize
    , 'RuleCatalog.selectedProfileRulesForStage
    , 'RuleCatalog.lookupSelectedProfileRule
    , 'RuleCatalog.foldSelectedProfileRuleCatalog
    , 'RuleExplanation.profileRuleIdText
    , 'RuleExplanation.selectedProfileRuleAuthority
    , 'RuleExplanation.profileRuleAuthorityText
    , 'RuleExplanation.foldProfileRuleAuthority
    , 'RuleExplanation.selectedProfileRuleStage
    , 'RuleExplanation.profileRuleStageText
    , 'RuleExplanation.foldProfileRuleStage
    , 'RuleExplanation.profileRuleId
    , 'RuleExplanation.profileRuleAuthority
    , 'RuleExplanation.profileRuleProfileReference
    , 'RuleExplanation.profileRuleProfileContractDigest
    , 'RuleExplanation.profileRuleStage
    , 'RuleExplanation.profileRuleExpectation
    , 'RuleExplanation.profileRuleMeaning
    , 'RuleExplanation.profileRuleAction
    , 'RuleExplanation.foldProfileRuleExplanation
    ])

main :: IO ()
main = pure ()
