{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Schema.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import O2I.Operation.Schema.Internal

adapterInventoryVariant :: SchemaVariant
adapterInventoryVariant = SchemaVariant "adapter-inventory"

adapterInventoryMachineSchema :: MachineSchema
adapterInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.adapter-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "9ebc6cba58375277366bf50e83bda032344e4aff76f378f4c32ede43eaf04149"
          }
    , machineSchemaVariantsValue = adapterInventoryVariant :| []
    }

profileInventoryVariant :: SchemaVariant
profileInventoryVariant = SchemaVariant "profile-inventory"

profileDefinitionInvalidVariant :: SchemaVariant
profileDefinitionInvalidVariant =
  SchemaVariant "profile-static-definition-invalid"

profileInventoryMachineSchema :: MachineSchema
profileInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.profile-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "cb3e8626972fabf979f729cd71761d46df0ffde7c710357b02e42b058d467a6a"
          }
    , machineSchemaVariantsValue =
        profileInventoryVariant :| [profileDefinitionInvalidVariant]
    }

ruleInventoryVariant :: SchemaVariant
ruleInventoryVariant = SchemaVariant "rule-inventory"

ruleDefinitionInvalidVariant :: SchemaVariant
ruleDefinitionInvalidVariant = SchemaVariant "rule-static-definition-invalid"

ruleInventoryMachineSchema :: MachineSchema
ruleInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "58648f3f9edd15d5ca9c3b042271547694062f0bde7cbc9f21d9e41ee63519b1"
          }
    , machineSchemaVariantsValue =
        ruleInventoryVariant :| [ruleDefinitionInvalidVariant]
    }

ruleExplanationFoundVariant :: SchemaVariant
ruleExplanationFoundVariant = SchemaVariant "rule-explanation-found"

ruleExplanationNotFoundVariant :: SchemaVariant
ruleExplanationNotFoundVariant = SchemaVariant "rule-explanation-not-found"

ruleExplanationMachineSchema :: MachineSchema
ruleExplanationMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-explanation"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "a8c10312335adc2fa8a0a449057c3177a0f9d74b416449b8f9e9dc02ddc67e8a"
          }
    , machineSchemaVariantsValue =
        ruleExplanationFoundVariant :| [ruleExplanationNotFoundVariant]
    }

viewsDiscoveredVariant :: SchemaVariant
viewsDiscoveredVariant = SchemaVariant "views-discovered"

viewAcquisitionFailedVariant :: SchemaVariant
viewAcquisitionFailedVariant = SchemaVariant "view-acquisition-failed"

viewAdapterSelectionFailedVariant :: SchemaVariant
viewAdapterSelectionFailedVariant =
  SchemaVariant "view-adapter-selection-failed"

viewAdapterDecodeFailedVariant :: SchemaVariant
viewAdapterDecodeFailedVariant = SchemaVariant "view-adapter-decode-failed"

viewDiscoveryMachineSchema :: MachineSchema
viewDiscoveryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.discovery.view"
          , schemaAuthorityVersionValue = SchemaVersion 2
          , schemaAuthorityDigestValue =
              SchemaDigest
                "596b82ae5bc9c900c5094e3dc82db2d3b26977686290cc5a17a7a5ee07ee4b87"
          }
    , machineSchemaVariantsValue =
        viewsDiscoveredVariant
          :| [ viewAcquisitionFailedVariant
             , viewAdapterSelectionFailedVariant
             , viewAdapterDecodeFailedVariant
             ]
    }

qualificationSubjectsPrerequisiteRejectedVariant :: SchemaVariant
qualificationSubjectsPrerequisiteRejectedVariant =
  SchemaVariant "qualification-subjects-prerequisite-rejected"

qualificationSubjectsDiscoveredVariant :: SchemaVariant
qualificationSubjectsDiscoveredVariant =
  SchemaVariant "qualification-subjects-discovered"

qualificationSubjectsMachineSchema :: MachineSchema
qualificationSubjectsMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.qualification-subjects"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "2955af496ca7c2e15d946b27407758980b95409930483b06d2344d06d144cdfb"
          }
    , machineSchemaVariantsValue =
        qualificationSubjectsPrerequisiteRejectedVariant
          :| [qualificationSubjectsDiscoveredVariant]
    }

notationValidationAcceptedVariant :: SchemaVariant
notationValidationAcceptedVariant = SchemaVariant "notation-validation-accepted"

notationValidationRejectedVariant :: SchemaVariant
notationValidationRejectedVariant = SchemaVariant "notation-validation-rejected"

profileValidationAcceptedVariant :: SchemaVariant
profileValidationAcceptedVariant = SchemaVariant "profile-validation-accepted"

profileValidationRejectedVariant :: SchemaVariant
profileValidationRejectedVariant = SchemaVariant "profile-validation-rejected"

structureValidationAcceptedVariant :: SchemaVariant
structureValidationAcceptedVariant =
  SchemaVariant "structure-validation-accepted"

structureValidationRejectedVariant :: SchemaVariant
structureValidationRejectedVariant =
  SchemaVariant "structure-validation-rejected"

semanticsValidationAcceptedVariant :: SchemaVariant
semanticsValidationAcceptedVariant =
  SchemaVariant "semantics-validation-accepted"

semanticsValidationRejectedVariant :: SchemaVariant
semanticsValidationRejectedVariant =
  SchemaVariant "semantics-validation-rejected"

semanticsValidationUnavailableVariant :: SchemaVariant
semanticsValidationUnavailableVariant =
  SchemaVariant "semantics-validation-unavailable"

validateResultMachineSchema :: MachineSchema
validateResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.validate"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "85ea7f0955303326d67340df20af1143025e4a35f98886763bb6726b4797f48e"
          }
    , machineSchemaVariantsValue =
        notationValidationAcceptedVariant
          :| [ notationValidationRejectedVariant
             , profileValidationAcceptedVariant
             , profileValidationRejectedVariant
             , structureValidationAcceptedVariant
             , structureValidationRejectedVariant
             , semanticsValidationAcceptedVariant
             , semanticsValidationRejectedVariant
             , semanticsValidationUnavailableVariant
             ]
    }

tracePrerequisiteRejectedVariant :: SchemaVariant
tracePrerequisiteRejectedVariant = SchemaVariant "trace-prerequisite-rejected"

traceRejectedVariant :: SchemaVariant
traceRejectedVariant = SchemaVariant "trace-rejected"

traceAcceptedVariant :: SchemaVariant
traceAcceptedVariant = SchemaVariant "trace-accepted"

traceResultMachineSchema :: MachineSchema
traceResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.trace"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "34b045904eb5bd80f4c1760d4b14036e0c024eb05d10fbc02aa87fd54b4239bb"
          }
    , machineSchemaVariantsValue =
        tracePrerequisiteRejectedVariant
          :| [traceRejectedVariant, traceAcceptedVariant]
    }

qualifyPrerequisiteRejectedVariant :: SchemaVariant
qualifyPrerequisiteRejectedVariant =
  SchemaVariant "qualify-prerequisite-rejected"

qualifyCompletedVariant :: SchemaVariant
qualifyCompletedVariant = SchemaVariant "qualify-completed"

qualifyResultMachineSchema :: MachineSchema
qualifyResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.qualify"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "1a9ab41581da48bace1f6ac5fef249312a8e5c0bd94c3cec9a1e8836a8d11090"
          }
    , machineSchemaVariantsValue =
        qualifyPrerequisiteRejectedVariant :| [qualifyCompletedVariant]
    }

readinessPrerequisiteRejectedVariant :: SchemaVariant
readinessPrerequisiteRejectedVariant =
  SchemaVariant "readiness-prerequisite-rejected"

readinessSubjectUnavailableVariant :: SchemaVariant
readinessSubjectUnavailableVariant =
  SchemaVariant "readiness-subject-unavailable"

readinessNotReadyVariant :: SchemaVariant
readinessNotReadyVariant = SchemaVariant "readiness-not-ready"

readinessReadyVariant :: SchemaVariant
readinessReadyVariant = SchemaVariant "readiness-ready"

readinessResultMachineSchema :: MachineSchema
readinessResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.readiness"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "1a716ec294e56cc91e462cea837947e2bf69a1859f774f121bbdb6c5d5be7603"
          }
    , machineSchemaVariantsValue =
        readinessPrerequisiteRejectedVariant
          :| [ readinessSubjectUnavailableVariant
             , readinessNotReadyVariant
             , readinessReadyVariant
             ]
    }

diagnosticSchemaAuthority :: SchemaAuthority
diagnosticSchemaAuthority =
  SchemaAuthority
    { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.diagnostic"
    , schemaAuthorityVersionValue = SchemaVersion 2
    , schemaAuthorityDigestValue =
        SchemaDigest
          "ff4e550795d72b8cfbd2502d146266512623d0f1801fc6e3f1ce807b85167788"
    }
