{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Schema.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import O2I.Operation.Schema.Internal

adapterInventoryVariant :: SchemaVariant
adapterInventoryVariant = SchemaVariant "adapter-inventory"

adapterInventoryMachineSchema :: MachineSchema
adapterInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.adapter-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "9ebc6cba58375277366bf50e83bda032344e4aff76f378f4c32ede43eaf04149"
          }
    , machineSchemaVariantsValue = adapterInventoryVariant :| []
    }

profileInventoryVariant :: SchemaVariant
profileInventoryVariant = SchemaVariant "profile-inventory"

profileDefinitionInvalidVariant :: SchemaVariant
profileDefinitionInvalidVariant =
  SchemaVariant "profile-static-definition-invalid"

profileInventoryMachineSchema :: MachineSchema
profileInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.profile-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "cb3e8626972fabf979f729cd71761d46df0ffde7c710357b02e42b058d467a6a"
          }
    , machineSchemaVariantsValue =
        profileInventoryVariant :| [profileDefinitionInvalidVariant]
    }

ruleInventoryVariant :: SchemaVariant
ruleInventoryVariant = SchemaVariant "rule-inventory"

ruleDefinitionInvalidVariant :: SchemaVariant
ruleDefinitionInvalidVariant = SchemaVariant "rule-static-definition-invalid"

ruleInventoryMachineSchema :: MachineSchema
ruleInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "58648f3f9edd15d5ca9c3b042271547694062f0bde7cbc9f21d9e41ee63519b1"
          }
    , machineSchemaVariantsValue =
        ruleInventoryVariant :| [ruleDefinitionInvalidVariant]
    }

ruleExplanationFoundVariant :: SchemaVariant
ruleExplanationFoundVariant = SchemaVariant "rule-explanation-found"

ruleExplanationNotFoundVariant :: SchemaVariant
ruleExplanationNotFoundVariant = SchemaVariant "rule-explanation-not-found"

ruleExplanationMachineSchema :: MachineSchema
ruleExplanationMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-explanation"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "a8c10312335adc2fa8a0a449057c3177a0f9d74b416449b8f9e9dc02ddc67e8a"
          }
    , machineSchemaVariantsValue =
        ruleExplanationFoundVariant :| [ruleExplanationNotFoundVariant]
    }

viewsDiscoveredVariant :: SchemaVariant
viewsDiscoveredVariant = SchemaVariant "views-discovered"

viewAcquisitionFailedVariant :: SchemaVariant
viewAcquisitionFailedVariant = SchemaVariant "view-acquisition-failed"

viewAdapterSelectionFailedVariant :: SchemaVariant
viewAdapterSelectionFailedVariant =
  SchemaVariant "view-adapter-selection-failed"

viewAdapterDecodeFailedVariant :: SchemaVariant
viewAdapterDecodeFailedVariant = SchemaVariant "view-adapter-decode-failed"

viewDiscoveryMachineSchema :: MachineSchema
viewDiscoveryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.discovery.view"
          , schemaAuthorityVersionValue = SchemaVersion 2
          , schemaAuthorityDigestValue =
              SchemaDigest
                "596b82ae5bc9c900c5094e3dc82db2d3b26977686290cc5a17a7a5ee07ee4b87"
          }
    , machineSchemaVariantsValue =
        viewsDiscoveredVariant
          :| [ viewAcquisitionFailedVariant
             , viewAdapterSelectionFailedVariant
             , viewAdapterDecodeFailedVariant
             ]
    }

diagnosticSchemaAuthority :: SchemaAuthority
diagnosticSchemaAuthority =
  SchemaAuthority
    { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.diagnostic"
    , schemaAuthorityVersionValue = SchemaVersion 2
    , schemaAuthorityDigestValue =
        SchemaDigest
          "becc0cc4dc574200325c702a872ed53d748d9f9a47fafda075d1b2832cc01183"
    }
