{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Schema.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import O2I.Operation.Schema.Internal

adapterInventoryVariant :: SchemaVariant
adapterInventoryVariant = SchemaVariant "adapter-inventory"

adapterInventoryMachineSchema :: MachineSchema
adapterInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.adapter-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "9ebc6cba58375277366bf50e83bda032344e4aff76f378f4c32ede43eaf04149"
          }
    , machineSchemaVariantsValue = adapterInventoryVariant :| []
    }

profileInventoryVariant :: SchemaVariant
profileInventoryVariant = SchemaVariant "profile-inventory"

profileDefinitionInvalidVariant :: SchemaVariant
profileDefinitionInvalidVariant =
  SchemaVariant "profile-static-definition-invalid"

profileInventoryMachineSchema :: MachineSchema
profileInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.profile-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "cb3e8626972fabf979f729cd71761d46df0ffde7c710357b02e42b058d467a6a"
          }
    , machineSchemaVariantsValue =
        profileInventoryVariant :| [profileDefinitionInvalidVariant]
    }

ruleInventoryVariant :: SchemaVariant
ruleInventoryVariant = SchemaVariant "rule-inventory"

ruleDefinitionInvalidVariant :: SchemaVariant
ruleDefinitionInvalidVariant = SchemaVariant "rule-static-definition-invalid"

ruleInventoryMachineSchema :: MachineSchema
ruleInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "58648f3f9edd15d5ca9c3b042271547694062f0bde7cbc9f21d9e41ee63519b1"
          }
    , machineSchemaVariantsValue =
        ruleInventoryVariant :| [ruleDefinitionInvalidVariant]
    }

ruleExplanationFoundVariant :: SchemaVariant
ruleExplanationFoundVariant = SchemaVariant "rule-explanation-found"

ruleExplanationNotFoundVariant :: SchemaVariant
ruleExplanationNotFoundVariant = SchemaVariant "rule-explanation-not-found"

ruleExplanationMachineSchema :: MachineSchema
ruleExplanationMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-explanation"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "a8c10312335adc2fa8a0a449057c3177a0f9d74b416449b8f9e9dc02ddc67e8a"
          }
    , machineSchemaVariantsValue =
        ruleExplanationFoundVariant :| [ruleExplanationNotFoundVariant]
    }

viewsDiscoveredVariant :: SchemaVariant
viewsDiscoveredVariant = SchemaVariant "views-discovered"

viewAcquisitionFailedVariant :: SchemaVariant
viewAcquisitionFailedVariant = SchemaVariant "view-acquisition-failed"

viewAdapterSelectionFailedVariant :: SchemaVariant
viewAdapterSelectionFailedVariant =
  SchemaVariant "view-adapter-selection-failed"

viewAdapterDecodeFailedVariant :: SchemaVariant
viewAdapterDecodeFailedVariant = SchemaVariant "view-adapter-decode-failed"

viewDiscoveryMachineSchema :: MachineSchema
viewDiscoveryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.discovery.view"
          , schemaAuthorityVersionValue = SchemaVersion 2
          , schemaAuthorityDigestValue =
              SchemaDigest
                "596b82ae5bc9c900c5094e3dc82db2d3b26977686290cc5a17a7a5ee07ee4b87"
          }
    , machineSchemaVariantsValue =
        viewsDiscoveredVariant
          :| [ viewAcquisitionFailedVariant
             , viewAdapterSelectionFailedVariant
             , viewAdapterDecodeFailedVariant
             ]
    }

qualificationSubjectsPrerequisiteRejectedVariant :: SchemaVariant
qualificationSubjectsPrerequisiteRejectedVariant =
  SchemaVariant "qualification-subjects-prerequisite-rejected"

qualificationSubjectsDiscoveredVariant :: SchemaVariant
qualificationSubjectsDiscoveredVariant =
  SchemaVariant "qualification-subjects-discovered"

qualificationSubjectsMachineSchema :: MachineSchema
qualificationSubjectsMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.qualification-subjects"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "ae3370f663f94af6f32ab9b3b5b736a6df8cc4ca283d5b056a5e489f0c96fa85"
          }
    , machineSchemaVariantsValue =
        qualificationSubjectsPrerequisiteRejectedVariant
          :| [qualificationSubjectsDiscoveredVariant]
    }

notationValidationAcceptedVariant :: SchemaVariant
notationValidationAcceptedVariant = SchemaVariant "notation-validation-accepted"

notationValidationRejectedVariant :: SchemaVariant
notationValidationRejectedVariant = SchemaVariant "notation-validation-rejected"

profileValidationAcceptedVariant :: SchemaVariant
profileValidationAcceptedVariant = SchemaVariant "profile-validation-accepted"

profileValidationRejectedVariant :: SchemaVariant
profileValidationRejectedVariant = SchemaVariant "profile-validation-rejected"

structureValidationAcceptedVariant :: SchemaVariant
structureValidationAcceptedVariant =
  SchemaVariant "structure-validation-accepted"

structureValidationRejectedVariant :: SchemaVariant
structureValidationRejectedVariant =
  SchemaVariant "structure-validation-rejected"

semanticsValidationAcceptedVariant :: SchemaVariant
semanticsValidationAcceptedVariant =
  SchemaVariant "semantics-validation-accepted"

semanticsValidationRejectedVariant :: SchemaVariant
semanticsValidationRejectedVariant =
  SchemaVariant "semantics-validation-rejected"

semanticsValidationUnavailableVariant :: SchemaVariant
semanticsValidationUnavailableVariant =
  SchemaVariant "semantics-validation-unavailable"

validateResultMachineSchema :: MachineSchema
validateResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.validate"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "20b7ff7a2058a2529daba19354928eb35d5a334c2f31cc2011a80acf5b8fe4c3"
          }
    , machineSchemaVariantsValue =
        notationValidationAcceptedVariant
          :| [ notationValidationRejectedVariant
             , profileValidationAcceptedVariant
             , profileValidationRejectedVariant
             , structureValidationAcceptedVariant
             , structureValidationRejectedVariant
             , semanticsValidationAcceptedVariant
             , semanticsValidationRejectedVariant
             , semanticsValidationUnavailableVariant
             ]
    }

tracePrerequisiteRejectedVariant :: SchemaVariant
tracePrerequisiteRejectedVariant = SchemaVariant "trace-prerequisite-rejected"

traceRejectedVariant :: SchemaVariant
traceRejectedVariant = SchemaVariant "trace-rejected"

traceAcceptedVariant :: SchemaVariant
traceAcceptedVariant = SchemaVariant "trace-accepted"

traceResultMachineSchema :: MachineSchema
traceResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.trace"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "4071317b5446643d5cbf0384ea3b3b0fb2c7db4bd9d5e3fae8fad28b50bd7bd2"
          }
    , machineSchemaVariantsValue =
        tracePrerequisiteRejectedVariant
          :| [traceRejectedVariant, traceAcceptedVariant]
    }

qualifyPrerequisiteRejectedVariant :: SchemaVariant
qualifyPrerequisiteRejectedVariant =
  SchemaVariant "qualify-prerequisite-rejected"

qualifyCompletedVariant :: SchemaVariant
qualifyCompletedVariant = SchemaVariant "qualify-completed"

qualifyResultMachineSchema :: MachineSchema
qualifyResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.qualify"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "a31ab4971f10ef68763e00fa0532d626bce45cd937523279813afd000fad5dfa"
          }
    , machineSchemaVariantsValue =
        qualifyPrerequisiteRejectedVariant :| [qualifyCompletedVariant]
    }

readinessPrerequisiteRejectedVariant :: SchemaVariant
readinessPrerequisiteRejectedVariant =
  SchemaVariant "readiness-prerequisite-rejected"

readinessSubjectUnavailableVariant :: SchemaVariant
readinessSubjectUnavailableVariant =
  SchemaVariant "readiness-subject-unavailable"

readinessNotReadyVariant :: SchemaVariant
readinessNotReadyVariant = SchemaVariant "readiness-not-ready"

readinessReadyVariant :: SchemaVariant
readinessReadyVariant = SchemaVariant "readiness-ready"

readinessResultMachineSchema :: MachineSchema
readinessResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.readiness"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "fac7a120baf1ecfd1b889bd65deb8067bb2eb5acb5c473b10a701f24edfc9352"
          }
    , machineSchemaVariantsValue =
        readinessPrerequisiteRejectedVariant
          :| [ readinessSubjectUnavailableVariant
             , readinessNotReadyVariant
             , readinessReadyVariant
             ]
    }

assessPrerequisiteRejectedVariant :: SchemaVariant
assessPrerequisiteRejectedVariant = SchemaVariant "assess-prerequisite-rejected"

assessSubjectUnavailableVariant :: SchemaVariant
assessSubjectUnavailableVariant = SchemaVariant "assess-subject-unavailable"

assessCollectionInvalidVariant :: SchemaVariant
assessCollectionInvalidVariant = SchemaVariant "assess-collection-invalid"

assessObservationsInvalidVariant :: SchemaVariant
assessObservationsInvalidVariant = SchemaVariant "assess-observations-invalid"

assessCompletedVariant :: SchemaVariant
assessCompletedVariant = SchemaVariant "assess-completed"

assessResultMachineSchema :: MachineSchema
assessResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.assess"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "0e0a6339678509db305ca174583c0ca187ebd96c79fd45fa11a0d5167445d1e7"
          }
    , machineSchemaVariantsValue =
        assessPrerequisiteRejectedVariant
          :| [ assessSubjectUnavailableVariant
             , assessCollectionInvalidVariant
             , assessObservationsInvalidVariant
             , assessCompletedVariant
             ]
    }

diagnosticSchemaAuthority :: SchemaAuthority
diagnosticSchemaAuthority =
  SchemaAuthority
    { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.diagnostic"
    , schemaAuthorityVersionValue = SchemaVersion 2
    , schemaAuthorityDigestValue =
        SchemaDigest
          "ff4e550795d72b8cfbd2502d146266512623d0f1801fc6e3f1ce807b85167788"
    }
