-- | Public facade for the O2I semantic language and validation core.
--
-- Language defines admissible O2I meaning, Graph represents concrete model
-- instances, and Validation establishes progressively stronger guarantees.
module O2I
  ( RawNodeId(..)
  , ContextRef
  , contextRefId
  , Context(..)
  , Primitive(..)
  , Structuring(..)
  , SituationAnchor(..)
  , NodeKindValue(..)
  , SContext(..)
  , SPrimitive(..)
  , SStructuring(..)
  , SSituationAnchor(..)
  , contextValue
  , primitiveValue
  , nodeKindValue
  , InterpretationCode(..)
  , SomeInterpretation
  , interpretationCodeOf
  , interpretationIdentity
  , allInterpretations
  , lookupInterpretation
  , Relation
  , SomeRelation
  , FixedRelationCode(..)
  , AnchorRelationFamily(..)
  , RelationCode(..)
  , RelationSemantics(..)
  , MacroEvidenceKind(..)
  , RelationName(..)
  , relationNameFor
  , relationNameOf
  , relationCodeOf
  , relationIdentity
  , guidesMission
  , groundsVision
  , guidesVision
  , orientsStrategy
  , directsStrategy
  , contributesToStrategy
  , qualifiesNeed
  , surfacesNeed
  , addressesNeed
  , directsIntervention
  , changesSituation
  , setsTargetForMeasure
  , measuresSituation
  , framesMeasure
  , constitutedByAnchor
  , guidesEthosPrincipleToMissionDriver
  , guidesEthosPrincipleToVisionObjective
  , groundsMissionDriverToVisionObjective
  , orientsVisionObjectiveToStrategyObjective
  , groundsStrategyDriverToObjective
  , substantiatesStrategyKeyResultObjective
  , guidesStrategyPrincipleToAction
  , contributesStrategyActionToKeyResult
  , guidesStrategyPrincipleToPrinciple
  , contributesStrategyKeyResultToKeyResult
  , contributesStrategyActionToAction
  , translatesStrategyKeyResultToNeedObjective
  , groundsNeedDriverToObjective
  , anchorsNeedDriver
  , indicatesMeasureDomain
  , determinesMeasureDomain
  , containsStrategyKeyResult
  , containsMeasureKPI
  , guidesStrategyActionToInterventionAction
  , contributesInterventionActionToKeyResult
  , substantiatesInterventionKeyResultNeedObjective
  , contributesInterventionKeyResultToStrategyKeyResult
  , setsTargetForMeasureKPI
  , changesAnchor
  , measuresAnchor
  , allRelationCodes
  , allRelations
  , lookupRelations
  , module O2I.Graph
  , StrategyAnchoring(..)
  , RawStrategyFormulation(..)
  , StrategyFormulation
  , StrategyTextField(..)
  , StrategyPrimitiveRole(..)
  , SemanticallyValidModel
  , strategyFormulations
  , strategyFormulationData
  , EffectTrace
  , EffectTraceId
  , TraceableEffectModel
  , effectTraces
  , traceIdentifier
  , lookupEffectTrace
  , traceNeed
  , traceInterventionKeyResult
  , traceKPI
  , traceAnchor
  , Unit(..)
  , Quantity(..)
  , EvidenceSource(..)
  , Observation(..)
  , EffectCriterion(..)
  , TargetCriterion(..)
  , EvidencePlan(..)
  , EvidenceClaim(..)
  , CriterionResult(..)
  , TargetResult(..)
  , EffectAssessment(..)
  , EvidenceAssessedModel
  , effectAssessments
  , isEffectiveNeed
  , Validation(..)
  , Check
  , StructuralError(..)
  , ModelInvariantError(..)
  , TraceabilityError(..)
  , EvidenceError(..)
  , validateStructure
  , validateModelSemantics
  , validateTraceability
  , assessEffectEvidence
  ) where

import O2I.Graph
import O2I.Language
import O2I.Validation
