{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Command.Error.Branch.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import Data.Text (Text)
import qualified O2I.Operation.Assess.Result.Internal as AssessInternal
import qualified O2I.Operation.Qualify.Result.Internal as QualifyInternal
import qualified O2I.Operation.Readiness.Result.Internal as ReadinessInternal
import qualified O2I.Operation.Validate.Result.Internal as ValidateInternal

data ValidateOwnerBranch
  = GeneratedValidateAcquiredModelRole
  | GeneratedValidateAcquiredSupplementalRole
  | GeneratedValidateSelectedAdapterContract
  | GeneratedValidateNotationContract
  | GeneratedValidateProfileContract
  | GeneratedValidateIdentityIndex
  | GeneratedValidateSelectedViewScope
  | GeneratedValidateStructureInput
  | GeneratedValidateSupplementalProvenance
  | GeneratedValidateSemanticUnavailableContract
  deriving (Bounded, Enum, Eq, Ord, Show)

validateOwnerBranchToken :: ValidateOwnerBranch -> Text
validateOwnerBranchToken branch =
  case branch of
    GeneratedValidateAcquiredModelRole -> "acquired-model-role"
    GeneratedValidateAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedValidateSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedValidateNotationContract -> "notation-contract"
    GeneratedValidateProfileContract -> "profile-contract"
    GeneratedValidateIdentityIndex -> "identity-index"
    GeneratedValidateSelectedViewScope -> "selected-view-scope"
    GeneratedValidateStructureInput -> "structure-input"
    GeneratedValidateSupplementalProvenance -> "supplemental-provenance"
    GeneratedValidateSemanticUnavailableContract ->
      "semantic-unavailable-contract"

validateOwnerBranches :: NonEmpty ValidateOwnerBranch
validateOwnerBranches =
  GeneratedValidateAcquiredModelRole
    :| [ GeneratedValidateAcquiredSupplementalRole
       , GeneratedValidateSelectedAdapterContract
       , GeneratedValidateNotationContract
       , GeneratedValidateProfileContract
       , GeneratedValidateIdentityIndex
       , GeneratedValidateSelectedViewScope
       , GeneratedValidateStructureInput
       , GeneratedValidateSupplementalProvenance
       , GeneratedValidateSemanticUnavailableContract
       ]

validateOwnerBranch ::
     ValidateInternal.ValidateInternalFailure -> ValidateOwnerBranch
validateOwnerBranch failure =
  case failure of
    ValidateInternal.ValidateAcquiredModelRoleFailure _ ->
      GeneratedValidateAcquiredModelRole
    ValidateInternal.ValidateAcquiredSupplementalRoleFailure _ ->
      GeneratedValidateAcquiredSupplementalRole
    ValidateInternal.ValidateSelectedAdapterContractFailure _ ->
      GeneratedValidateSelectedAdapterContract
    ValidateInternal.ValidateNotationContractFailure _ ->
      GeneratedValidateNotationContract
    ValidateInternal.ValidateProfileContractFailure _ ->
      GeneratedValidateProfileContract
    ValidateInternal.ValidateIdentityIndexFailure _ ->
      GeneratedValidateIdentityIndex
    ValidateInternal.ValidateSelectedViewScopeFailure _ ->
      GeneratedValidateSelectedViewScope
    ValidateInternal.ValidateStructureInputFailure _ ->
      GeneratedValidateStructureInput
    ValidateInternal.ValidateSupplementalProvenanceFailure _ ->
      GeneratedValidateSupplementalProvenance
    ValidateInternal.ValidateSemanticUnavailableContractFailure _ ->
      GeneratedValidateSemanticUnavailableContract

data QualifyOwnerBranch
  = GeneratedQualifyAcquiredModelRole
  | GeneratedQualifyAcquiredSupplementalRole
  | GeneratedQualifySelectedAdapterContract
  | GeneratedQualifyNotationContract
  | GeneratedQualifyProfileContract
  | GeneratedQualifyIdentityIndex
  | GeneratedQualifySelectedViewScope
  | GeneratedQualifyStructureInput
  | GeneratedQualifySupplementalProvenance
  | GeneratedQualifyContext
  deriving (Bounded, Enum, Eq, Ord, Show)

qualifyOwnerBranchToken :: QualifyOwnerBranch -> Text
qualifyOwnerBranchToken branch =
  case branch of
    GeneratedQualifyAcquiredModelRole -> "acquired-model-role"
    GeneratedQualifyAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedQualifySelectedAdapterContract -> "selected-adapter-contract"
    GeneratedQualifyNotationContract -> "notation-contract"
    GeneratedQualifyProfileContract -> "profile-contract"
    GeneratedQualifyIdentityIndex -> "identity-index"
    GeneratedQualifySelectedViewScope -> "selected-view-scope"
    GeneratedQualifyStructureInput -> "structure-input"
    GeneratedQualifySupplementalProvenance -> "supplemental-provenance"
    GeneratedQualifyContext -> "qualification-context"

qualifyOwnerBranches :: NonEmpty QualifyOwnerBranch
qualifyOwnerBranches =
  GeneratedQualifyAcquiredModelRole
    :| [ GeneratedQualifyAcquiredSupplementalRole
       , GeneratedQualifySelectedAdapterContract
       , GeneratedQualifyNotationContract
       , GeneratedQualifyProfileContract
       , GeneratedQualifyIdentityIndex
       , GeneratedQualifySelectedViewScope
       , GeneratedQualifyStructureInput
       , GeneratedQualifySupplementalProvenance
       , GeneratedQualifyContext
       ]

qualifyOwnerBranch ::
     QualifyInternal.QualifyInternalFailure -> QualifyOwnerBranch
qualifyOwnerBranch failure =
  case failure of
    QualifyInternal.QualifyAcquiredModelRoleFailure _ ->
      GeneratedQualifyAcquiredModelRole
    QualifyInternal.QualifyAcquiredSupplementalRoleFailure _ ->
      GeneratedQualifyAcquiredSupplementalRole
    QualifyInternal.QualifySelectedAdapterContractFailure _ ->
      GeneratedQualifySelectedAdapterContract
    QualifyInternal.QualifyNotationContractFailure _ ->
      GeneratedQualifyNotationContract
    QualifyInternal.QualifyProfileContractFailure _ ->
      GeneratedQualifyProfileContract
    QualifyInternal.QualifyIdentityIndexFailure _ ->
      GeneratedQualifyIdentityIndex
    QualifyInternal.QualifySelectedViewScopeFailure _ ->
      GeneratedQualifySelectedViewScope
    QualifyInternal.QualifyStructureInputFailure _ ->
      GeneratedQualifyStructureInput
    QualifyInternal.QualifySupplementalProvenanceFailure _ ->
      GeneratedQualifySupplementalProvenance
    QualifyInternal.QualifyContextFailure _ -> GeneratedQualifyContext

data ReadinessOwnerBranch
  = GeneratedReadinessAcquiredModelRole
  | GeneratedReadinessAcquiredEvidenceRole
  | GeneratedReadinessAcquiredSupplementalRole
  | GeneratedReadinessSelectedAdapterContract
  | GeneratedReadinessNotationContract
  | GeneratedReadinessProfileContract
  | GeneratedReadinessIdentityIndex
  | GeneratedReadinessSelectedViewScope
  | GeneratedReadinessStructureInput
  | GeneratedReadinessSupplementalProvenance
  | GeneratedReadinessSemanticModelContract
  deriving (Bounded, Enum, Eq, Ord, Show)

readinessOwnerBranchToken :: ReadinessOwnerBranch -> Text
readinessOwnerBranchToken branch =
  case branch of
    GeneratedReadinessAcquiredModelRole -> "acquired-model-role"
    GeneratedReadinessAcquiredEvidenceRole -> "acquired-readiness-role"
    GeneratedReadinessAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedReadinessSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedReadinessNotationContract -> "notation-contract"
    GeneratedReadinessProfileContract -> "profile-contract"
    GeneratedReadinessIdentityIndex -> "identity-index"
    GeneratedReadinessSelectedViewScope -> "selected-view-scope"
    GeneratedReadinessStructureInput -> "structure-input"
    GeneratedReadinessSupplementalProvenance -> "supplemental-provenance"
    GeneratedReadinessSemanticModelContract -> "semantic-model-contract"

readinessOwnerBranches :: NonEmpty ReadinessOwnerBranch
readinessOwnerBranches =
  GeneratedReadinessAcquiredModelRole
    :| [ GeneratedReadinessAcquiredEvidenceRole
       , GeneratedReadinessAcquiredSupplementalRole
       , GeneratedReadinessSelectedAdapterContract
       , GeneratedReadinessNotationContract
       , GeneratedReadinessProfileContract
       , GeneratedReadinessIdentityIndex
       , GeneratedReadinessSelectedViewScope
       , GeneratedReadinessStructureInput
       , GeneratedReadinessSupplementalProvenance
       , GeneratedReadinessSemanticModelContract
       ]

readinessOwnerBranch ::
     ReadinessInternal.ReadinessInternalFailure -> ReadinessOwnerBranch
readinessOwnerBranch failure =
  case failure of
    ReadinessInternal.ReadinessAcquiredModelRoleFailure _ ->
      GeneratedReadinessAcquiredModelRole
    ReadinessInternal.ReadinessAcquiredEvidenceRoleFailure _ ->
      GeneratedReadinessAcquiredEvidenceRole
    ReadinessInternal.ReadinessAcquiredSupplementalRoleFailure _ ->
      GeneratedReadinessAcquiredSupplementalRole
    ReadinessInternal.ReadinessSelectedAdapterContractFailure _ ->
      GeneratedReadinessSelectedAdapterContract
    ReadinessInternal.ReadinessNotationContractFailure _ ->
      GeneratedReadinessNotationContract
    ReadinessInternal.ReadinessProfileContractFailure _ ->
      GeneratedReadinessProfileContract
    ReadinessInternal.ReadinessIdentityIndexFailure _ ->
      GeneratedReadinessIdentityIndex
    ReadinessInternal.ReadinessSelectedViewScopeFailure _ ->
      GeneratedReadinessSelectedViewScope
    ReadinessInternal.ReadinessStructureInputFailure _ ->
      GeneratedReadinessStructureInput
    ReadinessInternal.ReadinessSupplementalProvenanceFailure _ ->
      GeneratedReadinessSupplementalProvenance
    ReadinessInternal.ReadinessSemanticModelContractFailure _ ->
      GeneratedReadinessSemanticModelContract

data AssessOwnerBranch
  = GeneratedAssessAcquiredModelRole
  | GeneratedAssessAcquiredBundleRole
  | GeneratedAssessAcquiredSupplementalRole
  | GeneratedAssessSelectedAdapterContract
  | GeneratedAssessNotationContract
  | GeneratedAssessProfileContract
  | GeneratedAssessIdentityIndex
  | GeneratedAssessSelectedViewScope
  | GeneratedAssessStructureInput
  | GeneratedAssessSupplementalProvenance
  | GeneratedAssessSemanticModelContract
  deriving (Bounded, Enum, Eq, Ord, Show)

assessOwnerBranchToken :: AssessOwnerBranch -> Text
assessOwnerBranchToken branch =
  case branch of
    GeneratedAssessAcquiredModelRole -> "acquired-model-role"
    GeneratedAssessAcquiredBundleRole -> "acquired-assessment-role"
    GeneratedAssessAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedAssessSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedAssessNotationContract -> "notation-contract"
    GeneratedAssessProfileContract -> "profile-contract"
    GeneratedAssessIdentityIndex -> "identity-index"
    GeneratedAssessSelectedViewScope -> "selected-view-scope"
    GeneratedAssessStructureInput -> "structure-input"
    GeneratedAssessSupplementalProvenance -> "supplemental-provenance"
    GeneratedAssessSemanticModelContract -> "semantic-model-contract"

assessOwnerBranches :: NonEmpty AssessOwnerBranch
assessOwnerBranches =
  GeneratedAssessAcquiredModelRole
    :| [ GeneratedAssessAcquiredBundleRole
       , GeneratedAssessAcquiredSupplementalRole
       , GeneratedAssessSelectedAdapterContract
       , GeneratedAssessNotationContract
       , GeneratedAssessProfileContract
       , GeneratedAssessIdentityIndex
       , GeneratedAssessSelectedViewScope
       , GeneratedAssessStructureInput
       , GeneratedAssessSupplementalProvenance
       , GeneratedAssessSemanticModelContract
       ]

assessOwnerBranch :: AssessInternal.AssessInternalFailure -> AssessOwnerBranch
assessOwnerBranch failure =
  case failure of
    AssessInternal.AssessAcquiredModelRoleFailure _ ->
      GeneratedAssessAcquiredModelRole
    AssessInternal.AssessAcquiredBundleRoleFailure _ ->
      GeneratedAssessAcquiredBundleRole
    AssessInternal.AssessAcquiredSupplementalRoleFailure _ ->
      GeneratedAssessAcquiredSupplementalRole
    AssessInternal.AssessSelectedAdapterContractFailure _ ->
      GeneratedAssessSelectedAdapterContract
    AssessInternal.AssessNotationContractFailure _ ->
      GeneratedAssessNotationContract
    AssessInternal.AssessProfileContractFailure _ ->
      GeneratedAssessProfileContract
    AssessInternal.AssessIdentityIndexFailure _ -> GeneratedAssessIdentityIndex
    AssessInternal.AssessSelectedViewScopeFailure _ ->
      GeneratedAssessSelectedViewScope
    AssessInternal.AssessStructureInputFailure _ ->
      GeneratedAssessStructureInput
    AssessInternal.AssessSupplementalProvenanceFailure _ ->
      GeneratedAssessSupplementalProvenance
    AssessInternal.AssessSemanticModelContractFailure _ ->
      GeneratedAssessSemanticModelContract

data CommandOwnerBranch
  = ValidateCommandOwnerBranch !ValidateOwnerBranch
  | QualifyCommandOwnerBranch !QualifyOwnerBranch
  | ReadinessCommandOwnerBranch !ReadinessOwnerBranch
  | AssessCommandOwnerBranch !AssessOwnerBranch
  deriving (Eq, Ord, Show)

commandOwnerBranchToken :: CommandOwnerBranch -> Text
commandOwnerBranchToken branch =
  case branch of
    ValidateCommandOwnerBranch capabilityBranch ->
      validateOwnerBranchToken capabilityBranch
    QualifyCommandOwnerBranch capabilityBranch ->
      qualifyOwnerBranchToken capabilityBranch
    ReadinessCommandOwnerBranch capabilityBranch ->
      readinessOwnerBranchToken capabilityBranch
    AssessCommandOwnerBranch capabilityBranch ->
      assessOwnerBranchToken capabilityBranch
