{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Command.Error.Branch.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import Data.Text (Text)
import qualified O2I.Operation.Assess.Result.Internal as AssessInternal
import qualified O2I.Operation.Qualification.Subjects.Result.Internal as QualificationSubjectsInternal
import qualified O2I.Operation.Qualify.Result.Internal as QualifyInternal
import qualified O2I.Operation.Readiness.Result.Internal as ReadinessInternal
import qualified O2I.Operation.Trace.Result.Internal as TraceInternal
import qualified O2I.Operation.Validate.Result.Internal as ValidateInternal

data ValidateOwnerBranch
  = GeneratedValidateAcquiredModelRole
  | GeneratedValidateAcquiredSupplementalRole
  | GeneratedValidateSelectedAdapterContract
  | GeneratedValidateNotationContract
  | GeneratedValidateProfileContract
  | GeneratedValidateIdentityIndex
  | GeneratedValidateSelectedViewScope
  | GeneratedValidateStructureInput
  | GeneratedValidateSupplementalProvenance
  | GeneratedValidateSemanticUnavailableContract
  deriving (Bounded, Enum, Eq, Ord, Show)

validateOwnerBranchToken :: ValidateOwnerBranch -> Text
validateOwnerBranchToken branch =
  case branch of
    GeneratedValidateAcquiredModelRole -> "acquired-model-role"
    GeneratedValidateAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedValidateSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedValidateNotationContract -> "notation-contract"
    GeneratedValidateProfileContract -> "profile-contract"
    GeneratedValidateIdentityIndex -> "identity-index"
    GeneratedValidateSelectedViewScope -> "selected-view-scope"
    GeneratedValidateStructureInput -> "structure-input"
    GeneratedValidateSupplementalProvenance -> "supplemental-provenance"
    GeneratedValidateSemanticUnavailableContract ->
      "semantic-unavailable-contract"

validateOwnerBranches :: NonEmpty ValidateOwnerBranch
validateOwnerBranches =
  GeneratedValidateAcquiredModelRole
    :| [ GeneratedValidateAcquiredSupplementalRole
       , GeneratedValidateSelectedAdapterContract
       , GeneratedValidateNotationContract
       , GeneratedValidateProfileContract
       , GeneratedValidateIdentityIndex
       , GeneratedValidateSelectedViewScope
       , GeneratedValidateStructureInput
       , GeneratedValidateSupplementalProvenance
       , GeneratedValidateSemanticUnavailableContract
       ]

validateOwnerBranch ::
     ValidateInternal.ValidateInternalFailure -> ValidateOwnerBranch
validateOwnerBranch failure =
  case failure of
    ValidateInternal.ValidateAcquiredModelRoleFailure {} ->
      GeneratedValidateAcquiredModelRole
    ValidateInternal.ValidateAcquiredSupplementalRoleFailure {} ->
      GeneratedValidateAcquiredSupplementalRole
    ValidateInternal.ValidateSelectedAdapterContractFailure {} ->
      GeneratedValidateSelectedAdapterContract
    ValidateInternal.ValidateNotationContractFailure {} ->
      GeneratedValidateNotationContract
    ValidateInternal.ValidateProfileContractFailure {} ->
      GeneratedValidateProfileContract
    ValidateInternal.ValidateIdentityIndexFailure {} ->
      GeneratedValidateIdentityIndex
    ValidateInternal.ValidateSelectedViewScopeFailure {} ->
      GeneratedValidateSelectedViewScope
    ValidateInternal.ValidateStructureInputFailure {} ->
      GeneratedValidateStructureInput
    ValidateInternal.ValidateSupplementalProvenanceFailure {} ->
      GeneratedValidateSupplementalProvenance
    ValidateInternal.ValidateSemanticUnavailableContractFailure {} ->
      GeneratedValidateSemanticUnavailableContract

data QualifyOwnerBranch
  = GeneratedQualifyAcquiredModelRole
  | GeneratedQualifyAcquiredSupplementalRole
  | GeneratedQualifySelectedAdapterContract
  | GeneratedQualifyNotationContract
  | GeneratedQualifyProfileContract
  | GeneratedQualifyIdentityIndex
  | GeneratedQualifySelectedViewScope
  | GeneratedQualifyStructureInput
  | GeneratedQualifySupplementalProvenance
  | GeneratedQualifyContext
  deriving (Bounded, Enum, Eq, Ord, Show)

qualifyOwnerBranchToken :: QualifyOwnerBranch -> Text
qualifyOwnerBranchToken branch =
  case branch of
    GeneratedQualifyAcquiredModelRole -> "acquired-model-role"
    GeneratedQualifyAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedQualifySelectedAdapterContract -> "selected-adapter-contract"
    GeneratedQualifyNotationContract -> "notation-contract"
    GeneratedQualifyProfileContract -> "profile-contract"
    GeneratedQualifyIdentityIndex -> "identity-index"
    GeneratedQualifySelectedViewScope -> "selected-view-scope"
    GeneratedQualifyStructureInput -> "structure-input"
    GeneratedQualifySupplementalProvenance -> "supplemental-provenance"
    GeneratedQualifyContext -> "qualification-context"

qualifyOwnerBranches :: NonEmpty QualifyOwnerBranch
qualifyOwnerBranches =
  GeneratedQualifyAcquiredModelRole
    :| [ GeneratedQualifyAcquiredSupplementalRole
       , GeneratedQualifySelectedAdapterContract
       , GeneratedQualifyNotationContract
       , GeneratedQualifyProfileContract
       , GeneratedQualifyIdentityIndex
       , GeneratedQualifySelectedViewScope
       , GeneratedQualifyStructureInput
       , GeneratedQualifySupplementalProvenance
       , GeneratedQualifyContext
       ]

qualifyOwnerBranch ::
     QualifyInternal.QualifyInternalFailure -> QualifyOwnerBranch
qualifyOwnerBranch failure =
  case failure of
    QualifyInternal.QualifyAcquiredModelRoleFailure {} ->
      GeneratedQualifyAcquiredModelRole
    QualifyInternal.QualifyAcquiredSupplementalRoleFailure {} ->
      GeneratedQualifyAcquiredSupplementalRole
    QualifyInternal.QualifySelectedAdapterContractFailure {} ->
      GeneratedQualifySelectedAdapterContract
    QualifyInternal.QualifyNotationContractFailure {} ->
      GeneratedQualifyNotationContract
    QualifyInternal.QualifyProfileContractFailure {} ->
      GeneratedQualifyProfileContract
    QualifyInternal.QualifyIdentityIndexFailure {} ->
      GeneratedQualifyIdentityIndex
    QualifyInternal.QualifySelectedViewScopeFailure {} ->
      GeneratedQualifySelectedViewScope
    QualifyInternal.QualifyStructureInputFailure {} ->
      GeneratedQualifyStructureInput
    QualifyInternal.QualifySupplementalProvenanceFailure {} ->
      GeneratedQualifySupplementalProvenance
    QualifyInternal.QualifyContextFailure {} -> GeneratedQualifyContext

data ReadinessOwnerBranch
  = GeneratedReadinessAcquiredModelRole
  | GeneratedReadinessAcquiredEvidenceRole
  | GeneratedReadinessAcquiredSupplementalRole
  | GeneratedReadinessSelectedAdapterContract
  | GeneratedReadinessNotationContract
  | GeneratedReadinessProfileContract
  | GeneratedReadinessIdentityIndex
  | GeneratedReadinessSelectedViewScope
  | GeneratedReadinessStructureInput
  | GeneratedReadinessSupplementalProvenance
  | GeneratedReadinessSemanticModelContract
  deriving (Bounded, Enum, Eq, Ord, Show)

readinessOwnerBranchToken :: ReadinessOwnerBranch -> Text
readinessOwnerBranchToken branch =
  case branch of
    GeneratedReadinessAcquiredModelRole -> "acquired-model-role"
    GeneratedReadinessAcquiredEvidenceRole -> "acquired-readiness-role"
    GeneratedReadinessAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedReadinessSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedReadinessNotationContract -> "notation-contract"
    GeneratedReadinessProfileContract -> "profile-contract"
    GeneratedReadinessIdentityIndex -> "identity-index"
    GeneratedReadinessSelectedViewScope -> "selected-view-scope"
    GeneratedReadinessStructureInput -> "structure-input"
    GeneratedReadinessSupplementalProvenance -> "supplemental-provenance"
    GeneratedReadinessSemanticModelContract -> "semantic-model-contract"

readinessOwnerBranches :: NonEmpty ReadinessOwnerBranch
readinessOwnerBranches =
  GeneratedReadinessAcquiredModelRole
    :| [ GeneratedReadinessAcquiredEvidenceRole
       , GeneratedReadinessAcquiredSupplementalRole
       , GeneratedReadinessSelectedAdapterContract
       , GeneratedReadinessNotationContract
       , GeneratedReadinessProfileContract
       , GeneratedReadinessIdentityIndex
       , GeneratedReadinessSelectedViewScope
       , GeneratedReadinessStructureInput
       , GeneratedReadinessSupplementalProvenance
       , GeneratedReadinessSemanticModelContract
       ]

readinessOwnerBranch ::
     ReadinessInternal.ReadinessInternalFailure -> ReadinessOwnerBranch
readinessOwnerBranch failure =
  case failure of
    ReadinessInternal.ReadinessAcquiredModelRoleFailure {} ->
      GeneratedReadinessAcquiredModelRole
    ReadinessInternal.ReadinessAcquiredEvidenceRoleFailure {} ->
      GeneratedReadinessAcquiredEvidenceRole
    ReadinessInternal.ReadinessAcquiredSupplementalRoleFailure {} ->
      GeneratedReadinessAcquiredSupplementalRole
    ReadinessInternal.ReadinessSelectedAdapterContractFailure {} ->
      GeneratedReadinessSelectedAdapterContract
    ReadinessInternal.ReadinessNotationContractFailure {} ->
      GeneratedReadinessNotationContract
    ReadinessInternal.ReadinessProfileContractFailure {} ->
      GeneratedReadinessProfileContract
    ReadinessInternal.ReadinessIdentityIndexFailure {} ->
      GeneratedReadinessIdentityIndex
    ReadinessInternal.ReadinessSelectedViewScopeFailure {} ->
      GeneratedReadinessSelectedViewScope
    ReadinessInternal.ReadinessStructureInputFailure {} ->
      GeneratedReadinessStructureInput
    ReadinessInternal.ReadinessSupplementalProvenanceFailure {} ->
      GeneratedReadinessSupplementalProvenance
    ReadinessInternal.ReadinessSemanticModelContractFailure {} ->
      GeneratedReadinessSemanticModelContract

data AssessOwnerBranch
  = GeneratedAssessAcquiredModelRole
  | GeneratedAssessAcquiredBundleRole
  | GeneratedAssessAcquiredSupplementalRole
  | GeneratedAssessSelectedAdapterContract
  | GeneratedAssessNotationContract
  | GeneratedAssessProfileContract
  | GeneratedAssessIdentityIndex
  | GeneratedAssessSelectedViewScope
  | GeneratedAssessStructureInput
  | GeneratedAssessSupplementalProvenance
  | GeneratedAssessSemanticModelContract
  deriving (Bounded, Enum, Eq, Ord, Show)

assessOwnerBranchToken :: AssessOwnerBranch -> Text
assessOwnerBranchToken branch =
  case branch of
    GeneratedAssessAcquiredModelRole -> "acquired-model-role"
    GeneratedAssessAcquiredBundleRole -> "acquired-assessment-role"
    GeneratedAssessAcquiredSupplementalRole -> "acquired-supplemental-role"
    GeneratedAssessSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedAssessNotationContract -> "notation-contract"
    GeneratedAssessProfileContract -> "profile-contract"
    GeneratedAssessIdentityIndex -> "identity-index"
    GeneratedAssessSelectedViewScope -> "selected-view-scope"
    GeneratedAssessStructureInput -> "structure-input"
    GeneratedAssessSupplementalProvenance -> "supplemental-provenance"
    GeneratedAssessSemanticModelContract -> "semantic-model-contract"

assessOwnerBranches :: NonEmpty AssessOwnerBranch
assessOwnerBranches =
  GeneratedAssessAcquiredModelRole
    :| [ GeneratedAssessAcquiredBundleRole
       , GeneratedAssessAcquiredSupplementalRole
       , GeneratedAssessSelectedAdapterContract
       , GeneratedAssessNotationContract
       , GeneratedAssessProfileContract
       , GeneratedAssessIdentityIndex
       , GeneratedAssessSelectedViewScope
       , GeneratedAssessStructureInput
       , GeneratedAssessSupplementalProvenance
       , GeneratedAssessSemanticModelContract
       ]

assessOwnerBranch :: AssessInternal.AssessInternalFailure -> AssessOwnerBranch
assessOwnerBranch failure =
  case failure of
    AssessInternal.AssessAcquiredModelRoleFailure {} ->
      GeneratedAssessAcquiredModelRole
    AssessInternal.AssessAcquiredBundleRoleFailure {} ->
      GeneratedAssessAcquiredBundleRole
    AssessInternal.AssessAcquiredSupplementalRoleFailure {} ->
      GeneratedAssessAcquiredSupplementalRole
    AssessInternal.AssessSelectedAdapterContractFailure {} ->
      GeneratedAssessSelectedAdapterContract
    AssessInternal.AssessNotationContractFailure {} ->
      GeneratedAssessNotationContract
    AssessInternal.AssessProfileContractFailure {} ->
      GeneratedAssessProfileContract
    AssessInternal.AssessIdentityIndexFailure {} -> GeneratedAssessIdentityIndex
    AssessInternal.AssessSelectedViewScopeFailure {} ->
      GeneratedAssessSelectedViewScope
    AssessInternal.AssessStructureInputFailure {} ->
      GeneratedAssessStructureInput
    AssessInternal.AssessSupplementalProvenanceFailure {} ->
      GeneratedAssessSupplementalProvenance
    AssessInternal.AssessSemanticModelContractFailure {} ->
      GeneratedAssessSemanticModelContract

data QualificationSubjectsOwnerBranch
  = GeneratedQualificationSubjectsAcquiredModelRole
  | GeneratedQualificationSubjectsAcquiredSupplementalRole
  | GeneratedQualificationSubjectsSelectedAdapterContract
  | GeneratedQualificationSubjectsNotationContract
  | GeneratedQualificationSubjectsProfileContract
  | GeneratedQualificationSubjectsIdentityIndex
  | GeneratedQualificationSubjectsSelectedViewScope
  | GeneratedQualificationSubjectsStructureInput
  | GeneratedQualificationSubjectsSupplementalProvenance
  | GeneratedQualificationSubjectsContext
  | GeneratedQualificationSubjectsOccurrenceProjection
  | GeneratedQualificationSubjectsOccurrenceJoin
  deriving (Bounded, Enum, Eq, Ord, Show)

qualificationSubjectsOwnerBranchToken ::
     QualificationSubjectsOwnerBranch -> Text
qualificationSubjectsOwnerBranchToken branch =
  case branch of
    GeneratedQualificationSubjectsAcquiredModelRole -> "acquired-model-role"
    GeneratedQualificationSubjectsAcquiredSupplementalRole ->
      "acquired-supplemental-role"
    GeneratedQualificationSubjectsSelectedAdapterContract ->
      "selected-adapter-contract"
    GeneratedQualificationSubjectsNotationContract -> "notation-contract"
    GeneratedQualificationSubjectsProfileContract -> "profile-contract"
    GeneratedQualificationSubjectsIdentityIndex -> "identity-index"
    GeneratedQualificationSubjectsSelectedViewScope -> "selected-view-scope"
    GeneratedQualificationSubjectsStructureInput -> "structure-input"
    GeneratedQualificationSubjectsSupplementalProvenance ->
      "supplemental-provenance"
    GeneratedQualificationSubjectsContext -> "qualification-context"
    GeneratedQualificationSubjectsOccurrenceProjection ->
      "occurrence-projection"
    GeneratedQualificationSubjectsOccurrenceJoin -> "occurrence-join"

qualificationSubjectsOwnerBranches :: NonEmpty QualificationSubjectsOwnerBranch
qualificationSubjectsOwnerBranches =
  GeneratedQualificationSubjectsAcquiredModelRole
    :| [ GeneratedQualificationSubjectsAcquiredSupplementalRole
       , GeneratedQualificationSubjectsSelectedAdapterContract
       , GeneratedQualificationSubjectsNotationContract
       , GeneratedQualificationSubjectsProfileContract
       , GeneratedQualificationSubjectsIdentityIndex
       , GeneratedQualificationSubjectsSelectedViewScope
       , GeneratedQualificationSubjectsStructureInput
       , GeneratedQualificationSubjectsSupplementalProvenance
       , GeneratedQualificationSubjectsContext
       , GeneratedQualificationSubjectsOccurrenceProjection
       , GeneratedQualificationSubjectsOccurrenceJoin
       ]

qualificationSubjectsOwnerBranch ::
     QualificationSubjectsInternal.QualificationSubjectsInternalFailure
  -> QualificationSubjectsOwnerBranch
qualificationSubjectsOwnerBranch failure =
  case failure of
    QualificationSubjectsInternal.QualificationSubjectsAcquiredModelRoleFailure {} ->
      GeneratedQualificationSubjectsAcquiredModelRole
    QualificationSubjectsInternal.QualificationSubjectsAcquiredSupplementalRoleFailure {} ->
      GeneratedQualificationSubjectsAcquiredSupplementalRole
    QualificationSubjectsInternal.QualificationSubjectsSelectedAdapterContractFailure {} ->
      GeneratedQualificationSubjectsSelectedAdapterContract
    QualificationSubjectsInternal.QualificationSubjectsNotationContractFailure {} ->
      GeneratedQualificationSubjectsNotationContract
    QualificationSubjectsInternal.QualificationSubjectsProfileContractFailure {} ->
      GeneratedQualificationSubjectsProfileContract
    QualificationSubjectsInternal.QualificationSubjectsIdentityIndexFailure {} ->
      GeneratedQualificationSubjectsIdentityIndex
    QualificationSubjectsInternal.QualificationSubjectsSelectedViewScopeFailure {} ->
      GeneratedQualificationSubjectsSelectedViewScope
    QualificationSubjectsInternal.QualificationSubjectsStructureInputFailure {} ->
      GeneratedQualificationSubjectsStructureInput
    QualificationSubjectsInternal.QualificationSubjectsSupplementalProvenanceFailure {} ->
      GeneratedQualificationSubjectsSupplementalProvenance
    QualificationSubjectsInternal.QualificationSubjectsContextFailure {} ->
      GeneratedQualificationSubjectsContext
    QualificationSubjectsInternal.QualificationSubjectsOccurrenceProjectionFailure {} ->
      GeneratedQualificationSubjectsOccurrenceProjection
    QualificationSubjectsInternal.QualificationSubjectsOccurrenceJoinFailure {} ->
      GeneratedQualificationSubjectsOccurrenceJoin

data TraceOwnerBranch
  = GeneratedTraceAcquiredModelRole
  | GeneratedTraceSelectedAdapterContract
  | GeneratedTraceNotationContract
  | GeneratedTraceProfileContract
  | GeneratedTraceIdentityIndex
  | GeneratedTraceSelectedViewScope
  | GeneratedTraceStructureInput
  | GeneratedTraceEmptyInputProvenance
  | GeneratedTraceEmptyInputContract
  | GeneratedTraceSemanticModelContract
  deriving (Bounded, Enum, Eq, Ord, Show)

traceOwnerBranchToken :: TraceOwnerBranch -> Text
traceOwnerBranchToken branch =
  case branch of
    GeneratedTraceAcquiredModelRole -> "acquired-model-role"
    GeneratedTraceSelectedAdapterContract -> "selected-adapter-contract"
    GeneratedTraceNotationContract -> "notation-contract"
    GeneratedTraceProfileContract -> "profile-contract"
    GeneratedTraceIdentityIndex -> "identity-index"
    GeneratedTraceSelectedViewScope -> "selected-view-scope"
    GeneratedTraceStructureInput -> "structure-input"
    GeneratedTraceEmptyInputProvenance -> "empty-input-provenance"
    GeneratedTraceEmptyInputContract -> "empty-input-contract"
    GeneratedTraceSemanticModelContract -> "semantic-model-contract"

traceOwnerBranches :: NonEmpty TraceOwnerBranch
traceOwnerBranches =
  GeneratedTraceAcquiredModelRole
    :| [ GeneratedTraceSelectedAdapterContract
       , GeneratedTraceNotationContract
       , GeneratedTraceProfileContract
       , GeneratedTraceIdentityIndex
       , GeneratedTraceSelectedViewScope
       , GeneratedTraceStructureInput
       , GeneratedTraceEmptyInputProvenance
       , GeneratedTraceEmptyInputContract
       , GeneratedTraceSemanticModelContract
       ]

traceOwnerBranch :: TraceInternal.TraceInternalFailure -> TraceOwnerBranch
traceOwnerBranch failure =
  case failure of
    TraceInternal.TraceAcquiredModelRoleFailure {} ->
      GeneratedTraceAcquiredModelRole
    TraceInternal.TraceSelectedAdapterContractFailure {} ->
      GeneratedTraceSelectedAdapterContract
    TraceInternal.TraceNotationContractFailure {} ->
      GeneratedTraceNotationContract
    TraceInternal.TraceProfileContractFailure {} ->
      GeneratedTraceProfileContract
    TraceInternal.TraceIdentityIndexFailure {} -> GeneratedTraceIdentityIndex
    TraceInternal.TraceSelectedViewScopeFailure {} ->
      GeneratedTraceSelectedViewScope
    TraceInternal.TraceStructureInputFailure {} -> GeneratedTraceStructureInput
    TraceInternal.TraceEmptyInputProvenanceFailure {} ->
      GeneratedTraceEmptyInputProvenance
    TraceInternal.TraceEmptyInputContractFailure {} ->
      GeneratedTraceEmptyInputContract
    TraceInternal.TraceSemanticModelContractFailure {} ->
      GeneratedTraceSemanticModelContract

data CommandOwnerBranch
  = ValidateCommandOwnerBranch !ValidateOwnerBranch
  | QualifyCommandOwnerBranch !QualifyOwnerBranch
  | ReadinessCommandOwnerBranch !ReadinessOwnerBranch
  | AssessCommandOwnerBranch !AssessOwnerBranch
  | QualificationSubjectsCommandOwnerBranch !QualificationSubjectsOwnerBranch
  | TraceCommandOwnerBranch !TraceOwnerBranch
  deriving (Eq, Ord, Show)

commandOwnerBranchToken :: CommandOwnerBranch -> Text
commandOwnerBranchToken branch =
  case branch of
    ValidateCommandOwnerBranch capabilityBranch ->
      validateOwnerBranchToken capabilityBranch
    QualifyCommandOwnerBranch capabilityBranch ->
      qualifyOwnerBranchToken capabilityBranch
    ReadinessCommandOwnerBranch capabilityBranch ->
      readinessOwnerBranchToken capabilityBranch
    AssessCommandOwnerBranch capabilityBranch ->
      assessOwnerBranchToken capabilityBranch
    QualificationSubjectsCommandOwnerBranch capabilityBranch ->
      qualificationSubjectsOwnerBranchToken capabilityBranch
    TraceCommandOwnerBranch capabilityBranch ->
      traceOwnerBranchToken capabilityBranch
