{-# LANGUAGE TemplateHaskell #-}

module Main
  ( main
  ) where

import ApiContractTH (assertAbstractTypes, assertOrdinaryFunctions)
import qualified O2I.Operation.Acquisition as Acquisition
import qualified O2I.Operation.Adapter as Adapter
import qualified O2I.Operation.Adapter.Authoring as AdapterAuthoring
import qualified O2I.Operation.Diagnostic as Diagnostic
import qualified O2I.Operation.Discovery.Adapter as DiscoveryAdapter
import qualified O2I.Operation.Discovery.Adapter.Machine as AdapterMachine
import qualified O2I.Operation.Discovery.Profile as DiscoveryProfile
import qualified O2I.Operation.Discovery.Profile.Machine as ProfileMachine
import qualified O2I.Operation.Discovery.Rule as DiscoveryRule
import qualified O2I.Operation.Discovery.Rule.Explanation.Machine as RuleExplanationMachine
import qualified O2I.Operation.Discovery.Rule.Inventory.Machine as RuleInventoryMachine
import qualified O2I.Operation.Discovery.View as DiscoveryView
import qualified O2I.Operation.Discovery.View.Machine as ViewMachine
import qualified O2I.Operation.Failure as Failure
import qualified O2I.Operation.Machine as Machine
import qualified O2I.Operation.Preparation as Preparation
import qualified O2I.Operation.Profile as Profile
import qualified O2I.Operation.Provenance as Provenance
import qualified O2I.Operation.Request as Request
import qualified O2I.Operation.Rule.Catalog as RuleCatalog
import qualified O2I.Operation.Schema as Schema
import qualified O2I.Operation.View as View

$(assertAbstractTypes
    [ "Acquisition.InputSource"
    , "Acquisition.AcquisitionFailure"
    , "Acquisition.AcquiredSource"
    , "Adapter.AdapterId"
    , "Adapter.AdapterDescriptor"
    , "Adapter.AdapterRuleId"
    , "Adapter.AdapterRuleStage"
    , "Adapter.AdapterRule"
    , "Adapter.NativeLocation"
    , "Adapter.AdapterOccurrence"
    , "Adapter.AdapterDiagnostic"
    , "Adapter.Recognition"
    , "Adapter.DecodeOutcome"
    , "Adapter.Adapter"
    , "Adapter.AdapterCollection"
    , "Adapter.CompiledAdapterContract"
    , "Adapter.SelectedAdapter"
    , "Adapter.AdapterExecution"
    , "Adapter.AdapterSelectionError"
    , "Adapter.AdapterSelection"
    , "AdapterAuthoring.AdapterRuleSpec"
    , "AdapterAuthoring.AdapterRuleBinding"
    , "AdapterAuthoring.AdapterRules"
    , "AdapterAuthoring.NativeAdapterRule"
    , "AdapterAuthoring.RecognitionRule"
    , "AdapterAuthoring.DecodeRule"
    , "AdapterAuthoring.RecognitionDiagnostic"
    , "AdapterAuthoring.DecodeDiagnostic"
    , "AdapterAuthoring.RecognitionResult"
    , "AdapterAuthoring.DecodeResult"
    , "AdapterAuthoring.AdapterBehavior"
    , "DiscoveryAdapter.AdapterDiscovery"
    , "AdapterMachine.AdapterInventoryDocument"
    , "DiscoveryProfile.ProfileDiscoveryDefect"
    , "DiscoveryProfile.ProfileDiscoveryCompilation"
    , "DiscoveryProfile.ProfileDiscovery"
    , "DiscoveryProfile.ProfileDiscoveryRow"
    , "ProfileMachine.ProfileInventoryDocument"
    , "DiscoveryRule.RuleContractBinding"
    , "DiscoveryRule.RuleAuthority"
    , "DiscoveryRule.DiscoveredRule"
    , "DiscoveryRule.RuleDiscoveryDefect"
    , "DiscoveryRule.RuleDiscoveryCompilation"
    , "DiscoveryRule.RuleDiscovery"
    , "DiscoveryRule.RuleExplanation"
    , "DiscoveryRule.RuleExplanationRequestDefect"
    , "RuleInventoryMachine.RuleInventoryDocument"
    , "RuleExplanationMachine.RuleExplanationDocument"
    , "DiscoveryView.ViewDiscoveryAuthority"
    , "DiscoveryView.ViewDiscoveryFailure"
    , "DiscoveryView.ViewDiscoveryResult"
    , "DiscoveryView.ViewDiscovery"
    , "ViewMachine.ViewDiscoveryDocument"
    , "Diagnostic.DiagnosticCode"
    , "Diagnostic.DiagnosticSeverity"
    , "Diagnostic.DiagnosticDisposition"
    , "Diagnostic.DiagnosticProvenance"
    , "Diagnostic.DiagnosticOccurrence"
    , "Diagnostic.Diagnostic"
    , "Failure.CommandFailure"
    , "Failure.PreparationFailure"
    , "Failure.CommonFailure"
    , "Machine.ToolDescriptorField"
    , "Machine.ToolDescriptorDefect"
    , "Machine.ToolDescriptor"
    , "Preparation.PreparationStage"
    , "Preparation.PreparationRequirement"
    , "Preparation.PreparationStep"
    , "Preparation.PreparationPlan"
    , "Profile.ProfileInventoryKey"
    , "Profile.ProfileInventoryDefect"
    , "Profile.ProfileInventoryCompilation"
    , "Profile.ProfileInventory"
    , "Profile.ProfileMarkerEvidence"
    , "Profile.ProfileMarkerEvidenceOutcome"
    , "Profile.ResolvedProfile"
    , "Profile.ProfileResolution"
    , "Profile.ProfileCompatibility"
    , "Provenance.SourceOrdinal"
    , "Provenance.SourceReference"
    , "Provenance.SourceSha256"
    , "Provenance.SourceIdentity"
    , "Provenance.SupplementalProvenance"
    , "Provenance.SupplementalProvenanceDefect"
    , "Request.CapabilityIdentity"
    , "Request.CapabilityInputReferences"
    , "Request.RequestedContract"
    , "RuleCatalog.OperationRuleId"
    , "RuleCatalog.OperationRuleAuthority"
    , "RuleCatalog.OperationRuleStage"
    , "RuleCatalog.OperationRule"
    , "RuleCatalog.OperationRuleCatalog"
    , "Schema.SchemaIdentity"
    , "Schema.SchemaVersion"
    , "Schema.SchemaDigest"
    , "Schema.SchemaVariant"
    , "Schema.SchemaAuthority"
    , "Schema.MachineSchema"
    , "View.ViewSelector"
    , "View.ViewSelectionCandidate"
    , "View.ViewSelectionFailure"
    , "View.SelectedView"
    , "View.ViewSelection"
    ])

$(assertOrdinaryFunctions
    [ 'Acquisition.inputSourceReference
    , 'Acquisition.foldInputSource
    , 'Acquisition.acquisitionFailureSource
    , 'Acquisition.acquisitionFailureIOException
    , 'Acquisition.foldAcquisitionFailure
    , 'Acquisition.acquireSource
    , 'Acquisition.acquiredSourceIdentity
    , 'Acquisition.acquiredSourceBytes
    , 'Acquisition.foldAcquiredSource
    , 'Adapter.adapterIdText
    , 'Adapter.adapterDescriptorId
    , 'Adapter.adapterDescriptorName
    , 'Adapter.adapterDescriptorVersion
    , 'Adapter.adapterDescriptorNotation
    , 'Adapter.foldAdapterDescriptor
    , 'Adapter.adapterRuleIdText
    , 'Adapter.preparationRuleStage
    , 'Adapter.notationRuleStage
    , 'Adapter.adapterRuleStageText
    , 'Adapter.foldAdapterRuleStage
    , 'Adapter.adapterRuleId
    , 'Adapter.adapterRuleStage
    , 'Adapter.adapterRuleExpectation
    , 'Adapter.adapterRuleMeaning
    , 'Adapter.adapterRuleAction
    , 'Adapter.foldAdapterRule
    , 'Adapter.adapterCollectionDescriptors
    , 'Adapter.adapterCollectionContracts
    , 'Adapter.lookupAdapterContract
    , 'Adapter.adapterContractDescriptor
    , 'Adapter.adapterContractRules
    , 'Adapter.lookupArchiMateNotationRule
    , 'Adapter.foldAdapterContract
    , 'Adapter.selectedAdapterDescriptor
    , 'Adapter.selectedAdapterRules
    , 'Adapter.adapterExecutionDescriptor
    , 'Adapter.adapterExecutionRules
    , 'Adapter.adapterExecutionOutcome
    , 'Adapter.foldAdapterExecution
    , 'Adapter.runSelectedAdapter
    , 'Adapter.foldAdapterSelectionError
    , 'Adapter.foldAdapterSelection
    , 'Adapter.selectAdapter
    , 'AdapterAuthoring.mkAdapterId
    , 'AdapterAuthoring.mkAdapterDescriptor
    , 'AdapterAuthoring.mkAdapterRuleSpec
    , 'AdapterAuthoring.adapterRuleSpecId
    , 'AdapterAuthoring.nativeAdapterRule
    , 'AdapterAuthoring.archiMateNotationRule
    , 'AdapterAuthoring.lookupNativeAdapterRule
    , 'AdapterAuthoring.recognitionRule
    , 'AdapterAuthoring.decodeRule
    , 'AdapterAuthoring.nativeByteOffset
    , 'AdapterAuthoring.nativeLineColumn
    , 'AdapterAuthoring.nativePath
    , 'AdapterAuthoring.unlocatedOccurrence
    , 'AdapterAuthoring.locatedOccurrence
    , 'AdapterAuthoring.recognitionDiagnostic
    , 'AdapterAuthoring.decodeDiagnostic
    , 'AdapterAuthoring.noRecognitionMatch
    , 'AdapterAuthoring.recognitionMatch
    , 'AdapterAuthoring.recognitionFailure
    , 'AdapterAuthoring.decodeFailure
    , 'AdapterAuthoring.decodedDraft
    , 'AdapterAuthoring.adapterBehavior
    , 'AdapterAuthoring.compileAdapter
    , 'AdapterAuthoring.compileAdapterCollection
    , 'DiscoveryAdapter.discoverAdapters
    , 'DiscoveryAdapter.discoveredAdapters
    , 'DiscoveryAdapter.lookupDiscoveredAdapter
    , 'DiscoveryAdapter.foldAdapterDiscovery
    , 'AdapterMachine.adapterInventoryDocument
    , 'AdapterMachine.adapterInventorySchema
    , 'AdapterMachine.adapterInventoryDocumentVariant
    , 'AdapterMachine.encodeAdapterInventoryDocument
    , 'DiscoveryProfile.foldProfileDiscoveryDefect
    , 'DiscoveryProfile.foldProfileDiscoveryCompilation
    , 'DiscoveryProfile.discoverProfiles
    , 'DiscoveryProfile.discoveredProfiles
    , 'DiscoveryProfile.lookupDiscoveredProfile
    , 'DiscoveryProfile.foldProfileDiscovery
    , 'DiscoveryProfile.profileDiscoveryIdentity
    , 'DiscoveryProfile.profileDiscoveryToken
    , 'DiscoveryProfile.profileDiscoveryReference
    , 'DiscoveryProfile.profileDiscoveryVersion
    , 'DiscoveryProfile.profileDiscoveryNotation
    , 'DiscoveryProfile.profileDiscoveryAdapterIds
    , 'DiscoveryProfile.profileDiscoveryContractDigest
    , 'DiscoveryProfile.foldProfileDiscoveryRow
    , 'ProfileMachine.profileInventoryDocument
    , 'ProfileMachine.profileInventorySchema
    , 'ProfileMachine.profileInventoryDocumentVariant
    , 'ProfileMachine.encodeProfileInventoryDocument
    , 'DiscoveryRule.ruleContractIdentity
    , 'DiscoveryRule.ruleContractVersion
    , 'DiscoveryRule.ruleContractDigest
    , 'DiscoveryRule.foldRuleContractBinding
    , 'DiscoveryRule.ruleAuthorityText
    , 'DiscoveryRule.ruleAuthorityBinding
    , 'DiscoveryRule.foldRuleAuthority
    , 'DiscoveryRule.discoveredRuleAuthority
    , 'DiscoveryRule.discoveredRuleIdentity
    , 'DiscoveryRule.discoveredRuleStage
    , 'DiscoveryRule.discoveredRuleExpectation
    , 'DiscoveryRule.discoveredRuleMeaning
    , 'DiscoveryRule.discoveredRuleAction
    , 'DiscoveryRule.foldDiscoveredRule
    , 'DiscoveryRule.foldRuleDiscoveryDefect
    , 'DiscoveryRule.foldRuleDiscoveryCompilation
    , 'DiscoveryRule.discoverOperationRules
    , 'DiscoveryRule.discoverCoreRules
    , 'DiscoveryRule.discoverProfileRules
    , 'DiscoveryRule.discoverAdapterRules
    , 'DiscoveryRule.ruleDiscoveryAuthority
    , 'DiscoveryRule.discoveredRules
    , 'DiscoveryRule.explainDiscoveredRule
    , 'DiscoveryRule.foldRuleExplanationRequestDefect
    , 'DiscoveryRule.foldRuleExplanation
    , 'DiscoveryRule.foldRuleDiscovery
    , 'RuleInventoryMachine.ruleInventoryDocument
    , 'RuleInventoryMachine.ruleInventorySchema
    , 'RuleInventoryMachine.ruleInventoryDocumentVariant
    , 'RuleInventoryMachine.encodeRuleInventoryDocument
    , 'RuleExplanationMachine.ruleExplanationDocument
    , 'RuleExplanationMachine.ruleExplanationSchema
    , 'RuleExplanationMachine.ruleExplanationDocumentVariant
    , 'RuleExplanationMachine.encodeRuleExplanationDocument
    , 'DiscoveryView.foldViewDiscoveryAuthority
    , 'DiscoveryView.viewDiscoveryAuthorityText
    , 'DiscoveryView.foldViewDiscoveryFailure
    , 'DiscoveryView.viewDiscoverySource
    , 'DiscoveryView.viewDiscoveryAdapter
    , 'DiscoveryView.viewDiscoveryAuthorities
    , 'DiscoveryView.foldViewDiscoveryResult
    , 'DiscoveryView.foldViewDiscovery
    , 'DiscoveryView.discoverViews
    , 'DiscoveryView.discoverAcquiredViews
    , 'ViewMachine.viewDiscoveryDocument
    , 'ViewMachine.viewDiscoverySchema
    , 'ViewMachine.viewDiscoveryDocumentVariant
    , 'ViewMachine.encodeViewDiscoveryDocument
    , 'Diagnostic.diagnosticCodeText
    , 'Diagnostic.debugSeverity
    , 'Diagnostic.infoSeverity
    , 'Diagnostic.warningSeverity
    , 'Diagnostic.errorSeverity
    , 'Diagnostic.diagnosticSeverityText
    , 'Diagnostic.foldDiagnosticSeverity
    , 'Diagnostic.modelFinding
    , 'Diagnostic.processFailure
    , 'Diagnostic.diagnosticDispositionText
    , 'Diagnostic.foldDiagnosticDisposition
    , 'Diagnostic.diagnosticProvenanceIdentity
    , 'Diagnostic.diagnosticProvenanceAuthority
    , 'Diagnostic.diagnosticProvenanceStage
    , 'Diagnostic.foldDiagnosticProvenance
    , 'Diagnostic.foldDiagnosticOccurrence
    , 'Diagnostic.diagnosticCode
    , 'Diagnostic.diagnosticRuleIdentity
    , 'Diagnostic.diagnosticSeverity
    , 'Diagnostic.diagnosticDisposition
    , 'Diagnostic.diagnosticProvenance
    , 'Diagnostic.diagnosticOccurrences
    , 'Diagnostic.foldDiagnostic
    , 'Failure.inputAcquisitionFailure
    , 'Failure.commandFailureCode
    , 'Failure.foldCommandFailure
    , 'Failure.adapterSelectionFailure
    , 'Failure.adapterDecodeFailure
    , 'Failure.profileMarkerFailure
    , 'Failure.profileResolutionFailure
    , 'Failure.profileCompatibilityFailure
    , 'Failure.viewSelectionFailure
    , 'Failure.preparationFailureCode
    , 'Failure.preparationFailureStage
    , 'Failure.foldPreparationFailure
    , 'Failure.commandFailure
    , 'Failure.preparationFailure
    , 'Failure.commonFailureCode
    , 'Failure.foldCommonFailure
    , 'Machine.toolIdentityField
    , 'Machine.toolVersionField
    , 'Machine.toolDescriptorFieldText
    , 'Machine.foldToolDescriptorField
    , 'Machine.foldToolDescriptorDefect
    , 'Machine.mkToolDescriptor
    , 'Machine.toolDescriptorIdentity
    , 'Machine.toolDescriptorVersion
    , 'Machine.foldToolDescriptor
    , 'Preparation.modelAcquisitionStage
    , 'Preparation.capabilityInputAcquisitionStage
    , 'Preparation.adapterSelectionStage
    , 'Preparation.adapterDecodeStage
    , 'Preparation.canonicalizationStage
    , 'Preparation.profileMarkerStage
    , 'Preparation.profileResolutionStage
    , 'Preparation.profileCompatibilityStage
    , 'Preparation.viewSelectionStage
    , 'Preparation.preparationStageText
    , 'Preparation.foldPreparationStage
    , 'Preparation.requiredPreparation
    , 'Preparation.omittedPreparation
    , 'Preparation.foldPreparationRequirement
    , 'Preparation.preparationStepStage
    , 'Preparation.preparationStepRequirement
    , 'Preparation.foldPreparationStep
    , 'Preparation.preparationPlan
    , 'Preparation.preparationPlanRequest
    , 'Preparation.preparationPlanSteps
    , 'Preparation.foldPreparationPlan
    , 'Profile.foldProfileInventoryKey
    , 'Profile.foldProfileInventoryDefect
    , 'Profile.foldProfileInventoryCompilation
    , 'Profile.compileProfileInventory
    , 'Profile.profileInventoryDescriptors
    , 'Profile.foldProfileMarkerEvidenceOutcome
    , 'Profile.prepareProfileMarkerEvidence
    , 'Profile.resolvedProfileDescriptor
    , 'Profile.resolvedProfileReference
    , 'Profile.foldResolvedProfile
    , 'Profile.foldProfileResolution
    , 'Profile.resolveProfile
    , 'Profile.foldProfileCompatibility
    , 'Profile.checkProfileCompatibility
    , 'Provenance.sourceOrdinal
    , 'Provenance.sourceOrdinalValue
    , 'Provenance.mkSourceReference
    , 'Provenance.sourceReferenceText
    , 'Provenance.sourceSha256Text
    , 'Provenance.sourceIdentityRole
    , 'Provenance.sourceIdentityOrdinal
    , 'Provenance.sourceIdentityReference
    , 'Provenance.sourceIdentitySha256
    , 'Provenance.foldSourceIdentity
    , 'Provenance.mkSupplementalProvenance
    , 'Provenance.supplementalProvenanceSources
    , 'Provenance.foldSupplementalProvenance
    , 'Provenance.foldSupplementalProvenanceDefect
    , 'Request.validationCapability
    , 'Request.traceCapability
    , 'Request.qualificationCapability
    , 'Request.readinessCapability
    , 'Request.assessmentCapability
    , 'Request.capabilityIdentityText
    , 'Request.foldCapabilityIdentity
    , 'Request.capabilityInputReferences
    , 'Request.foldCapabilityInputReferences
    , 'Request.validationRequest
    , 'Request.traceRequest
    , 'Request.qualificationRequest
    , 'Request.readinessRequest
    , 'Request.assessmentRequest
    , 'Request.requestedCapability
    , 'Request.requestedViewSelector
    , 'Request.requestedInputs
    , 'Request.foldRequestedContract
    , 'RuleCatalog.operationRuleIdText
    , 'RuleCatalog.operationRuleAuthorityText
    , 'RuleCatalog.foldOperationRuleAuthority
    , 'RuleCatalog.operationRuleStageText
    , 'RuleCatalog.foldOperationRuleStage
    , 'RuleCatalog.operationRuleIdentity
    , 'RuleCatalog.operationRuleAuthority
    , 'RuleCatalog.operationRuleStage
    , 'RuleCatalog.operationRuleExpectation
    , 'RuleCatalog.operationRuleMeaning
    , 'RuleCatalog.operationRuleAction
    , 'RuleCatalog.operationRuleCatalogContractIdentity
    , 'RuleCatalog.operationRuleCatalogContractVersion
    , 'RuleCatalog.operationRuleCatalogContractDigest
    , 'RuleCatalog.operationRuleCatalogEntries
    , 'RuleCatalog.operationRuleCatalogSize
    , 'RuleCatalog.operationRulesForStage
    , 'RuleCatalog.lookupOperationRule
    , 'Schema.schemaIdentityText
    , 'Schema.schemaVersionValue
    , 'Schema.schemaDigestText
    , 'Schema.schemaVariantText
    , 'Schema.schemaAuthorityIdentity
    , 'Schema.schemaAuthorityVersion
    , 'Schema.schemaAuthorityDigest
    , 'Schema.schemaAuthorityReference
    , 'Schema.foldSchemaAuthority
    , 'Schema.machineSchemaAuthority
    , 'Schema.machineSchemaVariants
    , 'Schema.foldMachineSchema
    , 'View.viewByName
    , 'View.viewByIdentity
    , 'View.foldViewSelector
    , 'View.viewSelectionCandidateOccurrence
    , 'View.viewSelectionCandidateFamily
    , 'View.viewSelectionCandidateIdentity
    , 'View.viewSelectionCandidateLocation
    , 'View.foldViewSelectionCandidate
    , 'View.foldViewSelectionFailure
    , 'View.selectedViewDescriptor
    , 'View.foldSelectedView
    , 'View.foldViewSelection
    , 'View.selectView
    ])

main :: IO ()
main = pure ()
