{-# LANGUAGE TemplateHaskell #-}

module Main
  ( main
  ) where

import ApiContractTH (assertAbstractTypes, assertOrdinaryFunctions)
import qualified O2I.Operation.Acquisition as Acquisition
import qualified O2I.Operation.Adapter as Adapter
import qualified O2I.Operation.Adapter.Authoring as AdapterAuthoring
import qualified O2I.Operation.Diagnostic as Diagnostic
import qualified O2I.Operation.Diagnostic.Machine as DiagnosticMachine
import qualified O2I.Operation.Diagnostic.Owner as DiagnosticOwner
import qualified O2I.Operation.Diagnostic.Owner.Source as DiagnosticSource
import qualified O2I.Operation.Discovery.Adapter as DiscoveryAdapter
import qualified O2I.Operation.Discovery.Adapter.Machine as AdapterMachine
import qualified O2I.Operation.Discovery.Profile as DiscoveryProfile
import qualified O2I.Operation.Discovery.Profile.Machine as ProfileMachine
import qualified O2I.Operation.Discovery.Rule as DiscoveryRule
import qualified O2I.Operation.Discovery.Rule.Explanation.Machine as RuleExplanationMachine
import qualified O2I.Operation.Discovery.Rule.Inventory.Machine as RuleInventoryMachine
import qualified O2I.Operation.Discovery.View as DiscoveryView
import qualified O2I.Operation.Discovery.View.Machine as ViewMachine
import qualified O2I.Operation.Failure as Failure
import qualified O2I.Operation.Machine as Machine
import qualified O2I.Operation.Preparation as Preparation
import qualified O2I.Operation.Profile as Profile
import qualified O2I.Operation.Provenance as Provenance
import qualified O2I.Operation.Qualification.Subjects as QualificationSubjects
import qualified O2I.Operation.Qualification.Subjects.Machine as QualificationSubjectsMachine
import qualified O2I.Operation.Qualification.Subjects.Request as QualificationSubjectsRequest
import qualified O2I.Operation.Qualification.Subjects.Result as QualificationSubjectsResult
import qualified O2I.Operation.Qualify as Qualify
import qualified O2I.Operation.Qualify.Machine as QualifyMachine
import qualified O2I.Operation.Qualify.Request as QualifyRequest
import qualified O2I.Operation.Qualify.Result as QualifyResult
import qualified O2I.Operation.Readiness as Readiness
import qualified O2I.Operation.Readiness.Machine as ReadinessMachine
import qualified O2I.Operation.Readiness.Request as ReadinessRequest
import qualified O2I.Operation.Readiness.Result as ReadinessResult
import qualified O2I.Operation.Request as Request
import qualified O2I.Operation.Rule.Catalog as RuleCatalog
import qualified O2I.Operation.Schema as Schema
import qualified O2I.Operation.Trace as Trace
import qualified O2I.Operation.Trace.Machine as TraceMachine
import qualified O2I.Operation.Trace.Request as TraceRequest
import qualified O2I.Operation.Trace.Result as TraceResult
import qualified O2I.Operation.Validate as Validate
import qualified O2I.Operation.Validate.Machine as ValidateMachine
import qualified O2I.Operation.Validate.Request as ValidateRequest
import qualified O2I.Operation.Validate.Result as ValidateResult
import qualified O2I.Operation.View as View

$(assertAbstractTypes
    [ "Acquisition.InputSource"
    , "Acquisition.AcquisitionFailure"
    , "Acquisition.AcquiredSource"
    , "Acquisition.AcquiredSupplementalSource"
    , "Acquisition.AcquiredReadinessSource"
    , "Adapter.AdapterId"
    , "Adapter.AdapterDescriptor"
    , "Adapter.AdapterRuleId"
    , "Adapter.AdapterRuleStage"
    , "Adapter.AdapterRule"
    , "Adapter.NativeLocation"
    , "Adapter.AdapterOccurrence"
    , "Adapter.AdapterDiagnostic"
    , "Adapter.Recognition"
    , "Adapter.DecodeOutcome"
    , "Adapter.Adapter"
    , "Adapter.AdapterCollection"
    , "Adapter.CompiledAdapterContract"
    , "Adapter.SelectedAdapter"
    , "Adapter.AdapterExecution"
    , "Adapter.AdapterSelectionError"
    , "Adapter.AdapterSelection"
    , "AdapterAuthoring.AdapterRuleSpec"
    , "AdapterAuthoring.AdapterRuleBinding"
    , "AdapterAuthoring.AdapterRules"
    , "AdapterAuthoring.NativeAdapterRule"
    , "AdapterAuthoring.RecognitionRule"
    , "AdapterAuthoring.DecodeRule"
    , "AdapterAuthoring.RecognitionDiagnostic"
    , "AdapterAuthoring.DecodeDiagnostic"
    , "AdapterAuthoring.RecognitionResult"
    , "AdapterAuthoring.DecodeResult"
    , "AdapterAuthoring.AdapterBehavior"
    , "DiscoveryAdapter.AdapterDiscovery"
    , "AdapterMachine.AdapterInventoryDocument"
    , "DiscoveryProfile.ProfileDiscoveryDefect"
    , "DiscoveryProfile.ProfileDiscoveryCompilation"
    , "DiscoveryProfile.ProfileDiscovery"
    , "DiscoveryProfile.ProfileDiscoveryRow"
    , "ProfileMachine.ProfileInventoryDocument"
    , "DiscoveryRule.RuleContractBinding"
    , "DiscoveryRule.RuleAuthority"
    , "DiscoveryRule.DiscoveredRule"
    , "DiscoveryRule.RuleDiscoveryDefect"
    , "DiscoveryRule.RuleDiscoveryCompilation"
    , "DiscoveryRule.RuleDiscovery"
    , "DiscoveryRule.RuleExplanation"
    , "DiscoveryRule.RuleExplanationRequestDefect"
    , "RuleInventoryMachine.RuleInventoryDocument"
    , "RuleExplanationMachine.RuleExplanationDocument"
    , "DiscoveryView.ViewDiscoveryAuthority"
    , "DiscoveryView.ViewDiscoveryFailure"
    , "DiscoveryView.ViewDiscoveryResult"
    , "DiscoveryView.ViewDiscovery"
    , "ViewMachine.ViewDiscoveryDocument"
    , "Diagnostic.DiagnosticSeverity"
    , "Diagnostic.DiagnosticDisposition"
    , "Diagnostic.AdapterNotationDiagnostic"
    , "Diagnostic.PreparedDiagnostic"
    , "Diagnostic.SupplementalDiagnosticGroups"
    , "Diagnostic.PreparedDiagnosticDocument"
    , "DiagnosticSource.PreparedAuthority"
    , "DiagnosticSource.PreparedScope"
    , "DiagnosticOwner.AdapterNotationResolutionFailure"
    , "DiagnosticSource.AdmittedOwnerSupplementalInputs"
    , "DiagnosticSource.SupplementalOwnerBinding"
    , "DiagnosticSource.SupplementalOwnerBindingGroup"
    , "DiagnosticSource.SupplementalOwnerBindingEvidence"
    , "DiagnosticSource.BoundOwnerSupplementalInputs"
    , "Failure.CommandFailure"
    , "Failure.PreparationFailure"
    , "Failure.CommonFailure"
    , "Machine.ToolDescriptorField"
    , "Machine.ToolDescriptorDefect"
    , "Machine.ToolDescriptor"
    , "Preparation.PreparationStage"
    , "Profile.ProfileInventoryKey"
    , "Profile.ProfileInventoryDefect"
    , "Profile.ProfileInventoryCompilation"
    , "Profile.ProfileInventory"
    , "Profile.ProfileMarkerEvidence"
    , "Profile.ProfileMarkerEvidenceOutcome"
    , "Profile.ResolvedProfile"
    , "Profile.ProfileResolution"
    , "Profile.ProfileCompatibility"
    , "Provenance.SourceOrdinal"
    , "Provenance.SourceKey"
    , "Provenance.SourceReference"
    , "Provenance.SourceSha256"
    , "Provenance.SourceIdentity"
    , "Provenance.SupplementalProvenance"
    , "Provenance.SupplementalProvenanceDefect"
    , "QualificationSubjectsRequest.QualificationSubjectsRequest"
    , "QualificationSubjectsResult.QualificationSubjectsPrerequisite"
    , "QualificationSubjectsResult.QualificationSubjectCategory"
    , "QualificationSubjectsResult.QualificationSubjectEligibility"
    , "QualificationSubjectsResult.DiscoveredQualificationSubject"
    , "QualificationSubjectsResult.QualificationSubjectsInventory"
    , "QualificationSubjectsResult.QualificationSubjectsInternalFailure"
    , "QualificationSubjectsResult.QualificationSubjectsFailure"
    , "QualificationSubjectsResult.PreparedQualificationSubjects"
    , "QualificationSubjectsResult.QualificationSubjectsResult"
    , "QualificationSubjectsMachine.QualificationSubjectsDocument"
    , "QualifyRequest.QualifySelectorCategory"
    , "QualifyRequest.QualifyRequestDefect"
    , "QualifyRequest.QualifyRequest"
    , "QualifyResult.QualifyPrerequisite"
    , "QualifyResult.QualifyInternalFailure"
    , "QualifyResult.QualifyFailure"
    , "QualifyResult.PreparedQualify"
    , "QualifyResult.QualifyResult"
    , "QualifyMachine.QualifyResultDocument"
    , "ReadinessRequest.ReadinessRequest"
    , "ReadinessResult.ReadinessPrerequisite"
    , "ReadinessResult.ReadinessInternalFailure"
    , "ReadinessResult.ReadinessFailure"
    , "ReadinessResult.ReadinessUnavailable"
    , "ReadinessResult.PreparedReadiness"
    , "ReadinessResult.ReadinessResult"
    , "ReadinessMachine.ReadinessResultDocument"
    , "Request.CapabilityIdentity"
    , "Request.CapabilityInputReferences"
    , "Request.RequestedContract"
    , "RuleCatalog.OperationRuleId"
    , "RuleCatalog.OperationRuleAuthority"
    , "RuleCatalog.OperationRuleStage"
    , "RuleCatalog.OperationRule"
    , "RuleCatalog.OperationRuleCatalog"
    , "Schema.SchemaIdentity"
    , "Schema.SchemaVersion"
    , "Schema.SchemaDigest"
    , "Schema.SchemaVariant"
    , "Schema.SchemaAuthority"
    , "Schema.MachineSchema"
    , "TraceRequest.TraceRequest"
    , "TraceResult.TracePrerequisite"
    , "TraceResult.TraceInternalFailure"
    , "TraceResult.TraceFailure"
    , "TraceResult.PreparedTrace"
    , "TraceResult.TraceResult"
    , "TraceMachine.TraceResultDocument"
    , "ValidateRequest.ValidationLevel"
    , "ValidateRequest.ValidateRequest"
    , "ValidateResult.ValidationDisposition"
    , "ValidateResult.ValidateInternalFailure"
    , "ValidateResult.ValidateFailure"
    , "ValidateResult.ValidateUnavailabilityWitness"
    , "ValidateResult.PreparedValidation"
    , "ValidateResult.ValidateResult"
    , "ValidateMachine.ValidateResultDocument"
    , "View.ViewSelector"
    , "View.ViewSelectionCandidate"
    , "View.ViewSelectionFailure"
    , "View.SelectedView"
    , "View.ViewSelection"
    ])

$(assertOrdinaryFunctions
    [ 'Acquisition.inputSourceReference
    , 'Acquisition.foldInputSource
    , 'Acquisition.acquisitionFailureSource
    , 'Acquisition.acquisitionFailureIOException
    , 'Acquisition.foldAcquisitionFailure
    , 'Acquisition.acquireSource
    , 'Acquisition.acquiredSourceIdentity
    , 'Acquisition.acquiredSourceBytes
    , 'Acquisition.foldAcquiredSource
    , 'Acquisition.acquiredSupplementalSource
    , 'Acquisition.foldAcquiredSupplementalSource
    , 'Acquisition.acquiredReadinessSource
    , 'Acquisition.foldAcquiredReadinessSource
    , 'Adapter.adapterIdText
    , 'Adapter.adapterDescriptorId
    , 'Adapter.adapterDescriptorName
    , 'Adapter.adapterDescriptorVersion
    , 'Adapter.adapterDescriptorNotation
    , 'Adapter.foldAdapterDescriptor
    , 'Adapter.adapterRuleIdText
    , 'Adapter.preparationRuleStage
    , 'Adapter.notationRuleStage
    , 'Adapter.adapterRuleStageText
    , 'Adapter.foldAdapterRuleStage
    , 'Adapter.adapterRuleId
    , 'Adapter.adapterRuleStage
    , 'Adapter.adapterRuleExpectation
    , 'Adapter.adapterRuleMeaning
    , 'Adapter.adapterRuleAction
    , 'Adapter.foldAdapterRule
    , 'Adapter.adapterCollectionDescriptors
    , 'Adapter.adapterCollectionContracts
    , 'Adapter.lookupAdapterContract
    , 'Adapter.adapterContractDescriptor
    , 'Adapter.adapterContractRules
    , 'Adapter.lookupArchiMateNotationRule
    , 'Adapter.foldAdapterContract
    , 'Adapter.selectedAdapterDescriptor
    , 'Adapter.selectedAdapterRules
    , 'Adapter.adapterExecutionDescriptor
    , 'Adapter.adapterExecutionRules
    , 'Adapter.adapterExecutionOutcome
    , 'Adapter.foldAdapterExecution
    , 'Adapter.runSelectedAdapter
    , 'Adapter.foldAdapterSelectionError
    , 'Adapter.foldAdapterSelection
    , 'Adapter.selectAdapter
    , 'AdapterAuthoring.mkAdapterId
    , 'AdapterAuthoring.mkAdapterDescriptor
    , 'AdapterAuthoring.mkAdapterRuleSpec
    , 'AdapterAuthoring.adapterRuleSpecId
    , 'AdapterAuthoring.nativeAdapterRule
    , 'AdapterAuthoring.archiMateNotationRule
    , 'AdapterAuthoring.lookupNativeAdapterRule
    , 'AdapterAuthoring.recognitionRule
    , 'AdapterAuthoring.decodeRule
    , 'AdapterAuthoring.nativeByteOffset
    , 'AdapterAuthoring.nativeLineColumn
    , 'AdapterAuthoring.nativePath
    , 'AdapterAuthoring.unlocatedOccurrence
    , 'AdapterAuthoring.locatedOccurrence
    , 'AdapterAuthoring.recognitionDiagnostic
    , 'AdapterAuthoring.decodeDiagnostic
    , 'AdapterAuthoring.noRecognitionMatch
    , 'AdapterAuthoring.recognitionMatch
    , 'AdapterAuthoring.recognitionFailure
    , 'AdapterAuthoring.decodeFailure
    , 'AdapterAuthoring.decodedDraft
    , 'AdapterAuthoring.adapterBehavior
    , 'AdapterAuthoring.compileAdapter
    , 'AdapterAuthoring.compileAdapterCollection
    , 'DiscoveryAdapter.discoverAdapters
    , 'DiscoveryAdapter.discoveredAdapters
    , 'DiscoveryAdapter.lookupDiscoveredAdapter
    , 'DiscoveryAdapter.foldAdapterDiscovery
    , 'AdapterMachine.adapterInventoryDocument
    , 'AdapterMachine.adapterInventorySchema
    , 'AdapterMachine.adapterInventoryDocumentVariant
    , 'AdapterMachine.encodeAdapterInventoryDocument
    , 'DiscoveryProfile.foldProfileDiscoveryDefect
    , 'DiscoveryProfile.foldProfileDiscoveryCompilation
    , 'DiscoveryProfile.discoverProfiles
    , 'DiscoveryProfile.discoveredProfiles
    , 'DiscoveryProfile.lookupDiscoveredProfile
    , 'DiscoveryProfile.foldProfileDiscovery
    , 'DiscoveryProfile.profileDiscoveryIdentity
    , 'DiscoveryProfile.profileDiscoveryToken
    , 'DiscoveryProfile.profileDiscoveryReference
    , 'DiscoveryProfile.profileDiscoveryVersion
    , 'DiscoveryProfile.profileDiscoveryNotation
    , 'DiscoveryProfile.profileDiscoveryAdapterIds
    , 'DiscoveryProfile.profileDiscoveryContractDigest
    , 'DiscoveryProfile.foldProfileDiscoveryRow
    , 'ProfileMachine.profileInventoryDocument
    , 'ProfileMachine.profileInventorySchema
    , 'ProfileMachine.profileInventoryDocumentVariant
    , 'ProfileMachine.encodeProfileInventoryDocument
    , 'DiscoveryRule.ruleContractIdentity
    , 'DiscoveryRule.ruleContractVersion
    , 'DiscoveryRule.ruleContractDigest
    , 'DiscoveryRule.foldRuleContractBinding
    , 'DiscoveryRule.ruleAuthorityText
    , 'DiscoveryRule.ruleAuthorityBinding
    , 'DiscoveryRule.foldRuleAuthority
    , 'DiscoveryRule.discoveredRuleAuthority
    , 'DiscoveryRule.discoveredRuleIdentity
    , 'DiscoveryRule.discoveredRuleStage
    , 'DiscoveryRule.discoveredRuleExpectation
    , 'DiscoveryRule.discoveredRuleMeaning
    , 'DiscoveryRule.discoveredRuleAction
    , 'DiscoveryRule.foldDiscoveredRule
    , 'DiscoveryRule.foldRuleDiscoveryDefect
    , 'DiscoveryRule.foldRuleDiscoveryCompilation
    , 'DiscoveryRule.discoverOperationRules
    , 'DiscoveryRule.discoverCoreRules
    , 'DiscoveryRule.discoverProfileRules
    , 'DiscoveryRule.discoverAdapterRules
    , 'DiscoveryRule.ruleDiscoveryAuthority
    , 'DiscoveryRule.discoveredRules
    , 'DiscoveryRule.explainDiscoveredRule
    , 'DiscoveryRule.foldRuleExplanationRequestDefect
    , 'DiscoveryRule.foldRuleExplanation
    , 'DiscoveryRule.foldRuleDiscovery
    , 'RuleInventoryMachine.ruleInventoryDocument
    , 'RuleInventoryMachine.ruleInventorySchema
    , 'RuleInventoryMachine.ruleInventoryDocumentVariant
    , 'RuleInventoryMachine.encodeRuleInventoryDocument
    , 'RuleExplanationMachine.ruleExplanationDocument
    , 'RuleExplanationMachine.ruleExplanationSchema
    , 'RuleExplanationMachine.ruleExplanationDocumentVariant
    , 'RuleExplanationMachine.encodeRuleExplanationDocument
    , 'DiscoveryView.foldViewDiscoveryAuthority
    , 'DiscoveryView.viewDiscoveryAuthorityText
    , 'DiscoveryView.foldViewDiscoveryFailure
    , 'DiscoveryView.viewDiscoverySource
    , 'DiscoveryView.viewDiscoveryAdapter
    , 'DiscoveryView.viewDiscoveryAuthorities
    , 'DiscoveryView.foldViewDiscoveryResult
    , 'DiscoveryView.foldViewDiscovery
    , 'DiscoveryView.discoverViews
    , 'DiscoveryView.discoverAcquiredViews
    , 'ViewMachine.viewDiscoveryDocument
    , 'ViewMachine.viewDiscoverySchema
    , 'ViewMachine.viewDiscoveryDocumentVariant
    , 'ViewMachine.encodeViewDiscoveryDocument
    , 'Diagnostic.infoSeverity
    , 'Diagnostic.errorSeverity
    , 'Diagnostic.diagnosticSeverityText
    , 'Diagnostic.modelFinding
    , 'Diagnostic.processFailure
    , 'Diagnostic.diagnosticDispositionText
    , 'Diagnostic.foldAdapterNotationDiagnostic
    , 'Diagnostic.preparedDiagnosticSeverity
    , 'Diagnostic.preparedDiagnosticDisposition
    , 'Diagnostic.preparedDiagnosticProducer
    , 'Diagnostic.preparedDiagnosticOwner
    , 'Diagnostic.preparedDiagnosticStage
    , 'Diagnostic.preparedDiagnosticRuleIdentity
    , 'Diagnostic.foldPreparedDiagnostic
    , 'Diagnostic.noSupplementalDiagnosticGroups
    , 'Diagnostic.preparedDiagnosticDocument
    , 'Diagnostic.foldPreparedDiagnosticDocument
    , 'DiagnosticMachine.diagnosticSchemaAuthority
    , 'DiagnosticMachine.encodePreparedDiagnosticDocument
    , 'DiagnosticOwner.profileActivationDiagnostics
    , 'DiagnosticOwner.foldAdapterNotationResolutionFailure
    , 'DiagnosticOwner.foldNotationAssessmentDiagnostics
    , 'DiagnosticOwner.foldProfileAssessmentDiagnostics
    , 'DiagnosticOwner.withModelStructureAssessment
    , 'DiagnosticOwner.structureEvidenceDiagnostic
    , 'DiagnosticOwner.bindingDiagnosticGroups
    , 'DiagnosticOwner.semanticsEvidenceDiagnostic
    , 'DiagnosticSource.withAdmittedOwnerSupplementalInputs
    , 'DiagnosticSource.withBoundAdmittedOwnerSupplementalInputs
    , 'DiagnosticSource.foldSupplementalOwnerBinding
    , 'DiagnosticSource.foldSupplementalOwnerBindingGroup
    , 'DiagnosticSource.assessOwnerSemantics
    , 'Failure.inputAcquisitionFailure
    , 'Failure.commandFailureCode
    , 'Failure.foldCommandFailure
    , 'Failure.adapterSelectionFailure
    , 'Failure.adapterDecodeFailure
    , 'Failure.profileMarkerFailure
    , 'Failure.profileResolutionFailure
    , 'Failure.profileCompatibilityFailure
    , 'Failure.viewSelectionFailure
    , 'Failure.preparationFailureCode
    , 'Failure.preparationFailureStage
    , 'Failure.foldPreparationFailure
    , 'Failure.commandFailure
    , 'Failure.preparationFailure
    , 'Failure.commonFailureCode
    , 'Failure.foldCommonFailure
    , 'Machine.toolIdentityField
    , 'Machine.toolVersionField
    , 'Machine.toolDescriptorFieldText
    , 'Machine.foldToolDescriptorField
    , 'Machine.foldToolDescriptorDefect
    , 'Machine.mkToolDescriptor
    , 'Machine.toolDescriptorIdentity
    , 'Machine.toolDescriptorVersion
    , 'Machine.foldToolDescriptor
    , 'Preparation.adapterSelectionStage
    , 'Preparation.adapterDecodeStage
    , 'Preparation.canonicalizationStage
    , 'Preparation.profileMarkerStage
    , 'Preparation.profileResolutionStage
    , 'Preparation.profileCompatibilityStage
    , 'Preparation.viewSelectionStage
    , 'Preparation.preparationStageText
    , 'Preparation.foldPreparationStage
    , 'Profile.foldProfileInventoryKey
    , 'Profile.foldProfileInventoryDefect
    , 'Profile.foldProfileInventoryCompilation
    , 'Profile.compileProfileInventory
    , 'Profile.profileInventoryDescriptors
    , 'Profile.foldProfileMarkerEvidenceOutcome
    , 'Profile.prepareProfileMarkerEvidence
    , 'Profile.resolvedProfileDescriptor
    , 'Profile.resolvedProfileReference
    , 'Profile.foldResolvedProfile
    , 'Profile.foldProfileResolution
    , 'Profile.resolveProfile
    , 'Profile.foldProfileCompatibility
    , 'Profile.checkProfileCompatibility
    , 'Provenance.sourceOrdinal
    , 'Provenance.sourceOrdinalValue
    , 'Provenance.sourceKey
    , 'Provenance.sourceKeyRole
    , 'Provenance.sourceKeyOrdinal
    , 'Provenance.foldSourceKey
    , 'Provenance.mkSourceReference
    , 'Provenance.sourceReferenceText
    , 'Provenance.sourceSha256Text
    , 'Provenance.sourceIdentityKey
    , 'Provenance.sourceIdentityRole
    , 'Provenance.sourceIdentityOrdinal
    , 'Provenance.sourceIdentityReference
    , 'Provenance.sourceIdentitySha256
    , 'Provenance.foldSourceIdentity
    , 'Provenance.mkSupplementalProvenance
    , 'Provenance.supplementalProvenanceSources
    , 'Provenance.foldSupplementalProvenance
    , 'Provenance.foldSupplementalProvenanceDefect
    , 'QualificationSubjects.runQualificationSubjects
    , 'QualificationSubjectsRequest.qualificationSubjectsRequest
    , 'QualificationSubjectsRequest.qualificationSubjectsModelInput
    , 'QualificationSubjectsRequest.qualificationSubjectsViewSelector
    , 'QualificationSubjectsRequest.qualificationSubjectsAdapterId
    , 'QualificationSubjectsRequest.qualificationSubjectsSupplementalInputs
    , 'QualificationSubjectsRequest.foldQualificationSubjectsRequest
    , 'QualificationSubjectsResult.notationQualificationSubjectsPrerequisite
    , 'QualificationSubjectsResult.profileQualificationSubjectsPrerequisite
    , 'QualificationSubjectsResult.structureQualificationSubjectsPrerequisite
    , 'QualificationSubjectsResult.qualificationSubjectsPrerequisiteText
    , 'QualificationSubjectsResult.foldQualificationSubjectsPrerequisite
    , 'QualificationSubjectsResult.needQualificationSubjectCategory
    , 'QualificationSubjectsResult.strategyQualificationSubjectCategory
    , 'QualificationSubjectsResult.qualificationSubjectCategoryText
    , 'QualificationSubjectsResult.foldQualificationSubjectCategory
    , 'QualificationSubjectsResult.eligibleQualificationSubject
    , 'QualificationSubjectsResult.ineligibleQualificationSubject
    , 'QualificationSubjectsResult.unavailableQualificationSubjectEligibility
    , 'QualificationSubjectsResult.qualificationSubjectEligibilityText
    , 'QualificationSubjectsResult.foldQualificationSubjectEligibility
    , 'QualificationSubjectsResult.discoveredQualificationSubjectCategory
    , 'QualificationSubjectsResult.discoveredQualificationSubjectIdentity
    , 'QualificationSubjectsResult.discoveredQualificationSubjectOccurrence
    , 'QualificationSubjectsResult.discoveredQualificationSubjectQualifiedEndpoint
    , 'QualificationSubjectsResult.discoveredQualificationSubjectDisplayName
    , 'QualificationSubjectsResult.discoveredQualificationSubjectEligibility
    , 'QualificationSubjectsResult.foldDiscoveredQualificationSubject
    , 'QualificationSubjectsResult.qualificationInventoryNeedSubjects
    , 'QualificationSubjectsResult.qualificationInventoryStrategySubjects
    , 'QualificationSubjectsResult.foldQualificationSubjectsInventory
    , 'QualificationSubjectsResult.foldQualificationSubjectsInternalFailure
    , 'QualificationSubjectsResult.foldQualificationSubjectsFailure
    , 'QualificationSubjectsResult.preparedQualificationSubjectsRequest
    , 'QualificationSubjectsResult.preparedQualificationSubjectsSupplementalSources
    , 'QualificationSubjectsResult.preparedQualificationSubjectsDiagnostics
    , 'QualificationSubjectsResult.foldPreparedQualificationSubjects
    , 'QualificationSubjectsResult.foldQualificationSubjectsResult
    , 'QualificationSubjectsMachine.qualificationSubjectsDocument
    , 'QualificationSubjectsMachine.qualificationSubjectsSchema
    , 'QualificationSubjectsMachine.qualificationSubjectsDocumentVariant
    , 'QualificationSubjectsMachine.encodeQualificationSubjectsDocument
    , 'Qualify.runQualify
    , 'QualifyRequest.needQualifySelectorCategory
    , 'QualifyRequest.strategyQualifySelectorCategory
    , 'QualifyRequest.qualifySelectorCategoryText
    , 'QualifyRequest.foldQualifySelectorCategory
    , 'QualifyRequest.qualifyRequestDefectCategory
    , 'QualifyRequest.qualifyRequestDefectIdentity
    , 'QualifyRequest.foldQualifyRequestDefect
    , 'QualifyRequest.qualifyRequest
    , 'QualifyRequest.qualifyModelInput
    , 'QualifyRequest.qualifyViewSelector
    , 'QualifyRequest.qualifyAdapterId
    , 'QualifyRequest.qualifyStrategySelectors
    , 'QualifyRequest.qualifyNeedSelectors
    , 'QualifyRequest.qualifySupplementalInputs
    , 'QualifyRequest.foldQualifyRequest
    , 'QualifyResult.notationQualifyPrerequisite
    , 'QualifyResult.profileQualifyPrerequisite
    , 'QualifyResult.structureQualifyPrerequisite
    , 'QualifyResult.qualifyPrerequisiteText
    , 'QualifyResult.foldQualifyPrerequisite
    , 'QualifyResult.foldQualifyInternalFailure
    , 'QualifyResult.foldQualifyFailure
    , 'QualifyResult.preparedQualifyRequest
    , 'QualifyResult.preparedQualifyDiagnostics
    , 'QualifyResult.foldPreparedQualify
    , 'QualifyResult.foldQualifyResult
    , 'QualifyMachine.qualifyResultDocument
    , 'QualifyMachine.qualifyResultSchema
    , 'QualifyMachine.qualifyResultDocumentVariant
    , 'QualifyMachine.encodeQualifyResultDocument
    , 'Request.validationCapability
    , 'Request.traceCapability
    , 'Request.qualificationCapability
    , 'Request.readinessCapability
    , 'Request.assessmentCapability
    , 'Request.capabilityIdentityText
    , 'Request.foldCapabilityIdentity
    , 'Request.capabilityInputReferences
    , 'Request.foldCapabilityInputReferences
    , 'Request.validationRequest
    , 'Request.traceRequest
    , 'Request.qualificationRequest
    , 'Request.readinessRequest
    , 'Request.assessmentRequest
    , 'Request.requestedCapability
    , 'Request.requestedViewSelector
    , 'Request.requestedInputs
    , 'Request.foldRequestedContract
    , 'RuleCatalog.operationRuleIdText
    , 'RuleCatalog.operationRuleAuthorityText
    , 'RuleCatalog.foldOperationRuleAuthority
    , 'RuleCatalog.operationRuleStageText
    , 'RuleCatalog.foldOperationRuleStage
    , 'RuleCatalog.operationRuleIdentity
    , 'RuleCatalog.operationRuleAuthority
    , 'RuleCatalog.operationRuleStage
    , 'RuleCatalog.operationRuleExpectation
    , 'RuleCatalog.operationRuleMeaning
    , 'RuleCatalog.operationRuleAction
    , 'RuleCatalog.operationRuleCatalogContractIdentity
    , 'RuleCatalog.operationRuleCatalogContractVersion
    , 'RuleCatalog.operationRuleCatalogContractDigest
    , 'RuleCatalog.operationRuleCatalogEntries
    , 'RuleCatalog.operationRuleCatalogSize
    , 'RuleCatalog.operationRulesForStage
    , 'RuleCatalog.lookupOperationRule
    , 'Schema.schemaIdentityText
    , 'Schema.schemaVersionValue
    , 'Schema.schemaDigestText
    , 'Schema.schemaVariantText
    , 'Schema.schemaAuthorityIdentity
    , 'Schema.schemaAuthorityVersion
    , 'Schema.schemaAuthorityDigest
    , 'Schema.schemaAuthorityReference
    , 'Schema.foldSchemaAuthority
    , 'Schema.machineSchemaAuthority
    , 'Schema.machineSchemaVariants
    , 'Schema.foldMachineSchema
    , 'Trace.runTrace
    , 'TraceRequest.traceRequest
    , 'TraceRequest.traceModelInput
    , 'TraceRequest.traceViewSelector
    , 'TraceRequest.traceAdapterId
    , 'TraceRequest.foldTraceRequest
    , 'TraceResult.notationTracePrerequisite
    , 'TraceResult.profileTracePrerequisite
    , 'TraceResult.structureTracePrerequisite
    , 'TraceResult.semanticsTracePrerequisite
    , 'TraceResult.tracePrerequisiteText
    , 'TraceResult.foldTracePrerequisite
    , 'TraceResult.foldTraceInternalFailure
    , 'TraceResult.foldTraceFailure
    , 'TraceResult.preparedTraceRequest
    , 'TraceResult.preparedTraceDiagnostics
    , 'TraceResult.foldPreparedTrace
    , 'TraceResult.foldTraceResult
    , 'TraceMachine.traceResultDocument
    , 'TraceMachine.traceResultSchema
    , 'TraceMachine.traceResultDocumentVariant
    , 'TraceMachine.encodeTraceResultDocument
    , 'Readiness.runReadiness
    , 'ReadinessRequest.readinessRequest
    , 'ReadinessRequest.readinessModelInput
    , 'ReadinessRequest.readinessViewSelector
    , 'ReadinessRequest.readinessAdapterId
    , 'ReadinessRequest.readinessEvidenceInput
    , 'ReadinessRequest.readinessSupplementalInputs
    , 'ReadinessRequest.foldReadinessRequest
    , 'ReadinessResult.notationReadinessPrerequisite
    , 'ReadinessResult.profileReadinessPrerequisite
    , 'ReadinessResult.structureReadinessPrerequisite
    , 'ReadinessResult.semanticsReadinessPrerequisite
    , 'ReadinessResult.readinessPrerequisiteText
    , 'ReadinessResult.foldReadinessPrerequisite
    , 'ReadinessResult.foldReadinessInternalFailure
    , 'ReadinessResult.foldReadinessFailure
    , 'ReadinessResult.foldReadinessUnavailable
    , 'ReadinessResult.preparedReadinessRequest
    , 'ReadinessResult.preparedReadinessDiagnostics
    , 'ReadinessResult.foldPreparedReadiness
    , 'ReadinessResult.foldReadinessResult
    , 'ReadinessMachine.readinessResultDocument
    , 'ReadinessMachine.readinessResultSchema
    , 'ReadinessMachine.readinessResultDocumentVariant
    , 'ReadinessMachine.encodeReadinessResultDocument
    , 'Validate.runValidate
    , 'ValidateRequest.notationValidationLevel
    , 'ValidateRequest.profileValidationLevel
    , 'ValidateRequest.structureValidationLevel
    , 'ValidateRequest.semanticsValidationLevel
    , 'ValidateRequest.validationLevelText
    , 'ValidateRequest.foldValidationLevel
    , 'ValidateRequest.notationValidateRequest
    , 'ValidateRequest.profileValidateRequest
    , 'ValidateRequest.structureValidateRequest
    , 'ValidateRequest.semanticsValidateRequest
    , 'ValidateRequest.validateRequestLevel
    , 'ValidateRequest.validateModelInput
    , 'ValidateRequest.validateViewSelector
    , 'ValidateRequest.validateAdapterId
    , 'ValidateRequest.validateSupplementalInputs
    , 'ValidateRequest.foldValidateRequest
    , 'ValidateResult.validationAccepted
    , 'ValidateResult.validationRejected
    , 'ValidateResult.validationUnavailable
    , 'ValidateResult.validationDispositionText
    , 'ValidateResult.foldValidationDisposition
    , 'ValidateResult.foldValidateInternalFailure
    , 'ValidateResult.foldValidateFailure
    , 'ValidateResult.foldValidateUnavailabilityWitness
    , 'ValidateResult.preparedValidationLevel
    , 'ValidateResult.preparedValidationDiagnostics
    , 'ValidateResult.foldPreparedValidation
    , 'ValidateResult.validateResultDisposition
    , 'ValidateResult.foldValidateResult
    , 'ValidateMachine.validateResultDocument
    , 'ValidateMachine.validateResultSchema
    , 'ValidateMachine.validateResultDocumentVariant
    , 'ValidateMachine.encodeValidateResultDocument
    , 'View.viewByName
    , 'View.viewByIdentity
    , 'View.foldViewSelector
    , 'View.viewSelectionCandidateOccurrence
    , 'View.viewSelectionCandidateFamily
    , 'View.viewSelectionCandidateIdentity
    , 'View.viewSelectionCandidateLocation
    , 'View.foldViewSelectionCandidate
    , 'View.foldViewSelectionFailure
    , 'View.selectedViewDescriptor
    , 'View.foldSelectedView
    , 'View.foldViewSelection
    , 'View.selectView
    ])

main :: IO ()
main = pure ()
