{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Core.Contract.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import Data.Text (Text)

contractIdentity :: Text
contractIdentity = "o2i.core-semantics"

contractVersion :: Text
contractVersion = "0.3.0"

contractSha256 :: Text
contractSha256 =
  "0654111b900ff1c19b241a4fdfec10694d61a88471981e9df6bcb58b27785f01"

contractShapeSha256 :: Text
contractShapeSha256 =
  "fbb21f3db5bda60724b8a1448fd7bd302050f4d1e21be2873cd040f84fd3f2e4"

data GeneratedCarrierCategory
  = GeneratedCarrierContext
  | GeneratedCarrierPrimitive
  | GeneratedCarrierSituationAnchor
  | GeneratedCarrierStructuring
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedCarrierCategoryText :: GeneratedCarrierCategory -> Text
generatedCarrierCategoryText value =
  case value of
    GeneratedCarrierContext -> "Context"
    GeneratedCarrierPrimitive -> "Primitive"
    GeneratedCarrierSituationAnchor -> "SituationAnchor"
    GeneratedCarrierStructuring -> "Structuring"

lookupGeneratedCarrierCategory :: Text -> Maybe GeneratedCarrierCategory
lookupGeneratedCarrierCategory value =
  case value of
    "Context" -> Just GeneratedCarrierContext
    "Primitive" -> Just GeneratedCarrierPrimitive
    "SituationAnchor" -> Just GeneratedCarrierSituationAnchor
    "Structuring" -> Just GeneratedCarrierStructuring
    _ -> Nothing

generatedCarrierCategories :: NonEmpty GeneratedCarrierCategory
generatedCarrierCategories =
  GeneratedCarrierContext
    :| [ GeneratedCarrierPrimitive
       , GeneratedCarrierSituationAnchor
       , GeneratedCarrierStructuring
       ]

data GeneratedO2IType
  = GeneratedTypeAction
  | GeneratedTypeBusinessCapability
  | GeneratedTypeBusinessObject
  | GeneratedTypeBusinessProcess
  | GeneratedTypeDriver
  | GeneratedTypeEthos
  | GeneratedTypeIntervention
  | GeneratedTypeKPI
  | GeneratedTypeKeyResult
  | GeneratedTypeMeasure
  | GeneratedTypeMission
  | GeneratedTypeNeed
  | GeneratedTypeObjective
  | GeneratedTypePerformanceDimension
  | GeneratedTypePrinciple
  | GeneratedTypeSituation
  | GeneratedTypeStrategy
  | GeneratedTypeValueStream
  | GeneratedTypeVision
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedO2ITypeText :: GeneratedO2IType -> Text
generatedO2ITypeText value =
  case value of
    GeneratedTypeAction -> "Action"
    GeneratedTypeBusinessCapability -> "BusinessCapability"
    GeneratedTypeBusinessObject -> "BusinessObject"
    GeneratedTypeBusinessProcess -> "BusinessProcess"
    GeneratedTypeDriver -> "Driver"
    GeneratedTypeEthos -> "Ethos"
    GeneratedTypeIntervention -> "Intervention"
    GeneratedTypeKPI -> "KPI"
    GeneratedTypeKeyResult -> "KeyResult"
    GeneratedTypeMeasure -> "Measure"
    GeneratedTypeMission -> "Mission"
    GeneratedTypeNeed -> "Need"
    GeneratedTypeObjective -> "Objective"
    GeneratedTypePerformanceDimension -> "PerformanceDimension"
    GeneratedTypePrinciple -> "Principle"
    GeneratedTypeSituation -> "Situation"
    GeneratedTypeStrategy -> "Strategy"
    GeneratedTypeValueStream -> "ValueStream"
    GeneratedTypeVision -> "Vision"

lookupGeneratedO2IType :: Text -> Maybe GeneratedO2IType
lookupGeneratedO2IType value =
  case value of
    "Action" -> Just GeneratedTypeAction
    "BusinessCapability" -> Just GeneratedTypeBusinessCapability
    "BusinessObject" -> Just GeneratedTypeBusinessObject
    "BusinessProcess" -> Just GeneratedTypeBusinessProcess
    "Driver" -> Just GeneratedTypeDriver
    "Ethos" -> Just GeneratedTypeEthos
    "Intervention" -> Just GeneratedTypeIntervention
    "KPI" -> Just GeneratedTypeKPI
    "KeyResult" -> Just GeneratedTypeKeyResult
    "Measure" -> Just GeneratedTypeMeasure
    "Mission" -> Just GeneratedTypeMission
    "Need" -> Just GeneratedTypeNeed
    "Objective" -> Just GeneratedTypeObjective
    "PerformanceDimension" -> Just GeneratedTypePerformanceDimension
    "Principle" -> Just GeneratedTypePrinciple
    "Situation" -> Just GeneratedTypeSituation
    "Strategy" -> Just GeneratedTypeStrategy
    "ValueStream" -> Just GeneratedTypeValueStream
    "Vision" -> Just GeneratedTypeVision
    _ -> Nothing

generatedO2ITypes :: NonEmpty GeneratedO2IType
generatedO2ITypes =
  GeneratedTypeAction
    :| [ GeneratedTypeBusinessCapability
       , GeneratedTypeBusinessObject
       , GeneratedTypeBusinessProcess
       , GeneratedTypeDriver
       , GeneratedTypeEthos
       , GeneratedTypeIntervention
       , GeneratedTypeKPI
       , GeneratedTypeKeyResult
       , GeneratedTypeMeasure
       , GeneratedTypeMission
       , GeneratedTypeNeed
       , GeneratedTypeObjective
       , GeneratedTypePerformanceDimension
       , GeneratedTypePrinciple
       , GeneratedTypeSituation
       , GeneratedTypeStrategy
       , GeneratedTypeValueStream
       , GeneratedTypeVision
       ]

data GeneratedQualifiedEndpoint
  = GeneratedEndpointContextEthos
  | GeneratedEndpointContextIntervention
  | GeneratedEndpointContextMeasure
  | GeneratedEndpointContextMission
  | GeneratedEndpointContextNeed
  | GeneratedEndpointContextSituation
  | GeneratedEndpointContextStrategy
  | GeneratedEndpointContextVision
  | GeneratedEndpointPrimitiveEthosPrinciple
  | GeneratedEndpointPrimitiveInterventionAction
  | GeneratedEndpointPrimitiveInterventionKeyResult
  | GeneratedEndpointPrimitiveMeasureKpi
  | GeneratedEndpointPrimitiveMissionDriver
  | GeneratedEndpointPrimitiveNeedDriver
  | GeneratedEndpointPrimitiveNeedObjective
  | GeneratedEndpointPrimitiveStrategyAction
  | GeneratedEndpointPrimitiveStrategyDriver
  | GeneratedEndpointPrimitiveStrategyKeyResult
  | GeneratedEndpointPrimitiveStrategyObjective
  | GeneratedEndpointPrimitiveStrategyPrinciple
  | GeneratedEndpointPrimitiveVisionObjective
  | GeneratedEndpointSituationAnchorBusinessCapability
  | GeneratedEndpointSituationAnchorBusinessObject
  | GeneratedEndpointSituationAnchorBusinessProcess
  | GeneratedEndpointSituationAnchorValueStream
  | GeneratedEndpointStructuringMeasurePerformanceDimension
  | GeneratedEndpointStructuringStrategyPerformanceDimension
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedQualifiedEndpointText :: GeneratedQualifiedEndpoint -> Text
generatedQualifiedEndpointText value =
  case value of
    GeneratedEndpointContextEthos -> "context.ethos"
    GeneratedEndpointContextIntervention -> "context.intervention"
    GeneratedEndpointContextMeasure -> "context.measure"
    GeneratedEndpointContextMission -> "context.mission"
    GeneratedEndpointContextNeed -> "context.need"
    GeneratedEndpointContextSituation -> "context.situation"
    GeneratedEndpointContextStrategy -> "context.strategy"
    GeneratedEndpointContextVision -> "context.vision"
    GeneratedEndpointPrimitiveEthosPrinciple -> "primitive.ethos.principle"
    GeneratedEndpointPrimitiveInterventionAction ->
      "primitive.intervention.action"
    GeneratedEndpointPrimitiveInterventionKeyResult ->
      "primitive.intervention.key-result"
    GeneratedEndpointPrimitiveMeasureKpi -> "primitive.measure.kpi"
    GeneratedEndpointPrimitiveMissionDriver -> "primitive.mission.driver"
    GeneratedEndpointPrimitiveNeedDriver -> "primitive.need.driver"
    GeneratedEndpointPrimitiveNeedObjective -> "primitive.need.objective"
    GeneratedEndpointPrimitiveStrategyAction -> "primitive.strategy.action"
    GeneratedEndpointPrimitiveStrategyDriver -> "primitive.strategy.driver"
    GeneratedEndpointPrimitiveStrategyKeyResult ->
      "primitive.strategy.key-result"
    GeneratedEndpointPrimitiveStrategyObjective ->
      "primitive.strategy.objective"
    GeneratedEndpointPrimitiveStrategyPrinciple ->
      "primitive.strategy.principle"
    GeneratedEndpointPrimitiveVisionObjective -> "primitive.vision.objective"
    GeneratedEndpointSituationAnchorBusinessCapability ->
      "situation-anchor.business-capability"
    GeneratedEndpointSituationAnchorBusinessObject ->
      "situation-anchor.business-object"
    GeneratedEndpointSituationAnchorBusinessProcess ->
      "situation-anchor.business-process"
    GeneratedEndpointSituationAnchorValueStream ->
      "situation-anchor.value-stream"
    GeneratedEndpointStructuringMeasurePerformanceDimension ->
      "structuring.measure.performance-dimension"
    GeneratedEndpointStructuringStrategyPerformanceDimension ->
      "structuring.strategy.performance-dimension"

lookupGeneratedQualifiedEndpoint :: Text -> Maybe GeneratedQualifiedEndpoint
lookupGeneratedQualifiedEndpoint value =
  case value of
    "context.ethos" -> Just GeneratedEndpointContextEthos
    "context.intervention" -> Just GeneratedEndpointContextIntervention
    "context.measure" -> Just GeneratedEndpointContextMeasure
    "context.mission" -> Just GeneratedEndpointContextMission
    "context.need" -> Just GeneratedEndpointContextNeed
    "context.situation" -> Just GeneratedEndpointContextSituation
    "context.strategy" -> Just GeneratedEndpointContextStrategy
    "context.vision" -> Just GeneratedEndpointContextVision
    "primitive.ethos.principle" -> Just GeneratedEndpointPrimitiveEthosPrinciple
    "primitive.intervention.action" ->
      Just GeneratedEndpointPrimitiveInterventionAction
    "primitive.intervention.key-result" ->
      Just GeneratedEndpointPrimitiveInterventionKeyResult
    "primitive.measure.kpi" -> Just GeneratedEndpointPrimitiveMeasureKpi
    "primitive.mission.driver" -> Just GeneratedEndpointPrimitiveMissionDriver
    "primitive.need.driver" -> Just GeneratedEndpointPrimitiveNeedDriver
    "primitive.need.objective" -> Just GeneratedEndpointPrimitiveNeedObjective
    "primitive.strategy.action" -> Just GeneratedEndpointPrimitiveStrategyAction
    "primitive.strategy.driver" -> Just GeneratedEndpointPrimitiveStrategyDriver
    "primitive.strategy.key-result" ->
      Just GeneratedEndpointPrimitiveStrategyKeyResult
    "primitive.strategy.objective" ->
      Just GeneratedEndpointPrimitiveStrategyObjective
    "primitive.strategy.principle" ->
      Just GeneratedEndpointPrimitiveStrategyPrinciple
    "primitive.vision.objective" ->
      Just GeneratedEndpointPrimitiveVisionObjective
    "situation-anchor.business-capability" ->
      Just GeneratedEndpointSituationAnchorBusinessCapability
    "situation-anchor.business-object" ->
      Just GeneratedEndpointSituationAnchorBusinessObject
    "situation-anchor.business-process" ->
      Just GeneratedEndpointSituationAnchorBusinessProcess
    "situation-anchor.value-stream" ->
      Just GeneratedEndpointSituationAnchorValueStream
    "structuring.measure.performance-dimension" ->
      Just GeneratedEndpointStructuringMeasurePerformanceDimension
    "structuring.strategy.performance-dimension" ->
      Just GeneratedEndpointStructuringStrategyPerformanceDimension
    _ -> Nothing

data GeneratedQualifiedEndpointRow =
  GeneratedQualifiedEndpointRow
    !GeneratedQualifiedEndpoint
    !GeneratedCarrierCategory
    !(Maybe GeneratedO2IType)
    !GeneratedO2IType
  deriving (Eq, Ord, Show)

generatedQualifiedEndpointRow ::
     GeneratedQualifiedEndpoint -> GeneratedQualifiedEndpointRow
generatedQualifiedEndpointRow endpoint =
  case endpoint of
    GeneratedEndpointContextEthos ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextEthos
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeEthos
    GeneratedEndpointContextIntervention ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextIntervention
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeIntervention
    GeneratedEndpointContextMeasure ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextMeasure
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeMeasure
    GeneratedEndpointContextMission ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextMission
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeMission
    GeneratedEndpointContextNeed ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextNeed
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeNeed
    GeneratedEndpointContextSituation ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextSituation
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeSituation
    GeneratedEndpointContextStrategy ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextStrategy
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeStrategy
    GeneratedEndpointContextVision ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointContextVision
        GeneratedCarrierContext
        (Nothing)
        GeneratedTypeVision
    GeneratedEndpointPrimitiveEthosPrinciple ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveEthosPrinciple
        GeneratedCarrierPrimitive
        (Just GeneratedTypeEthos)
        GeneratedTypePrinciple
    GeneratedEndpointPrimitiveInterventionAction ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedCarrierPrimitive
        (Just GeneratedTypeIntervention)
        GeneratedTypeAction
    GeneratedEndpointPrimitiveInterventionKeyResult ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveInterventionKeyResult
        GeneratedCarrierPrimitive
        (Just GeneratedTypeIntervention)
        GeneratedTypeKeyResult
    GeneratedEndpointPrimitiveMeasureKpi ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedCarrierPrimitive
        (Just GeneratedTypeMeasure)
        GeneratedTypeKPI
    GeneratedEndpointPrimitiveMissionDriver ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveMissionDriver
        GeneratedCarrierPrimitive
        (Just GeneratedTypeMission)
        GeneratedTypeDriver
    GeneratedEndpointPrimitiveNeedDriver ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveNeedDriver
        GeneratedCarrierPrimitive
        (Just GeneratedTypeNeed)
        GeneratedTypeDriver
    GeneratedEndpointPrimitiveNeedObjective ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveNeedObjective
        GeneratedCarrierPrimitive
        (Just GeneratedTypeNeed)
        GeneratedTypeObjective
    GeneratedEndpointPrimitiveStrategyAction ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveStrategyAction
        GeneratedCarrierPrimitive
        (Just GeneratedTypeStrategy)
        GeneratedTypeAction
    GeneratedEndpointPrimitiveStrategyDriver ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveStrategyDriver
        GeneratedCarrierPrimitive
        (Just GeneratedTypeStrategy)
        GeneratedTypeDriver
    GeneratedEndpointPrimitiveStrategyKeyResult ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedCarrierPrimitive
        (Just GeneratedTypeStrategy)
        GeneratedTypeKeyResult
    GeneratedEndpointPrimitiveStrategyObjective ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveStrategyObjective
        GeneratedCarrierPrimitive
        (Just GeneratedTypeStrategy)
        GeneratedTypeObjective
    GeneratedEndpointPrimitiveStrategyPrinciple ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveStrategyPrinciple
        GeneratedCarrierPrimitive
        (Just GeneratedTypeStrategy)
        GeneratedTypePrinciple
    GeneratedEndpointPrimitiveVisionObjective ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointPrimitiveVisionObjective
        GeneratedCarrierPrimitive
        (Just GeneratedTypeVision)
        GeneratedTypeObjective
    GeneratedEndpointSituationAnchorBusinessCapability ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointSituationAnchorBusinessCapability
        GeneratedCarrierSituationAnchor
        (Nothing)
        GeneratedTypeBusinessCapability
    GeneratedEndpointSituationAnchorBusinessObject ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointSituationAnchorBusinessObject
        GeneratedCarrierSituationAnchor
        (Nothing)
        GeneratedTypeBusinessObject
    GeneratedEndpointSituationAnchorBusinessProcess ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointSituationAnchorBusinessProcess
        GeneratedCarrierSituationAnchor
        (Nothing)
        GeneratedTypeBusinessProcess
    GeneratedEndpointSituationAnchorValueStream ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointSituationAnchorValueStream
        GeneratedCarrierSituationAnchor
        (Nothing)
        GeneratedTypeValueStream
    GeneratedEndpointStructuringMeasurePerformanceDimension ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointStructuringMeasurePerformanceDimension
        GeneratedCarrierStructuring
        (Just GeneratedTypeMeasure)
        GeneratedTypePerformanceDimension
    GeneratedEndpointStructuringStrategyPerformanceDimension ->
      GeneratedQualifiedEndpointRow
        GeneratedEndpointStructuringStrategyPerformanceDimension
        GeneratedCarrierStructuring
        (Just GeneratedTypeStrategy)
        GeneratedTypePerformanceDimension

generatedQualifiedEndpoints :: NonEmpty GeneratedQualifiedEndpoint
generatedQualifiedEndpoints =
  GeneratedEndpointContextEthos
    :| [ GeneratedEndpointContextIntervention
       , GeneratedEndpointContextMeasure
       , GeneratedEndpointContextMission
       , GeneratedEndpointContextNeed
       , GeneratedEndpointContextSituation
       , GeneratedEndpointContextStrategy
       , GeneratedEndpointContextVision
       , GeneratedEndpointPrimitiveEthosPrinciple
       , GeneratedEndpointPrimitiveInterventionAction
       , GeneratedEndpointPrimitiveInterventionKeyResult
       , GeneratedEndpointPrimitiveMeasureKpi
       , GeneratedEndpointPrimitiveMissionDriver
       , GeneratedEndpointPrimitiveNeedDriver
       , GeneratedEndpointPrimitiveNeedObjective
       , GeneratedEndpointPrimitiveStrategyAction
       , GeneratedEndpointPrimitiveStrategyDriver
       , GeneratedEndpointPrimitiveStrategyKeyResult
       , GeneratedEndpointPrimitiveStrategyObjective
       , GeneratedEndpointPrimitiveStrategyPrinciple
       , GeneratedEndpointPrimitiveVisionObjective
       , GeneratedEndpointSituationAnchorBusinessCapability
       , GeneratedEndpointSituationAnchorBusinessObject
       , GeneratedEndpointSituationAnchorBusinessProcess
       , GeneratedEndpointSituationAnchorValueStream
       , GeneratedEndpointStructuringMeasurePerformanceDimension
       , GeneratedEndpointStructuringStrategyPerformanceDimension
       ]

generatedQualifiedEndpointRows :: NonEmpty GeneratedQualifiedEndpointRow
generatedQualifiedEndpointRows =
  generatedQualifiedEndpointRow <$> generatedQualifiedEndpoints

data GeneratedRelationToken
  = GeneratedTokenAddresses
  | GeneratedTokenAnchors
  | GeneratedTokenChanges
  | GeneratedTokenContains
  | GeneratedTokenContributesTo
  | GeneratedTokenDetermines
  | GeneratedTokenDirects
  | GeneratedTokenFrames
  | GeneratedTokenGrounds
  | GeneratedTokenGuides
  | GeneratedTokenIndicates
  | GeneratedTokenIsConstitutedBy
  | GeneratedTokenMeasures
  | GeneratedTokenOrients
  | GeneratedTokenQualifies
  | GeneratedTokenSetsTargetFor
  | GeneratedTokenSubstantiates
  | GeneratedTokenSurfaces
  | GeneratedTokenTranslatesInto
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedRelationTokenText :: GeneratedRelationToken -> Text
generatedRelationTokenText value =
  case value of
    GeneratedTokenAddresses -> "addresses"
    GeneratedTokenAnchors -> "anchors"
    GeneratedTokenChanges -> "changes"
    GeneratedTokenContains -> "contains"
    GeneratedTokenContributesTo -> "contributes-to"
    GeneratedTokenDetermines -> "determines"
    GeneratedTokenDirects -> "directs"
    GeneratedTokenFrames -> "frames"
    GeneratedTokenGrounds -> "grounds"
    GeneratedTokenGuides -> "guides"
    GeneratedTokenIndicates -> "indicates"
    GeneratedTokenIsConstitutedBy -> "is-constituted-by"
    GeneratedTokenMeasures -> "measures"
    GeneratedTokenOrients -> "orients"
    GeneratedTokenQualifies -> "qualifies"
    GeneratedTokenSetsTargetFor -> "sets-target-for"
    GeneratedTokenSubstantiates -> "substantiates"
    GeneratedTokenSurfaces -> "surfaces"
    GeneratedTokenTranslatesInto -> "translates-into"

lookupGeneratedRelationToken :: Text -> Maybe GeneratedRelationToken
lookupGeneratedRelationToken value =
  case value of
    "addresses" -> Just GeneratedTokenAddresses
    "anchors" -> Just GeneratedTokenAnchors
    "changes" -> Just GeneratedTokenChanges
    "contains" -> Just GeneratedTokenContains
    "contributes-to" -> Just GeneratedTokenContributesTo
    "determines" -> Just GeneratedTokenDetermines
    "directs" -> Just GeneratedTokenDirects
    "frames" -> Just GeneratedTokenFrames
    "grounds" -> Just GeneratedTokenGrounds
    "guides" -> Just GeneratedTokenGuides
    "indicates" -> Just GeneratedTokenIndicates
    "is-constituted-by" -> Just GeneratedTokenIsConstitutedBy
    "measures" -> Just GeneratedTokenMeasures
    "orients" -> Just GeneratedTokenOrients
    "qualifies" -> Just GeneratedTokenQualifies
    "sets-target-for" -> Just GeneratedTokenSetsTargetFor
    "substantiates" -> Just GeneratedTokenSubstantiates
    "surfaces" -> Just GeneratedTokenSurfaces
    "translates-into" -> Just GeneratedTokenTranslatesInto
    _ -> Nothing

generatedRelationTokens :: NonEmpty GeneratedRelationToken
generatedRelationTokens =
  GeneratedTokenAddresses
    :| [ GeneratedTokenAnchors
       , GeneratedTokenChanges
       , GeneratedTokenContains
       , GeneratedTokenContributesTo
       , GeneratedTokenDetermines
       , GeneratedTokenDirects
       , GeneratedTokenFrames
       , GeneratedTokenGrounds
       , GeneratedTokenGuides
       , GeneratedTokenIndicates
       , GeneratedTokenIsConstitutedBy
       , GeneratedTokenMeasures
       , GeneratedTokenOrients
       , GeneratedTokenQualifies
       , GeneratedTokenSetsTargetFor
       , GeneratedTokenSubstantiates
       , GeneratedTokenSurfaces
       , GeneratedTokenTranslatesInto
       ]

data GeneratedSemanticRelation
  = GeneratedRelationEthosGuidesMission
  | GeneratedRelationMissionGroundsVision
  | GeneratedRelationEthosGuidesVision
  | GeneratedRelationVisionOrientsStrategy
  | GeneratedRelationStrategyDirectsStrategy
  | GeneratedRelationStrategyContributesToStrategy
  | GeneratedRelationStrategyQualifiesNeed
  | GeneratedRelationSituationSurfacesNeed
  | GeneratedRelationInterventionAddressesNeed
  | GeneratedRelationStrategyDirectsIntervention
  | GeneratedRelationInterventionChangesSituation
  | GeneratedRelationInterventionSetsTargetForMeasure
  | GeneratedRelationMeasureMeasuresSituation
  | GeneratedRelationStrategyFramesMeasure
  | GeneratedRelationEthosPrincipleGuidesMissionDriver
  | GeneratedRelationEthosPrincipleGuidesVisionObjective
  | GeneratedRelationMissionDriverGroundsVisionObjective
  | GeneratedRelationVisionObjectiveOrientsStrategyObjective
  | GeneratedRelationStrategyDriverGroundsStrategyObjective
  | GeneratedRelationStrategyKeyResultSubstantiatesStrategyObjective
  | GeneratedRelationStrategyPrincipleGuidesStrategyAction
  | GeneratedRelationStrategyActionContributesToStrategyKeyResult
  | GeneratedRelationStrategyPrincipleGuidesStrategyPrinciple
  | GeneratedRelationStrategyKeyResultContributesToStrategyKeyResult
  | GeneratedRelationStrategyActionContributesToStrategyAction
  | GeneratedRelationStrategyKeyResultTranslatesIntoNeedObjective
  | GeneratedRelationNeedDriverGroundsNeedObjective
  | GeneratedRelationStrategyDriverIndicatesMeasurePerformanceDimension
  | GeneratedRelationStrategyKeyResultDeterminesMeasurePerformanceDimension
  | GeneratedRelationStrategyActionGuidesInterventionAction
  | GeneratedRelationInterventionActionContributesToInterventionKeyResult
  | GeneratedRelationInterventionKeyResultSubstantiatesNeedObjective
  | GeneratedRelationInterventionKeyResultContributesToStrategyKeyResult
  | GeneratedRelationInterventionKeyResultSetsTargetForMeasureKpi
  | GeneratedRelationStrategyPerformanceDimensionContainsStrategyKeyResult
  | GeneratedRelationMeasurePerformanceDimensionContainsMeasureKpi
  | GeneratedRelationSituationIsConstitutedByAnchorBusinessCapability
  | GeneratedRelationSituationIsConstitutedByAnchorBusinessProcess
  | GeneratedRelationSituationIsConstitutedByAnchorBusinessObject
  | GeneratedRelationSituationIsConstitutedByAnchorValueStream
  | GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessCapability
  | GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessProcess
  | GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessObject
  | GeneratedRelationSituationAnchorAnchorsNeedDriverValueStream
  | GeneratedRelationInterventionActionChangesSituationAnchorBusinessCapability
  | GeneratedRelationInterventionActionChangesSituationAnchorBusinessProcess
  | GeneratedRelationInterventionActionChangesSituationAnchorBusinessObject
  | GeneratedRelationInterventionActionChangesSituationAnchorValueStream
  | GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessCapability
  | GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessProcess
  | GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessObject
  | GeneratedRelationMeasureKpiMeasuresSituationAnchorValueStream
  deriving (Bounded, Enum, Eq, Ord, Show)

data GeneratedSemanticRelationRow =
  GeneratedSemanticRelationRow
    !GeneratedSemanticRelation
    !GeneratedQualifiedEndpoint
    !GeneratedQualifiedEndpoint
    !GeneratedRelationToken
  deriving (Eq, Ord, Show)

generatedSemanticRelationRow ::
     GeneratedSemanticRelation -> GeneratedSemanticRelationRow
generatedSemanticRelationRow relation =
  case relation of
    GeneratedRelationEthosGuidesMission ->
      GeneratedSemanticRelationRow
        GeneratedRelationEthosGuidesMission
        GeneratedEndpointContextEthos
        GeneratedEndpointContextMission
        GeneratedTokenGuides
    GeneratedRelationMissionGroundsVision ->
      GeneratedSemanticRelationRow
        GeneratedRelationMissionGroundsVision
        GeneratedEndpointContextMission
        GeneratedEndpointContextVision
        GeneratedTokenGrounds
    GeneratedRelationEthosGuidesVision ->
      GeneratedSemanticRelationRow
        GeneratedRelationEthosGuidesVision
        GeneratedEndpointContextEthos
        GeneratedEndpointContextVision
        GeneratedTokenGuides
    GeneratedRelationVisionOrientsStrategy ->
      GeneratedSemanticRelationRow
        GeneratedRelationVisionOrientsStrategy
        GeneratedEndpointContextVision
        GeneratedEndpointContextStrategy
        GeneratedTokenOrients
    GeneratedRelationStrategyDirectsStrategy ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyDirectsStrategy
        GeneratedEndpointContextStrategy
        GeneratedEndpointContextStrategy
        GeneratedTokenDirects
    GeneratedRelationStrategyContributesToStrategy ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyContributesToStrategy
        GeneratedEndpointContextStrategy
        GeneratedEndpointContextStrategy
        GeneratedTokenContributesTo
    GeneratedRelationStrategyQualifiesNeed ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyQualifiesNeed
        GeneratedEndpointContextStrategy
        GeneratedEndpointContextNeed
        GeneratedTokenQualifies
    GeneratedRelationSituationSurfacesNeed ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationSurfacesNeed
        GeneratedEndpointContextSituation
        GeneratedEndpointContextNeed
        GeneratedTokenSurfaces
    GeneratedRelationInterventionAddressesNeed ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionAddressesNeed
        GeneratedEndpointContextIntervention
        GeneratedEndpointContextNeed
        GeneratedTokenAddresses
    GeneratedRelationStrategyDirectsIntervention ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyDirectsIntervention
        GeneratedEndpointContextStrategy
        GeneratedEndpointContextIntervention
        GeneratedTokenDirects
    GeneratedRelationInterventionChangesSituation ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionChangesSituation
        GeneratedEndpointContextIntervention
        GeneratedEndpointContextSituation
        GeneratedTokenChanges
    GeneratedRelationInterventionSetsTargetForMeasure ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionSetsTargetForMeasure
        GeneratedEndpointContextIntervention
        GeneratedEndpointContextMeasure
        GeneratedTokenSetsTargetFor
    GeneratedRelationMeasureMeasuresSituation ->
      GeneratedSemanticRelationRow
        GeneratedRelationMeasureMeasuresSituation
        GeneratedEndpointContextMeasure
        GeneratedEndpointContextSituation
        GeneratedTokenMeasures
    GeneratedRelationStrategyFramesMeasure ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyFramesMeasure
        GeneratedEndpointContextStrategy
        GeneratedEndpointContextMeasure
        GeneratedTokenFrames
    GeneratedRelationEthosPrincipleGuidesMissionDriver ->
      GeneratedSemanticRelationRow
        GeneratedRelationEthosPrincipleGuidesMissionDriver
        GeneratedEndpointPrimitiveEthosPrinciple
        GeneratedEndpointPrimitiveMissionDriver
        GeneratedTokenGuides
    GeneratedRelationEthosPrincipleGuidesVisionObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationEthosPrincipleGuidesVisionObjective
        GeneratedEndpointPrimitiveEthosPrinciple
        GeneratedEndpointPrimitiveVisionObjective
        GeneratedTokenGuides
    GeneratedRelationMissionDriverGroundsVisionObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationMissionDriverGroundsVisionObjective
        GeneratedEndpointPrimitiveMissionDriver
        GeneratedEndpointPrimitiveVisionObjective
        GeneratedTokenGrounds
    GeneratedRelationVisionObjectiveOrientsStrategyObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationVisionObjectiveOrientsStrategyObjective
        GeneratedEndpointPrimitiveVisionObjective
        GeneratedEndpointPrimitiveStrategyObjective
        GeneratedTokenOrients
    GeneratedRelationStrategyDriverGroundsStrategyObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyDriverGroundsStrategyObjective
        GeneratedEndpointPrimitiveStrategyDriver
        GeneratedEndpointPrimitiveStrategyObjective
        GeneratedTokenGrounds
    GeneratedRelationStrategyKeyResultSubstantiatesStrategyObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyKeyResultSubstantiatesStrategyObjective
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedEndpointPrimitiveStrategyObjective
        GeneratedTokenSubstantiates
    GeneratedRelationStrategyPrincipleGuidesStrategyAction ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyPrincipleGuidesStrategyAction
        GeneratedEndpointPrimitiveStrategyPrinciple
        GeneratedEndpointPrimitiveStrategyAction
        GeneratedTokenGuides
    GeneratedRelationStrategyActionContributesToStrategyKeyResult ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyActionContributesToStrategyKeyResult
        GeneratedEndpointPrimitiveStrategyAction
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedTokenContributesTo
    GeneratedRelationStrategyPrincipleGuidesStrategyPrinciple ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyPrincipleGuidesStrategyPrinciple
        GeneratedEndpointPrimitiveStrategyPrinciple
        GeneratedEndpointPrimitiveStrategyPrinciple
        GeneratedTokenGuides
    GeneratedRelationStrategyKeyResultContributesToStrategyKeyResult ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyKeyResultContributesToStrategyKeyResult
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedTokenContributesTo
    GeneratedRelationStrategyActionContributesToStrategyAction ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyActionContributesToStrategyAction
        GeneratedEndpointPrimitiveStrategyAction
        GeneratedEndpointPrimitiveStrategyAction
        GeneratedTokenContributesTo
    GeneratedRelationStrategyKeyResultTranslatesIntoNeedObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyKeyResultTranslatesIntoNeedObjective
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedEndpointPrimitiveNeedObjective
        GeneratedTokenTranslatesInto
    GeneratedRelationNeedDriverGroundsNeedObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationNeedDriverGroundsNeedObjective
        GeneratedEndpointPrimitiveNeedDriver
        GeneratedEndpointPrimitiveNeedObjective
        GeneratedTokenGrounds
    GeneratedRelationStrategyDriverIndicatesMeasurePerformanceDimension ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyDriverIndicatesMeasurePerformanceDimension
        GeneratedEndpointPrimitiveStrategyDriver
        GeneratedEndpointStructuringMeasurePerformanceDimension
        GeneratedTokenIndicates
    GeneratedRelationStrategyKeyResultDeterminesMeasurePerformanceDimension ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyKeyResultDeterminesMeasurePerformanceDimension
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedEndpointStructuringMeasurePerformanceDimension
        GeneratedTokenDetermines
    GeneratedRelationStrategyActionGuidesInterventionAction ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyActionGuidesInterventionAction
        GeneratedEndpointPrimitiveStrategyAction
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedTokenGuides
    GeneratedRelationInterventionActionContributesToInterventionKeyResult ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionActionContributesToInterventionKeyResult
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedEndpointPrimitiveInterventionKeyResult
        GeneratedTokenContributesTo
    GeneratedRelationInterventionKeyResultSubstantiatesNeedObjective ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionKeyResultSubstantiatesNeedObjective
        GeneratedEndpointPrimitiveInterventionKeyResult
        GeneratedEndpointPrimitiveNeedObjective
        GeneratedTokenSubstantiates
    GeneratedRelationInterventionKeyResultContributesToStrategyKeyResult ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionKeyResultContributesToStrategyKeyResult
        GeneratedEndpointPrimitiveInterventionKeyResult
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedTokenContributesTo
    GeneratedRelationInterventionKeyResultSetsTargetForMeasureKpi ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionKeyResultSetsTargetForMeasureKpi
        GeneratedEndpointPrimitiveInterventionKeyResult
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedTokenSetsTargetFor
    GeneratedRelationStrategyPerformanceDimensionContainsStrategyKeyResult ->
      GeneratedSemanticRelationRow
        GeneratedRelationStrategyPerformanceDimensionContainsStrategyKeyResult
        GeneratedEndpointStructuringStrategyPerformanceDimension
        GeneratedEndpointPrimitiveStrategyKeyResult
        GeneratedTokenContains
    GeneratedRelationMeasurePerformanceDimensionContainsMeasureKpi ->
      GeneratedSemanticRelationRow
        GeneratedRelationMeasurePerformanceDimensionContainsMeasureKpi
        GeneratedEndpointStructuringMeasurePerformanceDimension
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedTokenContains
    GeneratedRelationSituationIsConstitutedByAnchorBusinessCapability ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationIsConstitutedByAnchorBusinessCapability
        GeneratedEndpointContextSituation
        GeneratedEndpointSituationAnchorBusinessCapability
        GeneratedTokenIsConstitutedBy
    GeneratedRelationSituationIsConstitutedByAnchorBusinessProcess ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationIsConstitutedByAnchorBusinessProcess
        GeneratedEndpointContextSituation
        GeneratedEndpointSituationAnchorBusinessProcess
        GeneratedTokenIsConstitutedBy
    GeneratedRelationSituationIsConstitutedByAnchorBusinessObject ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationIsConstitutedByAnchorBusinessObject
        GeneratedEndpointContextSituation
        GeneratedEndpointSituationAnchorBusinessObject
        GeneratedTokenIsConstitutedBy
    GeneratedRelationSituationIsConstitutedByAnchorValueStream ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationIsConstitutedByAnchorValueStream
        GeneratedEndpointContextSituation
        GeneratedEndpointSituationAnchorValueStream
        GeneratedTokenIsConstitutedBy
    GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessCapability ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessCapability
        GeneratedEndpointSituationAnchorBusinessCapability
        GeneratedEndpointPrimitiveNeedDriver
        GeneratedTokenAnchors
    GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessProcess ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessProcess
        GeneratedEndpointSituationAnchorBusinessProcess
        GeneratedEndpointPrimitiveNeedDriver
        GeneratedTokenAnchors
    GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessObject ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessObject
        GeneratedEndpointSituationAnchorBusinessObject
        GeneratedEndpointPrimitiveNeedDriver
        GeneratedTokenAnchors
    GeneratedRelationSituationAnchorAnchorsNeedDriverValueStream ->
      GeneratedSemanticRelationRow
        GeneratedRelationSituationAnchorAnchorsNeedDriverValueStream
        GeneratedEndpointSituationAnchorValueStream
        GeneratedEndpointPrimitiveNeedDriver
        GeneratedTokenAnchors
    GeneratedRelationInterventionActionChangesSituationAnchorBusinessCapability ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionActionChangesSituationAnchorBusinessCapability
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedEndpointSituationAnchorBusinessCapability
        GeneratedTokenChanges
    GeneratedRelationInterventionActionChangesSituationAnchorBusinessProcess ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionActionChangesSituationAnchorBusinessProcess
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedEndpointSituationAnchorBusinessProcess
        GeneratedTokenChanges
    GeneratedRelationInterventionActionChangesSituationAnchorBusinessObject ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionActionChangesSituationAnchorBusinessObject
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedEndpointSituationAnchorBusinessObject
        GeneratedTokenChanges
    GeneratedRelationInterventionActionChangesSituationAnchorValueStream ->
      GeneratedSemanticRelationRow
        GeneratedRelationInterventionActionChangesSituationAnchorValueStream
        GeneratedEndpointPrimitiveInterventionAction
        GeneratedEndpointSituationAnchorValueStream
        GeneratedTokenChanges
    GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessCapability ->
      GeneratedSemanticRelationRow
        GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessCapability
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedEndpointSituationAnchorBusinessCapability
        GeneratedTokenMeasures
    GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessProcess ->
      GeneratedSemanticRelationRow
        GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessProcess
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedEndpointSituationAnchorBusinessProcess
        GeneratedTokenMeasures
    GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessObject ->
      GeneratedSemanticRelationRow
        GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessObject
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedEndpointSituationAnchorBusinessObject
        GeneratedTokenMeasures
    GeneratedRelationMeasureKpiMeasuresSituationAnchorValueStream ->
      GeneratedSemanticRelationRow
        GeneratedRelationMeasureKpiMeasuresSituationAnchorValueStream
        GeneratedEndpointPrimitiveMeasureKpi
        GeneratedEndpointSituationAnchorValueStream
        GeneratedTokenMeasures

generatedSemanticRelations :: NonEmpty GeneratedSemanticRelation
generatedSemanticRelations =
  GeneratedRelationEthosGuidesMission
    :| [ GeneratedRelationMissionGroundsVision
       , GeneratedRelationEthosGuidesVision
       , GeneratedRelationVisionOrientsStrategy
       , GeneratedRelationStrategyDirectsStrategy
       , GeneratedRelationStrategyContributesToStrategy
       , GeneratedRelationStrategyQualifiesNeed
       , GeneratedRelationSituationSurfacesNeed
       , GeneratedRelationInterventionAddressesNeed
       , GeneratedRelationStrategyDirectsIntervention
       , GeneratedRelationInterventionChangesSituation
       , GeneratedRelationInterventionSetsTargetForMeasure
       , GeneratedRelationMeasureMeasuresSituation
       , GeneratedRelationStrategyFramesMeasure
       , GeneratedRelationEthosPrincipleGuidesMissionDriver
       , GeneratedRelationEthosPrincipleGuidesVisionObjective
       , GeneratedRelationMissionDriverGroundsVisionObjective
       , GeneratedRelationVisionObjectiveOrientsStrategyObjective
       , GeneratedRelationStrategyDriverGroundsStrategyObjective
       , GeneratedRelationStrategyKeyResultSubstantiatesStrategyObjective
       , GeneratedRelationStrategyPrincipleGuidesStrategyAction
       , GeneratedRelationStrategyActionContributesToStrategyKeyResult
       , GeneratedRelationStrategyPrincipleGuidesStrategyPrinciple
       , GeneratedRelationStrategyKeyResultContributesToStrategyKeyResult
       , GeneratedRelationStrategyActionContributesToStrategyAction
       , GeneratedRelationStrategyKeyResultTranslatesIntoNeedObjective
       , GeneratedRelationNeedDriverGroundsNeedObjective
       , GeneratedRelationStrategyDriverIndicatesMeasurePerformanceDimension
       , GeneratedRelationStrategyKeyResultDeterminesMeasurePerformanceDimension
       , GeneratedRelationStrategyActionGuidesInterventionAction
       , GeneratedRelationInterventionActionContributesToInterventionKeyResult
       , GeneratedRelationInterventionKeyResultSubstantiatesNeedObjective
       , GeneratedRelationInterventionKeyResultContributesToStrategyKeyResult
       , GeneratedRelationInterventionKeyResultSetsTargetForMeasureKpi
       , GeneratedRelationStrategyPerformanceDimensionContainsStrategyKeyResult
       , GeneratedRelationMeasurePerformanceDimensionContainsMeasureKpi
       , GeneratedRelationSituationIsConstitutedByAnchorBusinessCapability
       , GeneratedRelationSituationIsConstitutedByAnchorBusinessProcess
       , GeneratedRelationSituationIsConstitutedByAnchorBusinessObject
       , GeneratedRelationSituationIsConstitutedByAnchorValueStream
       , GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessCapability
       , GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessProcess
       , GeneratedRelationSituationAnchorAnchorsNeedDriverBusinessObject
       , GeneratedRelationSituationAnchorAnchorsNeedDriverValueStream
       , GeneratedRelationInterventionActionChangesSituationAnchorBusinessCapability
       , GeneratedRelationInterventionActionChangesSituationAnchorBusinessProcess
       , GeneratedRelationInterventionActionChangesSituationAnchorBusinessObject
       , GeneratedRelationInterventionActionChangesSituationAnchorValueStream
       , GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessCapability
       , GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessProcess
       , GeneratedRelationMeasureKpiMeasuresSituationAnchorBusinessObject
       , GeneratedRelationMeasureKpiMeasuresSituationAnchorValueStream
       ]

generatedSemanticRelationRows :: NonEmpty GeneratedSemanticRelationRow
generatedSemanticRelationRows =
  generatedSemanticRelationRow <$> generatedSemanticRelations

data GeneratedStructuredPropositionFamily =
  GeneratedFamilyCollectiveStrategyRealization
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedStructuredPropositionFamilyText ::
     GeneratedStructuredPropositionFamily -> Text
generatedStructuredPropositionFamilyText value =
  case value of
    GeneratedFamilyCollectiveStrategyRealization ->
      "collective-strategy-realization"

lookupGeneratedStructuredPropositionFamily ::
     Text -> Maybe GeneratedStructuredPropositionFamily
lookupGeneratedStructuredPropositionFamily value =
  case value of
    "collective-strategy-realization" ->
      Just GeneratedFamilyCollectiveStrategyRealization
    _ -> Nothing

generatedStructuredPropositionFamilies ::
     NonEmpty GeneratedStructuredPropositionFamily
generatedStructuredPropositionFamilies =
  GeneratedFamilyCollectiveStrategyRealization :| []

data GeneratedStructuredPropositionRole
  = GeneratedRoleCollectiveStrategyRealizationRoleParticipant
  | GeneratedRoleCollectiveStrategyRealizationRoleTarget
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedStructuredPropositionRoleText ::
     GeneratedStructuredPropositionRole -> Text
generatedStructuredPropositionRoleText value =
  case value of
    GeneratedRoleCollectiveStrategyRealizationRoleParticipant ->
      "collective-strategy-realization.role.participant"
    GeneratedRoleCollectiveStrategyRealizationRoleTarget ->
      "collective-strategy-realization.role.target"

lookupGeneratedStructuredPropositionRole ::
     Text -> Maybe GeneratedStructuredPropositionRole
lookupGeneratedStructuredPropositionRole value =
  case value of
    "collective-strategy-realization.role.participant" ->
      Just GeneratedRoleCollectiveStrategyRealizationRoleParticipant
    "collective-strategy-realization.role.target" ->
      Just GeneratedRoleCollectiveStrategyRealizationRoleTarget
    _ -> Nothing

generatedStructuredPropositionRoles ::
     NonEmpty GeneratedStructuredPropositionRole
generatedStructuredPropositionRoles =
  GeneratedRoleCollectiveStrategyRealizationRoleParticipant
    :| [GeneratedRoleCollectiveStrategyRealizationRoleTarget]

data GeneratedQualificationProposalRole
  = GeneratedQualificationRoleNeedQualificationProposalRoleNeed
  | GeneratedQualificationRoleNeedQualificationProposalRoleStrategy
  | GeneratedQualificationRoleNeedQualificationProposalRoleKeyResult
  | GeneratedQualificationRoleNeedQualificationProposalRoleObjective
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedQualificationProposalRoleText ::
     GeneratedQualificationProposalRole -> Text
generatedQualificationProposalRoleText value =
  case value of
    GeneratedQualificationRoleNeedQualificationProposalRoleNeed ->
      "need-qualification-proposal.role.need"
    GeneratedQualificationRoleNeedQualificationProposalRoleStrategy ->
      "need-qualification-proposal.role.strategy"
    GeneratedQualificationRoleNeedQualificationProposalRoleKeyResult ->
      "need-qualification-proposal.role.key-result"
    GeneratedQualificationRoleNeedQualificationProposalRoleObjective ->
      "need-qualification-proposal.role.objective"

lookupGeneratedQualificationProposalRole ::
     Text -> Maybe GeneratedQualificationProposalRole
lookupGeneratedQualificationProposalRole value =
  case value of
    "need-qualification-proposal.role.need" ->
      Just GeneratedQualificationRoleNeedQualificationProposalRoleNeed
    "need-qualification-proposal.role.strategy" ->
      Just GeneratedQualificationRoleNeedQualificationProposalRoleStrategy
    "need-qualification-proposal.role.key-result" ->
      Just GeneratedQualificationRoleNeedQualificationProposalRoleKeyResult
    "need-qualification-proposal.role.objective" ->
      Just GeneratedQualificationRoleNeedQualificationProposalRoleObjective
    _ -> Nothing

generatedQualificationProposalRoles ::
     NonEmpty GeneratedQualificationProposalRole
generatedQualificationProposalRoles =
  GeneratedQualificationRoleNeedQualificationProposalRoleNeed
    :| [ GeneratedQualificationRoleNeedQualificationProposalRoleStrategy
       , GeneratedQualificationRoleNeedQualificationProposalRoleKeyResult
       , GeneratedQualificationRoleNeedQualificationProposalRoleObjective
       ]

data GeneratedStructuredComposition =
  GeneratedCompositionConjunctive
  deriving (Bounded, Enum, Eq, Ord, Show)

data GeneratedStructuredCardinality
  = GeneratedCardinalityAtLeastTwo
  | GeneratedCardinalityExactlyOne
  deriving (Bounded, Enum, Eq, Ord, Show)

data GeneratedParticipantCompleteness
  = GeneratedCompletenessOpen
  | GeneratedCompletenessClosed
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedParticipantCompletenessIdText ::
     GeneratedParticipantCompleteness -> Text
generatedParticipantCompletenessIdText value =
  case value of
    GeneratedCompletenessOpen ->
      "collective-strategy-realization.participant-completeness.open"
    GeneratedCompletenessClosed ->
      "collective-strategy-realization.participant-completeness.closed"

generatedParticipantCompletenessToken ::
     GeneratedParticipantCompleteness -> Text
generatedParticipantCompletenessToken value =
  case value of
    GeneratedCompletenessOpen -> "open"
    GeneratedCompletenessClosed -> "closed"

lookupGeneratedParticipantCompletenessId ::
     Text -> Maybe GeneratedParticipantCompleteness
lookupGeneratedParticipantCompletenessId value =
  case value of
    "collective-strategy-realization.participant-completeness.open" ->
      Just GeneratedCompletenessOpen
    "collective-strategy-realization.participant-completeness.closed" ->
      Just GeneratedCompletenessClosed
    _ -> Nothing

lookupGeneratedParticipantCompletenessToken ::
     Text -> Maybe GeneratedParticipantCompleteness
lookupGeneratedParticipantCompletenessToken value =
  case value of
    "open" -> Just GeneratedCompletenessOpen
    "closed" -> Just GeneratedCompletenessClosed
    _ -> Nothing

generatedParticipantCompletenessValues ::
     NonEmpty GeneratedParticipantCompleteness
generatedParticipantCompletenessValues =
  GeneratedCompletenessOpen :| [GeneratedCompletenessClosed]

data GeneratedStructuredFamilyRow =
  GeneratedStructuredFamilyRow
    !GeneratedStructuredPropositionFamily
    !Text
    !GeneratedStructuredComposition
    !GeneratedStructuredPropositionRole
    !GeneratedQualifiedEndpoint
    !GeneratedStructuredCardinality
    !Bool
    !GeneratedStructuredPropositionRole
    !GeneratedQualifiedEndpoint
    !GeneratedStructuredCardinality
    !Bool
    !(NonEmpty GeneratedParticipantCompleteness)
    !Bool
  deriving (Eq, Ord, Show)

generatedStructuredFamilyRow ::
     GeneratedStructuredPropositionFamily -> GeneratedStructuredFamilyRow
generatedStructuredFamilyRow family =
  case family of
    GeneratedFamilyCollectiveStrategyRealization ->
      GeneratedStructuredFamilyRow
        GeneratedFamilyCollectiveStrategyRealization
        "CollectiveStrategyRealization"
        GeneratedCompositionConjunctive
        GeneratedRoleCollectiveStrategyRealizationRoleParticipant
        GeneratedEndpointContextStrategy
        GeneratedCardinalityAtLeastTwo
        True
        GeneratedRoleCollectiveStrategyRealizationRoleTarget
        GeneratedEndpointContextStrategy
        GeneratedCardinalityExactlyOne
        True
        (GeneratedCompletenessOpen :| [GeneratedCompletenessClosed])
        True

generatedStructuredFamilyRows :: NonEmpty GeneratedStructuredFamilyRow
generatedStructuredFamilyRows =
  generatedStructuredFamilyRow <$> generatedStructuredPropositionFamilies

data GeneratedSemanticEvidenceSchema
  = GeneratedAssertedDependencyKeySchema
  | GeneratedFitClaimKeySchema
  | GeneratedNeedKeySchema
  | GeneratedNeedMemberKeySchema
  | GeneratedParticipantClaimKeySchema
  | GeneratedStrategyKeySchema
  | GeneratedStrategyMemberKeySchema
  deriving (Bounded, Enum, Eq, Ord, Show)

data GeneratedSemanticEvidenceSchemaWitness (schema :: GeneratedSemanticEvidenceSchema) where
  GeneratedAssertedDependencyKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness
         'GeneratedAssertedDependencyKeySchema
  GeneratedFitClaimKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness 'GeneratedFitClaimKeySchema
  GeneratedNeedKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness 'GeneratedNeedKeySchema
  GeneratedNeedMemberKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness 'GeneratedNeedMemberKeySchema
  GeneratedParticipantClaimKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness
         'GeneratedParticipantClaimKeySchema
  GeneratedStrategyKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness 'GeneratedStrategyKeySchema
  GeneratedStrategyMemberKeyWitness
    :: GeneratedSemanticEvidenceSchemaWitness 'GeneratedStrategyMemberKeySchema

generatedSemanticEvidenceSchemaName ::
     GeneratedSemanticEvidenceSchemaWitness schema -> Text
generatedSemanticEvidenceSchemaName witness =
  case witness of
    GeneratedAssertedDependencyKeyWitness -> "AssertedDependencyKey"
    GeneratedFitClaimKeyWitness -> "FitClaimKey"
    GeneratedNeedKeyWitness -> "NeedKey"
    GeneratedNeedMemberKeyWitness -> "NeedMemberKey"
    GeneratedParticipantClaimKeyWitness -> "ParticipantClaimKey"
    GeneratedStrategyKeyWitness -> "StrategyKey"
    GeneratedStrategyMemberKeyWitness -> "StrategyMemberKey"

generatedSemanticEvidenceSchemaFields ::
     GeneratedSemanticEvidenceSchemaWitness schema -> NonEmpty Text
generatedSemanticEvidenceSchemaFields witness =
  case witness of
    GeneratedAssertedDependencyKeyWitness ->
      "propositionOccurrence"
        :| ["endpointOccurrence", "contextualizationOccurrence"]
    GeneratedFitClaimKeyWitness -> "claim" :| []
    GeneratedNeedKeyWitness -> "need" :| []
    GeneratedNeedMemberKeyWitness -> "need" :| ["member"]
    GeneratedParticipantClaimKeyWitness -> "claim" :| ["participant"]
    GeneratedStrategyKeyWitness -> "strategy" :| []
    GeneratedStrategyMemberKeyWitness -> "strategy" :| ["member"]

data GeneratedSemanticRule (schema :: GeneratedSemanticEvidenceSchema) where
  CollectiveAssertedCollectiveCoverageRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveAssertedCompletenessRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveAssertedMacroSupportRule
    :: GeneratedSemanticRule 'GeneratedParticipantClaimKeySchema
  CollectiveAssertedParticipantPrimitiveSupportRule
    :: GeneratedSemanticRule 'GeneratedParticipantClaimKeySchema
  CollectiveFitPairwiseCoherenceRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveFitParticipantBindingRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveFitParticipantCompatibilityRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveFitTargetBindingRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveFitTargetGuidingPolicyRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  CollectiveFitTargetTradeOffsRule
    :: GeneratedSemanticRule 'GeneratedFitClaimKeySchema
  ContextualizationAssertedDependencyRule
    :: GeneratedSemanticRule 'GeneratedAssertedDependencyKeySchema
  SituatedNeedDriverAnchoringRule
    :: GeneratedSemanticRule 'GeneratedNeedMemberKeySchema
  SituatedNeedDriverCardinalityRule
    :: GeneratedSemanticRule 'GeneratedNeedKeySchema
  SituatedNeedObjectiveCardinalityRule
    :: GeneratedSemanticRule 'GeneratedNeedKeySchema
  SituatedNeedObjectiveGroundingRule
    :: GeneratedSemanticRule 'GeneratedNeedMemberKeySchema
  SituatedNeedSurfacingSituationAnchoringRule
    :: GeneratedSemanticRule 'GeneratedNeedMemberKeySchema
  SituatedNeedSurfacingSituationCardinalityRule
    :: GeneratedSemanticRule 'GeneratedNeedKeySchema
  StrategyFormulationActionContributionsRule
    :: GeneratedSemanticRule 'GeneratedStrategyMemberKeySchema
  StrategyFormulationActionsRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema
  StrategyFormulationDiagnosisRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema
  StrategyFormulationDiagnosisGroundingRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema
  StrategyFormulationGuidingPolicyRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema
  StrategyFormulationGuidingPolicyActionsRule
    :: GeneratedSemanticRule 'GeneratedStrategyMemberKeySchema
  StrategyFormulationIntentRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema
  StrategyFormulationKeyResultSubstantiationRule
    :: GeneratedSemanticRule 'GeneratedStrategyMemberKeySchema
  StrategyFormulationKeyResultsRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema
  StrategyFormulationVisionOrientationRule
    :: GeneratedSemanticRule 'GeneratedStrategyKeySchema

generatedSemanticRuleId :: GeneratedSemanticRule schema -> Text
generatedSemanticRuleId rule =
  case rule of
    CollectiveAssertedCollectiveCoverageRule ->
      "core.collective-strategy-realization.asserted-collective-coverage"
    CollectiveAssertedCompletenessRule ->
      "core.collective-strategy-realization.asserted-completeness"
    CollectiveAssertedMacroSupportRule ->
      "core.collective-strategy-realization.asserted-macro-support"
    CollectiveAssertedParticipantPrimitiveSupportRule ->
      "core.collective-strategy-realization."
        <> "asserted-participant-primitive-support"
    CollectiveFitPairwiseCoherenceRule ->
      "core.collective-strategy-realization.fit-pairwise-coherence"
    CollectiveFitParticipantBindingRule ->
      "core.collective-strategy-realization.fit-participant-binding"
    CollectiveFitParticipantCompatibilityRule ->
      "core.collective-strategy-realization.fit-participant-compatibility"
    CollectiveFitTargetBindingRule ->
      "core.collective-strategy-realization.fit-target-binding"
    CollectiveFitTargetGuidingPolicyRule ->
      "core.collective-strategy-realization.fit-target-guiding-policy"
    CollectiveFitTargetTradeOffsRule ->
      "core.collective-strategy-realization.fit-target-trade-offs"
    ContextualizationAssertedDependencyRule ->
      "core.contextualization.asserted-dependency"
    SituatedNeedDriverAnchoringRule -> "core.situated-need.driver-anchoring"
    SituatedNeedDriverCardinalityRule -> "core.situated-need.driver-cardinality"
    SituatedNeedObjectiveCardinalityRule ->
      "core.situated-need.objective-cardinality"
    SituatedNeedObjectiveGroundingRule ->
      "core.situated-need.objective-grounding"
    SituatedNeedSurfacingSituationAnchoringRule ->
      "core.situated-need.surfacing-situation-anchoring"
    SituatedNeedSurfacingSituationCardinalityRule ->
      "core.situated-need.surfacing-situation-cardinality"
    StrategyFormulationActionContributionsRule ->
      "core.strategy-formulation.action-contributions"
    StrategyFormulationActionsRule -> "core.strategy-formulation.actions"
    StrategyFormulationDiagnosisRule -> "core.strategy-formulation.diagnosis"
    StrategyFormulationDiagnosisGroundingRule ->
      "core.strategy-formulation.diagnosis-grounding"
    StrategyFormulationGuidingPolicyRule ->
      "core.strategy-formulation.guiding-policy"
    StrategyFormulationGuidingPolicyActionsRule ->
      "core.strategy-formulation.guiding-policy-actions"
    StrategyFormulationIntentRule -> "core.strategy-formulation.intent"
    StrategyFormulationKeyResultSubstantiationRule ->
      "core.strategy-formulation.key-result-substantiation"
    StrategyFormulationKeyResultsRule -> "core.strategy-formulation.key-results"
    StrategyFormulationVisionOrientationRule ->
      "core.strategy-formulation.vision-orientation"

generatedSemanticRuleRank :: GeneratedSemanticRule schema -> Int
generatedSemanticRuleRank rule =
  case rule of
    CollectiveAssertedCollectiveCoverageRule -> 0
    CollectiveAssertedCompletenessRule -> 1
    CollectiveAssertedMacroSupportRule -> 2
    CollectiveAssertedParticipantPrimitiveSupportRule -> 3
    CollectiveFitPairwiseCoherenceRule -> 4
    CollectiveFitParticipantBindingRule -> 5
    CollectiveFitParticipantCompatibilityRule -> 6
    CollectiveFitTargetBindingRule -> 7
    CollectiveFitTargetGuidingPolicyRule -> 8
    CollectiveFitTargetTradeOffsRule -> 9
    ContextualizationAssertedDependencyRule -> 10
    SituatedNeedDriverAnchoringRule -> 11
    SituatedNeedDriverCardinalityRule -> 12
    SituatedNeedObjectiveCardinalityRule -> 13
    SituatedNeedObjectiveGroundingRule -> 14
    SituatedNeedSurfacingSituationAnchoringRule -> 15
    SituatedNeedSurfacingSituationCardinalityRule -> 16
    StrategyFormulationActionContributionsRule -> 17
    StrategyFormulationActionsRule -> 18
    StrategyFormulationDiagnosisRule -> 19
    StrategyFormulationDiagnosisGroundingRule -> 20
    StrategyFormulationGuidingPolicyRule -> 21
    StrategyFormulationGuidingPolicyActionsRule -> 22
    StrategyFormulationIntentRule -> 23
    StrategyFormulationKeyResultSubstantiationRule -> 24
    StrategyFormulationKeyResultsRule -> 25
    StrategyFormulationVisionOrientationRule -> 26

generatedSemanticRuleEvidenceSchema ::
     GeneratedSemanticRule schema
  -> GeneratedSemanticEvidenceSchemaWitness schema
generatedSemanticRuleEvidenceSchema rule =
  case rule of
    CollectiveAssertedCollectiveCoverageRule -> GeneratedFitClaimKeyWitness
    CollectiveAssertedCompletenessRule -> GeneratedFitClaimKeyWitness
    CollectiveAssertedMacroSupportRule -> GeneratedParticipantClaimKeyWitness
    CollectiveAssertedParticipantPrimitiveSupportRule ->
      GeneratedParticipantClaimKeyWitness
    CollectiveFitPairwiseCoherenceRule -> GeneratedFitClaimKeyWitness
    CollectiveFitParticipantBindingRule -> GeneratedFitClaimKeyWitness
    CollectiveFitParticipantCompatibilityRule -> GeneratedFitClaimKeyWitness
    CollectiveFitTargetBindingRule -> GeneratedFitClaimKeyWitness
    CollectiveFitTargetGuidingPolicyRule -> GeneratedFitClaimKeyWitness
    CollectiveFitTargetTradeOffsRule -> GeneratedFitClaimKeyWitness
    ContextualizationAssertedDependencyRule ->
      GeneratedAssertedDependencyKeyWitness
    SituatedNeedDriverAnchoringRule -> GeneratedNeedMemberKeyWitness
    SituatedNeedDriverCardinalityRule -> GeneratedNeedKeyWitness
    SituatedNeedObjectiveCardinalityRule -> GeneratedNeedKeyWitness
    SituatedNeedObjectiveGroundingRule -> GeneratedNeedMemberKeyWitness
    SituatedNeedSurfacingSituationAnchoringRule -> GeneratedNeedMemberKeyWitness
    SituatedNeedSurfacingSituationCardinalityRule -> GeneratedNeedKeyWitness
    StrategyFormulationActionContributionsRule ->
      GeneratedStrategyMemberKeyWitness
    StrategyFormulationActionsRule -> GeneratedStrategyKeyWitness
    StrategyFormulationDiagnosisRule -> GeneratedStrategyKeyWitness
    StrategyFormulationDiagnosisGroundingRule -> GeneratedStrategyKeyWitness
    StrategyFormulationGuidingPolicyRule -> GeneratedStrategyKeyWitness
    StrategyFormulationGuidingPolicyActionsRule ->
      GeneratedStrategyMemberKeyWitness
    StrategyFormulationIntentRule -> GeneratedStrategyKeyWitness
    StrategyFormulationKeyResultSubstantiationRule ->
      GeneratedStrategyMemberKeyWitness
    StrategyFormulationKeyResultsRule -> GeneratedStrategyKeyWitness
    StrategyFormulationVisionOrientationRule -> GeneratedStrategyKeyWitness

data SomeGeneratedSemanticRule where
  SomeGeneratedSemanticRule
    :: GeneratedSemanticRule schema -> SomeGeneratedSemanticRule

generatedSomeSemanticRuleId :: SomeGeneratedSemanticRule -> Text
generatedSomeSemanticRuleId (SomeGeneratedSemanticRule rule) =
  generatedSemanticRuleId rule

generatedSomeSemanticRuleRank :: SomeGeneratedSemanticRule -> Int
generatedSomeSemanticRuleRank (SomeGeneratedSemanticRule rule) =
  generatedSemanticRuleRank rule

generatedSemanticRules :: NonEmpty SomeGeneratedSemanticRule
generatedSemanticRules =
  SomeGeneratedSemanticRule CollectiveAssertedCollectiveCoverageRule
    :| [ SomeGeneratedSemanticRule CollectiveAssertedCompletenessRule
       , SomeGeneratedSemanticRule CollectiveAssertedMacroSupportRule
       , SomeGeneratedSemanticRule
           CollectiveAssertedParticipantPrimitiveSupportRule
       , SomeGeneratedSemanticRule CollectiveFitPairwiseCoherenceRule
       , SomeGeneratedSemanticRule CollectiveFitParticipantBindingRule
       , SomeGeneratedSemanticRule CollectiveFitParticipantCompatibilityRule
       , SomeGeneratedSemanticRule CollectiveFitTargetBindingRule
       , SomeGeneratedSemanticRule CollectiveFitTargetGuidingPolicyRule
       , SomeGeneratedSemanticRule CollectiveFitTargetTradeOffsRule
       , SomeGeneratedSemanticRule ContextualizationAssertedDependencyRule
       , SomeGeneratedSemanticRule SituatedNeedDriverAnchoringRule
       , SomeGeneratedSemanticRule SituatedNeedDriverCardinalityRule
       , SomeGeneratedSemanticRule SituatedNeedObjectiveCardinalityRule
       , SomeGeneratedSemanticRule SituatedNeedObjectiveGroundingRule
       , SomeGeneratedSemanticRule SituatedNeedSurfacingSituationAnchoringRule
       , SomeGeneratedSemanticRule SituatedNeedSurfacingSituationCardinalityRule
       , SomeGeneratedSemanticRule StrategyFormulationActionContributionsRule
       , SomeGeneratedSemanticRule StrategyFormulationActionsRule
       , SomeGeneratedSemanticRule StrategyFormulationDiagnosisRule
       , SomeGeneratedSemanticRule StrategyFormulationDiagnosisGroundingRule
       , SomeGeneratedSemanticRule StrategyFormulationGuidingPolicyRule
       , SomeGeneratedSemanticRule StrategyFormulationGuidingPolicyActionsRule
       , SomeGeneratedSemanticRule StrategyFormulationIntentRule
       , SomeGeneratedSemanticRule
           StrategyFormulationKeyResultSubstantiationRule
       , SomeGeneratedSemanticRule StrategyFormulationKeyResultsRule
       , SomeGeneratedSemanticRule StrategyFormulationVisionOrientationRule
       ]

semanticsRuleIds :: NonEmpty Text
semanticsRuleIds = generatedSomeSemanticRuleId <$> generatedSemanticRules

ruleIds :: NonEmpty Text
ruleIds =
  "core.assessment.actual-start.cardinality"
    :| [ "core.assessment.actual-start.chronology"
       , "core.assessment.anchor.identity"
       , "core.assessment.chronology.observation"
       , "core.assessment.coverage.trace-observation"
       , "core.assessment.effect-criterion.apply"
       , "core.assessment.identity.observation"
       , "core.assessment.identity.observation-uniqueness"
       , "core.assessment.kpi.identity"
       , "core.assessment.limitations.required"
       , "core.assessment.readiness.reconstructed-proof"
       , "core.assessment.source.nonempty"
       , "core.assessment.target-criterion.apply"
       , "core.assessment.trace.identity"
       , "core.assessment.value-domain.observation"
       , "core.collective-strategy-realization.asserted-collective-coverage"
       , "core.collective-strategy-realization.asserted-completeness"
       , "core.collective-strategy-realization.asserted-macro-support"
       , "core.collective-strategy-realization.asserted-participant-primitive-support"
       , "core.collective-strategy-realization.fit-pairwise-coherence"
       , "core.collective-strategy-realization.fit-participant-binding"
       , "core.collective-strategy-realization.fit-participant-compatibility"
       , "core.collective-strategy-realization.fit-target-binding"
       , "core.collective-strategy-realization.fit-target-guiding-policy"
       , "core.collective-strategy-realization.fit-target-trade-offs"
       , "core.collective-strategy-realization.participant-cardinality"
       , "core.collective-strategy-realization.participant-type"
       , "core.collective-strategy-realization.participant-uniqueness"
       , "core.collective-strategy-realization.target-cardinality"
       , "core.collective-strategy-realization.target-distinctness"
       , "core.collective-strategy-realization.target-type"
       , "core.contextualization.asserted-dependency"
       , "core.contextualization.source-category"
       , "core.contextualization.target-category"
       , "core.contextualization.target-owner-cardinality"
       , "core.evidence-input.decode.array-cardinality"
       , "core.evidence-input.decode.array-distinctness"
       , "core.evidence-input.decode.discriminator"
       , "core.evidence-input.decode.duplicate-object-member"
       , "core.evidence-input.decode.json-syntax"
       , "core.evidence-input.decode.model-identity.nul"
       , "core.evidence-input.decode.model-identity.unicode-scalar"
       , "core.evidence-input.decode.normalization-collision"
       , "core.evidence-input.decode.required-member"
       , "core.evidence-input.decode.scalar-grammar"
       , "core.evidence-input.decode.top-level-object"
       , "core.evidence-input.decode.unknown-member"
       , "core.evidence-input.decode.utf8"
       , "core.evidence-input.decode.value-kind"
       , "core.evidence-input.identity.ambiguous"
       , "core.evidence-input.identity.out-of-selected-view"
       , "core.evidence-input.identity.unknown"
       , "core.evidence-input.identity.wrong-type"
       , "core.qualification.pair.proposal-presence"
       , "core.qualification.proposal.effect-graph-membership"
       , "core.qualification.proposal.existing-macro-qualification"
       , "core.qualification.proposal.existing-primitive-support"
       , "core.qualification.proposal.key-result-context"
       , "core.qualification.proposal.listed-key-result"
       , "core.qualification.proposal.need-eligibility"
       , "core.qualification.proposal.objective-context"
       , "core.qualification.proposal.rationale"
       , "core.qualification.proposal.role.key-result.cardinality"
       , "core.qualification.proposal.role.key-result.target"
       , "core.qualification.proposal.role.need.cardinality"
       , "core.qualification.proposal.role.need.target"
       , "core.qualification.proposal.role.objective.cardinality"
       , "core.qualification.proposal.role.objective.target"
       , "core.qualification.proposal.role.strategy.cardinality"
       , "core.qualification.proposal.role.strategy.target"
       , "core.qualification.proposal.selected-need"
       , "core.qualification.proposal.selected-strategy"
       , "core.qualification.proposal.sources"
       , "core.qualification.proposal.strategy-eligibility"
       , "core.qualified-endpoint.catalog-membership"
       , "core.readiness.baseline.chronology"
       , "core.readiness.baseline.identity"
       , "core.readiness.baseline.value-domain"
       , "core.readiness.effect-criterion.kind"
       , "core.readiness.effect-criterion.value-domain"
       , "core.readiness.evidence-plan.cardinality"
       , "core.readiness.evidence-plan.chronology"
       , "core.readiness.evidence-plan.source"
       , "core.readiness.kpi-definition.cardinality"
       , "core.readiness.kpi-definition.interpretation"
       , "core.readiness.kpi-definition.measurement-method"
       , "core.readiness.kpi-definition.unit"
       , "core.readiness.kpi-definition.value-domain"
       , "core.readiness.planned-start.cardinality"
       , "core.readiness.target-criterion.due"
       , "core.readiness.target-criterion.kind"
       , "core.readiness.target-criterion.value-domain"
       , "core.semantic-relation.compatibility"
       , "core.situated-need.driver-anchoring"
       , "core.situated-need.driver-cardinality"
       , "core.situated-need.objective-cardinality"
       , "core.situated-need.objective-grounding"
       , "core.situated-need.surfacing-situation-anchoring"
       , "core.situated-need.surfacing-situation-cardinality"
       , "core.strategy-formulation.action-contributions"
       , "core.strategy-formulation.actions"
       , "core.strategy-formulation.diagnosis"
       , "core.strategy-formulation.diagnosis-grounding"
       , "core.strategy-formulation.guiding-policy"
       , "core.strategy-formulation.guiding-policy-actions"
       , "core.strategy-formulation.intent"
       , "core.strategy-formulation.key-result-substantiation"
       , "core.strategy-formulation.key-results"
       , "core.strategy-formulation.vision-orientation"
       , "core.structured-proposition.commitment"
       , "core.structured-proposition.family"
       , "core.structured-proposition.identity"
       , "core.structured-proposition.incidence"
       , "core.supplemental.decode.duplicate-member"
       , "core.supplemental.decode.json-syntax"
       , "core.supplemental.decode.utf8"
       , "core.supplemental.identity.ambiguous"
       , "core.supplemental.identity.out-of-selected-view"
       , "core.supplemental.identity.unknown"
       , "core.supplemental.identity.wrong-type"
       , "core.supplemental.schema.admitted-type"
       , "core.supplemental.schema.array-cardinality"
       , "core.supplemental.schema.array-distinctness"
       , "core.supplemental.schema.model-identity.nul"
       , "core.supplemental.schema.model-identity.unicode-scalar"
       , "core.supplemental.schema.required-member"
       , "core.supplemental.schema.scalar-grammar"
       , "core.supplemental.schema.top-level-object"
       , "core.supplemental.schema.type-member"
       , "core.supplemental.schema.unknown-member"
       , "core.supplemental.schema.value-kind"
       , "core.supplemental.subject.cardinality"
       , "core.trace.ownership.intervention-action-at-intervention"
       , "core.trace.ownership.intervention-key-result-at-intervention"
       , "core.trace.ownership.measure-kpi-at-measure"
       , "core.trace.ownership.measure-performance-dimension-at-measure"
       , "core.trace.ownership.need-driver-at-need"
       , "core.trace.ownership.need-objective-at-need"
       , "core.trace.ownership.strategy-action-at-strategy"
       , "core.trace.ownership.strategy-driver-at-strategy"
       , "core.trace.ownership.strategy-key-result-at-strategy"
       , "core.trace.ownership.strategy-objective-at-strategy"
       , "core.trace.ownership.vision-objective-at-vision"
       , "core.trace.promotion.strategy-action-membership"
       , "core.trace.promotion.strategy-diagnosis"
       , "core.trace.promotion.strategy-identity"
       , "core.trace.promotion.strategy-intent"
       , "core.trace.promotion.strategy-key-result-membership"
       , "core.trace.promotion.strategy-model-identity"
       , "core.trace.promotion.strategy-proof"
       , "core.trace.root.asserted-presence"
       , "core.trace.slot.intervention-action-changes-same-situation-anchor"
       , "core.trace.slot.intervention-action-contributes-to-intervention-key-result"
       , "core.trace.slot.intervention-addresses-need"
       , "core.trace.slot.intervention-changes-situation"
       , "core.trace.slot.intervention-key-result-contributes-to-strategy-key-result"
       , "core.trace.slot.intervention-key-result-sets-target-for-measure-kpi"
       , "core.trace.slot.intervention-key-result-substantiates-need-objective"
       , "core.trace.slot.intervention-sets-target-for-measure"
       , "core.trace.slot.measure-kpi-measures-situation-anchor"
       , "core.trace.slot.measure-measures-situation"
       , "core.trace.slot.measure-performance-dimension-contains-measure-kpi"
       , "core.trace.slot.need-driver-grounds-need-objective"
       , "core.trace.slot.situation-anchor-anchors-need-driver"
       , "core.trace.slot.situation-is-constituted-by-same-situation-anchor"
       , "core.trace.slot.situation-surfaces-need"
       , "core.trace.slot.strategy-action-contributes-to-strategy-key-result"
       , "core.trace.slot.strategy-action-guides-intervention-action"
       , "core.trace.slot.strategy-directs-intervention"
       , "core.trace.slot.strategy-driver-grounds-strategy-objective"
       , "core.trace.slot.strategy-driver-indicates-measure-performance-dimension"
       , "core.trace.slot.strategy-frames-measure"
       , "core.trace.slot.strategy-key-result-determines-measure-performance-dimension"
       , "core.trace.slot.strategy-key-result-substantiates-strategy-objective"
       , "core.trace.slot.strategy-key-result-translates-into-need-objective"
       , "core.trace.slot.strategy-qualifies-need"
       , "core.trace.slot.vision-objective-orients-strategy-objective"
       , "core.trace.slot.vision-orients-strategy"
       , "core.trace.supplied.graph-identity"
       , "core.trace.supplied.ownership-slot"
       , "core.trace.supplied.relation-slot"
       ]

capabilityInputRuleIds :: NonEmpty Text
capabilityInputRuleIds =
  "core.evidence-input.decode.array-cardinality"
    :| [ "core.evidence-input.decode.array-distinctness"
       , "core.evidence-input.decode.discriminator"
       , "core.evidence-input.decode.duplicate-object-member"
       , "core.evidence-input.decode.json-syntax"
       , "core.evidence-input.decode.model-identity.nul"
       , "core.evidence-input.decode.model-identity.unicode-scalar"
       , "core.evidence-input.decode.normalization-collision"
       , "core.evidence-input.decode.required-member"
       , "core.evidence-input.decode.scalar-grammar"
       , "core.evidence-input.decode.top-level-object"
       , "core.evidence-input.decode.unknown-member"
       , "core.evidence-input.decode.utf8"
       , "core.evidence-input.decode.value-kind"
       , "core.evidence-input.identity.ambiguous"
       , "core.evidence-input.identity.out-of-selected-view"
       , "core.evidence-input.identity.unknown"
       , "core.evidence-input.identity.wrong-type"
       , "core.supplemental.decode.duplicate-member"
       , "core.supplemental.decode.json-syntax"
       , "core.supplemental.decode.utf8"
       , "core.supplemental.identity.ambiguous"
       , "core.supplemental.identity.out-of-selected-view"
       , "core.supplemental.identity.unknown"
       , "core.supplemental.identity.wrong-type"
       , "core.supplemental.schema.admitted-type"
       , "core.supplemental.schema.array-cardinality"
       , "core.supplemental.schema.array-distinctness"
       , "core.supplemental.schema.model-identity.nul"
       , "core.supplemental.schema.model-identity.unicode-scalar"
       , "core.supplemental.schema.required-member"
       , "core.supplemental.schema.scalar-grammar"
       , "core.supplemental.schema.top-level-object"
       , "core.supplemental.schema.type-member"
       , "core.supplemental.schema.unknown-member"
       , "core.supplemental.schema.value-kind"
       , "core.supplemental.subject.cardinality"
       ]

qualificationRuleIds :: NonEmpty Text
qualificationRuleIds =
  "core.qualification.pair.proposal-presence"
    :| [ "core.qualification.proposal.effect-graph-membership"
       , "core.qualification.proposal.existing-macro-qualification"
       , "core.qualification.proposal.existing-primitive-support"
       , "core.qualification.proposal.key-result-context"
       , "core.qualification.proposal.listed-key-result"
       , "core.qualification.proposal.need-eligibility"
       , "core.qualification.proposal.objective-context"
       , "core.qualification.proposal.rationale"
       , "core.qualification.proposal.role.key-result.cardinality"
       , "core.qualification.proposal.role.key-result.target"
       , "core.qualification.proposal.role.need.cardinality"
       , "core.qualification.proposal.role.need.target"
       , "core.qualification.proposal.role.objective.cardinality"
       , "core.qualification.proposal.role.objective.target"
       , "core.qualification.proposal.role.strategy.cardinality"
       , "core.qualification.proposal.role.strategy.target"
       , "core.qualification.proposal.selected-need"
       , "core.qualification.proposal.selected-strategy"
       , "core.qualification.proposal.sources"
       , "core.qualification.proposal.strategy-eligibility"
       ]

readinessAndAssessmentRuleIds :: NonEmpty Text
readinessAndAssessmentRuleIds =
  "core.assessment.actual-start.cardinality"
    :| [ "core.assessment.actual-start.chronology"
       , "core.assessment.anchor.identity"
       , "core.assessment.chronology.observation"
       , "core.assessment.coverage.trace-observation"
       , "core.assessment.effect-criterion.apply"
       , "core.assessment.identity.observation"
       , "core.assessment.identity.observation-uniqueness"
       , "core.assessment.kpi.identity"
       , "core.assessment.limitations.required"
       , "core.assessment.readiness.reconstructed-proof"
       , "core.assessment.source.nonempty"
       , "core.assessment.target-criterion.apply"
       , "core.assessment.trace.identity"
       , "core.assessment.value-domain.observation"
       , "core.readiness.baseline.chronology"
       , "core.readiness.baseline.identity"
       , "core.readiness.baseline.value-domain"
       , "core.readiness.effect-criterion.kind"
       , "core.readiness.effect-criterion.value-domain"
       , "core.readiness.evidence-plan.cardinality"
       , "core.readiness.evidence-plan.chronology"
       , "core.readiness.evidence-plan.source"
       , "core.readiness.kpi-definition.cardinality"
       , "core.readiness.kpi-definition.interpretation"
       , "core.readiness.kpi-definition.measurement-method"
       , "core.readiness.kpi-definition.unit"
       , "core.readiness.kpi-definition.value-domain"
       , "core.readiness.planned-start.cardinality"
       , "core.readiness.target-criterion.due"
       , "core.readiness.target-criterion.kind"
       , "core.readiness.target-criterion.value-domain"
       ]

structureRuleIds :: NonEmpty Text
structureRuleIds =
  "core.collective-strategy-realization.participant-cardinality"
    :| [ "core.collective-strategy-realization.participant-type"
       , "core.collective-strategy-realization.participant-uniqueness"
       , "core.collective-strategy-realization.target-cardinality"
       , "core.collective-strategy-realization.target-distinctness"
       , "core.collective-strategy-realization.target-type"
       , "core.contextualization.source-category"
       , "core.contextualization.target-category"
       , "core.contextualization.target-owner-cardinality"
       , "core.qualified-endpoint.catalog-membership"
       , "core.semantic-relation.compatibility"
       , "core.structured-proposition.commitment"
       , "core.structured-proposition.family"
       , "core.structured-proposition.identity"
       , "core.structured-proposition.incidence"
       ]

traceRuleIds :: NonEmpty Text
traceRuleIds =
  "core.trace.ownership.intervention-action-at-intervention"
    :| [ "core.trace.ownership.intervention-key-result-at-intervention"
       , "core.trace.ownership.measure-kpi-at-measure"
       , "core.trace.ownership.measure-performance-dimension-at-measure"
       , "core.trace.ownership.need-driver-at-need"
       , "core.trace.ownership.need-objective-at-need"
       , "core.trace.ownership.strategy-action-at-strategy"
       , "core.trace.ownership.strategy-driver-at-strategy"
       , "core.trace.ownership.strategy-key-result-at-strategy"
       , "core.trace.ownership.strategy-objective-at-strategy"
       , "core.trace.ownership.vision-objective-at-vision"
       , "core.trace.promotion.strategy-action-membership"
       , "core.trace.promotion.strategy-diagnosis"
       , "core.trace.promotion.strategy-identity"
       , "core.trace.promotion.strategy-intent"
       , "core.trace.promotion.strategy-key-result-membership"
       , "core.trace.promotion.strategy-model-identity"
       , "core.trace.promotion.strategy-proof"
       , "core.trace.root.asserted-presence"
       , "core.trace.slot.intervention-action-changes-same-situation-anchor"
       , "core.trace.slot.intervention-action-contributes-to-intervention-key-result"
       , "core.trace.slot.intervention-addresses-need"
       , "core.trace.slot.intervention-changes-situation"
       , "core.trace.slot.intervention-key-result-contributes-to-strategy-key-result"
       , "core.trace.slot.intervention-key-result-sets-target-for-measure-kpi"
       , "core.trace.slot.intervention-key-result-substantiates-need-objective"
       , "core.trace.slot.intervention-sets-target-for-measure"
       , "core.trace.slot.measure-kpi-measures-situation-anchor"
       , "core.trace.slot.measure-measures-situation"
       , "core.trace.slot.measure-performance-dimension-contains-measure-kpi"
       , "core.trace.slot.need-driver-grounds-need-objective"
       , "core.trace.slot.situation-anchor-anchors-need-driver"
       , "core.trace.slot.situation-is-constituted-by-same-situation-anchor"
       , "core.trace.slot.situation-surfaces-need"
       , "core.trace.slot.strategy-action-contributes-to-strategy-key-result"
       , "core.trace.slot.strategy-action-guides-intervention-action"
       , "core.trace.slot.strategy-directs-intervention"
       , "core.trace.slot.strategy-driver-grounds-strategy-objective"
       , "core.trace.slot.strategy-driver-indicates-measure-performance-dimension"
       , "core.trace.slot.strategy-frames-measure"
       , "core.trace.slot.strategy-key-result-determines-measure-performance-dimension"
       , "core.trace.slot.strategy-key-result-substantiates-strategy-objective"
       , "core.trace.slot.strategy-key-result-translates-into-need-objective"
       , "core.trace.slot.strategy-qualifies-need"
       , "core.trace.slot.vision-objective-orients-strategy-objective"
       , "core.trace.slot.vision-orients-strategy"
       , "core.trace.supplied.graph-identity"
       , "core.trace.supplied.ownership-slot"
       , "core.trace.supplied.relation-slot"
       ]

relationTokens :: NonEmpty Text
relationTokens =
  "addresses"
    :| [ "anchors"
       , "changes"
       , "contains"
       , "contributes-to"
       , "determines"
       , "directs"
       , "frames"
       , "grounds"
       , "guides"
       , "indicates"
       , "is-constituted-by"
       , "measures"
       , "orients"
       , "qualifies"
       , "sets-target-for"
       , "substantiates"
       , "surfaces"
       , "translates-into"
       ]

qualifiedEndpointIds :: NonEmpty Text
qualifiedEndpointIds =
  "context.ethos"
    :| [ "context.intervention"
       , "context.measure"
       , "context.mission"
       , "context.need"
       , "context.situation"
       , "context.strategy"
       , "context.vision"
       , "primitive.ethos.principle"
       , "primitive.intervention.action"
       , "primitive.intervention.key-result"
       , "primitive.measure.kpi"
       , "primitive.mission.driver"
       , "primitive.need.driver"
       , "primitive.need.objective"
       , "primitive.strategy.action"
       , "primitive.strategy.driver"
       , "primitive.strategy.key-result"
       , "primitive.strategy.objective"
       , "primitive.strategy.principle"
       , "primitive.vision.objective"
       , "situation-anchor.business-capability"
       , "situation-anchor.business-object"
       , "situation-anchor.business-process"
       , "situation-anchor.value-stream"
       , "structuring.measure.performance-dimension"
       , "structuring.strategy.performance-dimension"
       ]

structuredPropositionFamilyIds :: NonEmpty Text
structuredPropositionFamilyIds = "collective-strategy-realization" :| []
