#!/usr/bin/env python3
"""Render the O2I ArchiMate profile contract as a Markdown fragment."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from archimate_profile import (
    ArchimateProfileContract,
    FrozenObject,
    ProfileContractError,
    load_profile_contract,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONTRACT = ROOT / "spc" / "contract" / "archimate-profile.json"
DEFAULT_OUTPUT = ROOT / "spc" / "contract" / "archimate-profile.md"

GERMAN_TERMS = {
    "at-least-two": "mindestens zwei",
    "context-ownership": "Kontextzuordnung",
    "exactly-one": "genau eins",
    "exactly-one-each": "jeweils genau eins",
    "exactly-one-non-empty": "genau ein nicht leerer Wert",
    "forbidden": "unzulässig",
    "required": "erforderlich",
    "structured-proposition": "strukturierte Proposition",
}


class ProfileRenderError(ValueError):
    """The structurally valid contract cannot be rendered coherently."""


@dataclass(frozen=True)
class AnchorFamily:
    identifier: str
    source: str
    target: str
    label: str
    relationship: str
    directed: bool


def render_contract(contract: ArchimateProfileContract) -> str:
    """Render one validated contract in deterministic publication order."""
    patterns = _patterns_by_id(contract)
    endpoint_names = _endpoint_names(
        contract.carrier_mappings,
        patterns.get("contextualization"),
    )
    anchor_carriers, anchor_families, anchor_relation_ids = _anchor_contract(
        contract,
        endpoint_names,
    )
    context_relations = []
    evidence_relations = []
    for relation in contract.relation_mappings:
        identifier = relation["id"]
        if identifier in anchor_relation_ids:
            continue
        if (
            relation["source"].startswith("context.")
            and relation["target"].startswith("context.")
        ):
            context_relations.append(relation)
        else:
            evidence_relations.append(relation)

    lines = [
        (
            "<!-- Generated by utl/render-archimate-profile.py from "
            "spc/contract/archimate-profile.json. Do not edit. -->"
        ),
        "",
        "#### ArchiMate-Profilvertrag",
        "",
        (
            "Der [maschinenlesbare Vertrag]"
            "(spc/contract/archimate-profile.json) bestimmt die folgenden "
            "Notationsabbildungen."
        ),
        "",
    ]
    lines.extend(_render_metadata(contract))
    lines.extend(_render_carriers(contract.carrier_mappings))
    lines.extend(
        _render_relations(
            "Kontextrelationen",
            context_relations,
            endpoint_names,
        )
    )
    lines.extend(
        _render_relations(
            "Primitive und strukturierende Relationen",
            evidence_relations,
            endpoint_names,
        )
    )
    lines.extend(
        _render_anchor_contract(anchor_carriers, anchor_families)
    )
    lines.extend(
        _render_contextualization(patterns.get("contextualization"))
    )
    lines.extend(
        _render_collective(
            patterns.get("collective-strategy-realization"),
            endpoint_names,
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def write_fragment(
    contract_path: Path,
    output_path: Path,
) -> None:
    """Render and write one fragment."""
    content = render_contract(load_profile_contract(contract_path))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def check_fragment(
    contract_path: Path,
    output_path: Path,
) -> bool:
    """Return whether the committed fragment equals deterministic output."""
    expected = render_contract(load_profile_contract(contract_path))
    try:
        actual = output_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return actual == expected


def _render_metadata(contract: ArchimateProfileContract) -> List[str]:
    metadata = contract.metadata
    model = metadata["modelRoot"]
    carrier = metadata["typedCarrier"]
    relation = metadata["semanticRelation"]
    rows = [
        ("Schema", _code(contract.schema)),
        ("Profilversion", _code(contract.profile_version)),
        (
            "Modellwurzel",
            _contract_summary(
                (model["profileKey"],),
                model["cardinality"],
                model["additionalO2IProperties"],
            ),
        ),
        (
            "Typisierter Träger",
            _contract_summary(
                (
                    carrier["kindKey"],
                    carrier["typeKey"],
                    carrier["commitmentKey"],
                ),
                carrier["cardinality"],
                carrier["additionalO2IProperties"],
                carrier["commitmentValues"],
            ),
        ),
        (
            "Semantische Relation",
            _contract_summary(
                (relation["commitmentKey"],),
                relation["cardinality"],
                relation["additionalO2IProperties"],
                relation["commitmentValues"],
            ),
        ),
    ]
    return [
        "##### Profilmetadaten",
        "",
        *_table(("Vertrag", "Wert"), rows),
        "",
    ]


def _render_carriers(
    carriers: Sequence[FrozenObject],
) -> List[str]:
    rows = []
    for carrier in carriers:
        rows.append(
            (
                _code(carrier["o2iKind"]),
                _code_join(carrier["o2iTypes"]),
                _code(carrier["archimateElement"]),
                _code(_german(carrier["contextOwnership"])),
            )
        )
    return [
        "##### Trägerabbildungen",
        "",
        (
            "Die Trägerabbildung legt fest, welches ArchiMate-Element "
            "einen typisierten O2I-Inhalt darstellen kann."
        ),
        "",
        *_table(
            (
                "O2I-Kind",
                "Persistierter o2i.type",
                "ArchiMate-Element",
                "Kontextbezug",
            ),
            rows,
        ),
        "",
    ]


def _render_relations(
    heading: str,
    relations: Sequence[FrozenObject],
    endpoint_names: Dict[str, str],
) -> List[str]:
    rows = []
    for relation in relations:
        rows.append(
            (
                _code(_signature(relation, endpoint_names)),
                _code(_representation(relation)),
            )
        )
    return [
        f"##### {heading}",
        "",
        *_table(
            ("O2I-Signatur", "ArchiMate-Repräsentation"),
            rows,
        ),
        "",
    ]


def _render_anchor_contract(
    carriers: Sequence[FrozenObject],
    families: Sequence[AnchorFamily],
) -> List[str]:
    carrier_rows = [
        (
            _code(_display_name(carrier["o2iTypes"][0])),
            _code(carrier["archimateElement"]),
        )
        for carrier in carriers
    ]
    family_rows = [
        (
            _code(
                f"{family.source} --{family.label}--> {family.target}"
            ),
            _code(
                _representation_parts(
                    family.relationship,
                    family.directed,
                )
            ),
        )
        for family in families
    ]
    return [
        "##### Situationsanker",
        "",
        (
            "Die sechs Ankerformen verwenden ihre fachlich entsprechenden "
            "ArchiMate-Business-Architecture-Elemente."
        ),
        "",
        *_table(
            ("O2I-Ankerform", "ArchiMate-Element"),
            carrier_rows,
        ),
        "",
        (
            "Die vier parametrisierten Relationsfamilien gelten jeweils "
            "vollständig für alle sechs Ankerformen."
        ),
        "",
        *_table(
            (
                "O2I-Familiensignatur",
                "ArchiMate-Repräsentation",
            ),
            family_rows,
        ),
        "",
    ]


def _render_contextualization(
    pattern: Optional[FrozenObject],
) -> List[str]:
    if pattern is None:
        raise ProfileRenderError(
            "contextualization is required for publication"
        )
    targets = " | ".join(pattern["targetKinds"])
    signature = (
        f"{pattern['sourceKind']} --{pattern['label']}--> {targets}"
    )
    rows = [
        ("O2I-Signatur", _code(signature)),
        (
            "ArchiMate-Repräsentation",
            _code(_representation(pattern)),
        ),
        (
            "Eingehende Kardinalität am Inhalt",
            _code(_german(pattern["targetIncomingCardinality"])),
        ),
        (
            "Relationsmetadaten",
            _code(_german(pattern["o2iMetadata"])),
        ),
        ("Projektion", _code(_german(pattern["projection"]))),
    ]
    return [
        "##### Kontextualisierung",
        "",
        (
            "Kontextualisierung ordnet Primitive und strukturierende "
            "Elemente genau einem konkreten O2I-Kontext zu."
        ),
        "",
        *_table(("Aspekt", "Vertrag"), rows),
        "",
    ]


def _render_collective(
    pattern: Optional[FrozenObject],
    endpoint_names: Dict[str, str],
) -> List[str]:
    if pattern is None:
        raise ProfileRenderError(
            "collective Strategy realization is required for publication"
        )
    carrier = pattern["carrier"]
    segments = pattern["segments"]
    contributors = pattern["contributors"]
    target = pattern["target"]
    contributor = endpoint_names[contributors["endpoint"]]
    target_name = endpoint_names[target["endpoint"]]
    signature = (
        f"{contributor} [n] --{segments['label']}--> "
        f"{_display_name(carrier['o2iType'])} "
        f"--{segments['label']}--> {target_name}"
    )
    rows = [
        ("O2I-Signatur", _code(signature)),
        (
            "Träger",
            _code(
                f"{_display_name(carrier['o2iKind'])} / "
                f"{_display_name(carrier['o2iType'])} -> "
                f"{carrier['archimateElement']} "
                f"({_junction_name(carrier['junctionType'])})"
            ),
        ),
        (
            "Commitment",
            _code(
                f"{carrier['commitmentKey']} = "
                f"{' | '.join(carrier['commitmentValues'])}"
            ),
        ),
        (
            "Beitragsevidenz",
            _code(
                f"{carrier['fitEvidenceKey']} "
                f"({_german(carrier['fitEvidenceCardinality'])})"
            ),
        ),
        (
            "Segmente",
            _code(
                f"{_representation(segments)}; "
                f"Metadaten {_german(segments['o2iMetadata'])}"
            ),
        ),
        (
            "Beitragende",
            _code(
                f"{_german(contributors['cardinality'])}; "
                "untereinander verschieden: "
                f"{_german(contributors['distinct'])}"
            ),
        ),
        (
            "Ziel",
            _code(
                f"{_german(target['cardinality'])}; "
                "von Beitragenden verschieden: "
                f"{_german(target['distinctFromContributors'])}"
            ),
        ),
        (
            "Junction-Ketten",
            _code(_german(pattern["junctionChains"])),
        ),
        ("Projektion", _code(_german(pattern["projection"]))),
    ]
    return [
        "##### Kollektive Strategierealisierung",
        "",
        (
            "Die kollektive Strategierealisierung bildet einen n-ären "
            "O2I-Claim auf eine ArchiMate-Junction und ihre Segmente ab."
        ),
        "",
        *_table(("Aspekt", "Vertrag"), rows),
        "",
    ]


def _anchor_contract(
    contract: ArchimateProfileContract,
    endpoint_names: Dict[str, str],
) -> Tuple[Tuple[FrozenObject, ...], Tuple[AnchorFamily, ...], frozenset]:
    carriers = tuple(
        carrier
        for carrier in contract.carrier_mappings
        if carrier["o2iKind"] == "SituationAnchor"
    )
    if len(carriers) != 6:
        raise ProfileRenderError(
            "the publication contract requires exactly six anchor forms"
        )
    for carrier in carriers:
        if len(carrier["o2iTypes"]) != 1:
            raise ProfileRenderError(
                f"anchor carrier {carrier['id']} must declare one type"
            )

    anchor_ids = {carrier["id"] for carrier in carriers}
    grouped: Dict[str, List[FrozenObject]] = {}
    ordered_names = []
    relation_ids = set()
    for relation in contract.relation_mappings:
        endpoints = {relation["source"], relation["target"]}
        if not endpoints.intersection(anchor_ids):
            continue
        name = relation["relationName"]
        if name not in grouped:
            grouped[name] = []
            ordered_names.append(name)
        grouped[name].append(relation)
        relation_ids.add(relation["id"])
    if len(grouped) != 4:
        raise ProfileRenderError(
            "the publication contract requires four anchor families"
        )

    families = tuple(
        _compress_anchor_family(
            name,
            grouped[name],
            carriers,
            endpoint_names,
        )
        for name in ordered_names
    )
    return carriers, families, frozenset(relation_ids)


def _compress_anchor_family(
    name: str,
    relations: Sequence[FrozenObject],
    carriers: Sequence[FrozenObject],
    endpoint_names: Dict[str, str],
) -> AnchorFamily:
    expected = {carrier["id"]: carrier for carrier in carriers}
    observed = {}
    template = relations[0]
    anchor_at_source = template["source"] in expected
    for relation in relations:
        source_anchor = relation["source"] in expected
        target_anchor = relation["target"] in expected
        if source_anchor == target_anchor or source_anchor != anchor_at_source:
            raise ProfileRenderError(
                f"anchor family {name} has inconsistent endpoint roles"
            )
        anchor_id = (
            relation["source"] if source_anchor else relation["target"]
        )
        _, separator, suffix = anchor_id.partition(".")
        if not separator:
            raise ProfileRenderError(
                f"anchor carrier {anchor_id} has no stable suffix"
            )
        expected_id = f"{name}.{suffix}"
        if relation["id"] != expected_id:
            raise ProfileRenderError(
                f"anchor relation {relation['id']} must be {expected_id}"
            )
        if anchor_id in observed:
            raise ProfileRenderError(
                f"anchor family {name} repeats {anchor_id}"
            )
        observed[anchor_id] = relation
        invariant = (
            relation["relationName"],
            relation["label"],
            relation["archimateRelationship"],
            relation["associationDirected"],
            relation["target"] if source_anchor else relation["source"],
        )
        template_invariant = (
            template["relationName"],
            template["label"],
            template["archimateRelationship"],
            template["associationDirected"],
            template["target"]
            if anchor_at_source
            else template["source"],
        )
        if invariant != template_invariant:
            raise ProfileRenderError(
                f"anchor family {name} is not parametrically uniform"
            )
    if set(observed) != set(expected):
        raise ProfileRenderError(
            f"anchor family {name} does not cover every anchor form"
        )

    source = (
        "Situation Anchor"
        if anchor_at_source
        else endpoint_names[template["source"]]
    )
    target = (
        endpoint_names[template["target"]]
        if anchor_at_source
        else "Situation Anchor"
    )
    return AnchorFamily(
        identifier=name,
        source=source,
        target=target,
        label=template["label"],
        relationship=template["archimateRelationship"],
        directed=template["associationDirected"],
    )


def _endpoint_names(
    carriers: Sequence[FrozenObject],
    contextualization: Optional[FrozenObject],
) -> Dict[str, str]:
    if contextualization is None:
        raise ProfileRenderError(
            "contextualization is required to render endpoint signatures"
        )
    source_kind = contextualization["sourceKind"]
    target_kinds = set(contextualization["targetKinds"])
    contexts = tuple(
        (_slug(o2i_type), o2i_type)
        for carrier in carriers
        if carrier["o2iKind"] == source_kind
        for o2i_type in carrier["o2iTypes"]
    )
    result = {}
    for carrier in carriers:
        kind = carrier["o2iKind"]
        if kind == source_kind:
            for token, name in contexts:
                _put_unique(
                    result,
                    f"{carrier['id']}.{token}",
                    _display_name(name),
                )
        elif kind in target_kinds:
            prefix, separator, suffix = carrier["id"].partition(".")
            if not separator or len(carrier["o2iTypes"]) != 1:
                raise ProfileRenderError(
                    f"cannot render contextualized carrier {carrier['id']}"
                )
            for token, context in contexts:
                _put_unique(
                    result,
                    f"{prefix}.{token}.{suffix}",
                    (
                        f"{_display_name(carrier['o2iTypes'][0])} "
                        f"@ {_display_name(context)}"
                    ),
                )
        else:
            if len(carrier["o2iTypes"]) != 1:
                raise ProfileRenderError(
                    f"cannot render carrier {carrier['id']}"
                )
            _put_unique(
                result,
                carrier["id"],
                _display_name(carrier["o2iTypes"][0]),
            )
    return result


def _patterns_by_id(
    contract: ArchimateProfileContract,
) -> Dict[str, FrozenObject]:
    return {pattern["id"]: pattern for pattern in contract.pattern_mappings}


def _signature(
    relation: FrozenObject,
    endpoint_names: Dict[str, str],
) -> str:
    return (
        f"{endpoint_names[relation['source']]} "
        f"--{relation['label']}--> "
        f"{endpoint_names[relation['target']]}"
    )


def _representation(record: FrozenObject) -> str:
    return _representation_parts(
        record["archimateRelationship"],
        record["associationDirected"],
    )


def _representation_parts(relationship: str, directed: bool) -> str:
    if relationship == "AssociationRelationship":
        direction = "gerichtet" if directed else "ungerichtet"
        return f"{relationship} ({direction})"
    return relationship


def _contract_summary(
    keys: Sequence[str],
    cardinality: str,
    additional: str,
    values: Sequence[str] = (),
) -> str:
    result = ", ".join(_code(key) for key in keys)
    if values:
        result += f" = {_code_join(values)}"
    return (
        f"{result}; Kardinalität {_code(_german(cardinality))}; "
        f"weitere O2I-Properties {_code(_german(additional))}"
    )


def _table(
    headers: Sequence[str],
    rows: Iterable[Sequence[str]],
) -> List[str]:
    result = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    result.extend("| " + " | ".join(row) + " |" for row in rows)
    return result


def _code_join(values: Sequence[str]) -> str:
    return ", ".join(_code(value) for value in values)


def _code(value: str) -> str:
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\n", " ").replace("|", r"\|")
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * (longest + 1)
    padded_edge = (
        text.startswith(("`", " "))
        or text.endswith(("`", " "))
    )
    padding = " " if padded_edge else ""
    return f"{fence}{padding}{text}{padding}{fence}"


def _slug(value: str) -> str:
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", value).lower()


def _display_name(value: str) -> str:
    acronym_boundary = re.sub(
        r"(?<=[A-Z])(?=[A-Z][a-z])",
        " ",
        value,
    )
    return re.sub(
        r"(?<=[a-z0-9])(?=[A-Z])",
        " ",
        acronym_boundary,
    )


def _german(value: str) -> str:
    return GERMAN_TERMS.get(value, value)


def _junction_name(value: str) -> str:
    return f"{value.upper()}-Junction"


def _put_unique(target: Dict[str, str], key: str, value: str) -> None:
    if key in target:
        raise ProfileRenderError(f"duplicate rendered endpoint {key}")
    target[key] = value


def _arguments(argv: Optional[Sequence[str]]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render the O2I ArchiMate profile contract.",
    )
    parser.add_argument(
        "--contract",
        type=Path,
        default=DEFAULT_CONTRACT,
        help="profile contract JSON",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="generated Markdown fragment",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated fragment is stale",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Run write mode or freshness checking."""
    arguments = _arguments(argv)
    try:
        if arguments.check:
            if not check_fragment(arguments.contract, arguments.output):
                print(
                    (
                        "[o2i|error] ArchiMate profile fragment is stale: "
                        f"{arguments.output}"
                    ),
                    file=sys.stderr,
                )
                return 1
            print("[o2i|info] ArchiMate profile fragment is current.")
            return 0
        write_fragment(arguments.contract, arguments.output)
        print(
            f"[o2i|info] Wrote ArchiMate profile fragment: {arguments.output}"
        )
        return 0
    except (OSError, ProfileContractError, ProfileRenderError) as error:
        print(f"[o2i|error] {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
