{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Schema.Generated where

import Data.ByteString (ByteString)
import Data.List.NonEmpty (NonEmpty(..))
import O2I.Operation.Schema.Embed (embedSchemaBytes)
import O2I.Operation.Schema.Internal

adapterInventoryVariant :: SchemaVariant
adapterInventoryVariant = SchemaVariant "adapter-inventory"

adapterInventoryMachineSchema :: MachineSchema
adapterInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.adapter-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "9ebc6cba58375277366bf50e83bda032344e4aff76f378f4c32ede43eaf04149"
          }
    , machineSchemaVariantsValue = adapterInventoryVariant :| []
    }

profileInventoryVariant :: SchemaVariant
profileInventoryVariant = SchemaVariant "profile-inventory"

profileDefinitionInvalidVariant :: SchemaVariant
profileDefinitionInvalidVariant =
  SchemaVariant "profile-static-definition-invalid"

profileInventoryMachineSchema :: MachineSchema
profileInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.profile-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "cb3e8626972fabf979f729cd71761d46df0ffde7c710357b02e42b058d467a6a"
          }
    , machineSchemaVariantsValue =
        profileInventoryVariant :| [profileDefinitionInvalidVariant]
    }

ruleInventoryVariant :: SchemaVariant
ruleInventoryVariant = SchemaVariant "rule-inventory"

ruleDefinitionInvalidVariant :: SchemaVariant
ruleDefinitionInvalidVariant = SchemaVariant "rule-static-definition-invalid"

ruleInventoryMachineSchema :: MachineSchema
ruleInventoryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-inventory"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "58648f3f9edd15d5ca9c3b042271547694062f0bde7cbc9f21d9e41ee63519b1"
          }
    , machineSchemaVariantsValue =
        ruleInventoryVariant :| [ruleDefinitionInvalidVariant]
    }

ruleExplanationFoundVariant :: SchemaVariant
ruleExplanationFoundVariant = SchemaVariant "rule-explanation-found"

ruleExplanationNotFoundVariant :: SchemaVariant
ruleExplanationNotFoundVariant = SchemaVariant "rule-explanation-not-found"

ruleExplanationMachineSchema :: MachineSchema
ruleExplanationMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.rule-explanation"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "a8c10312335adc2fa8a0a449057c3177a0f9d74b416449b8f9e9dc02ddc67e8a"
          }
    , machineSchemaVariantsValue =
        ruleExplanationFoundVariant :| [ruleExplanationNotFoundVariant]
    }

viewsDiscoveredVariant :: SchemaVariant
viewsDiscoveredVariant = SchemaVariant "views-discovered"

viewAcquisitionFailedVariant :: SchemaVariant
viewAcquisitionFailedVariant = SchemaVariant "view-acquisition-failed"

viewAdapterSelectionFailedVariant :: SchemaVariant
viewAdapterSelectionFailedVariant =
  SchemaVariant "view-adapter-selection-failed"

viewAdapterDecodeFailedVariant :: SchemaVariant
viewAdapterDecodeFailedVariant = SchemaVariant "view-adapter-decode-failed"

viewDiscoveryMachineSchema :: MachineSchema
viewDiscoveryMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.discovery.view"
          , schemaAuthorityVersionValue = SchemaVersion 2
          , schemaAuthorityDigestValue =
              SchemaDigest
                "596b82ae5bc9c900c5094e3dc82db2d3b26977686290cc5a17a7a5ee07ee4b87"
          }
    , machineSchemaVariantsValue =
        viewsDiscoveredVariant
          :| [ viewAcquisitionFailedVariant
             , viewAdapterSelectionFailedVariant
             , viewAdapterDecodeFailedVariant
             ]
    }

qualificationSubjectsPrerequisiteRejectedVariant :: SchemaVariant
qualificationSubjectsPrerequisiteRejectedVariant =
  SchemaVariant "qualification-subjects-prerequisite-rejected"

qualificationSubjectsDiscoveredVariant :: SchemaVariant
qualificationSubjectsDiscoveredVariant =
  SchemaVariant "qualification-subjects-discovered"

qualificationSubjectsMachineSchema :: MachineSchema
qualificationSubjectsMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.discovery.qualification-subjects"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "f0a1504ccfd1d3fb130401b4cbe98cf4b4e5209cdb33fc039878f3440f1ad740"
          }
    , machineSchemaVariantsValue =
        qualificationSubjectsPrerequisiteRejectedVariant
          :| [qualificationSubjectsDiscoveredVariant]
    }

notationValidationAcceptedVariant :: SchemaVariant
notationValidationAcceptedVariant = SchemaVariant "notation-validation-accepted"

notationValidationRejectedVariant :: SchemaVariant
notationValidationRejectedVariant = SchemaVariant "notation-validation-rejected"

profileValidationAcceptedVariant :: SchemaVariant
profileValidationAcceptedVariant = SchemaVariant "profile-validation-accepted"

profileValidationRejectedVariant :: SchemaVariant
profileValidationRejectedVariant = SchemaVariant "profile-validation-rejected"

structureValidationAcceptedVariant :: SchemaVariant
structureValidationAcceptedVariant =
  SchemaVariant "structure-validation-accepted"

structureValidationRejectedVariant :: SchemaVariant
structureValidationRejectedVariant =
  SchemaVariant "structure-validation-rejected"

semanticsValidationAcceptedVariant :: SchemaVariant
semanticsValidationAcceptedVariant =
  SchemaVariant "semantics-validation-accepted"

semanticsValidationRejectedVariant :: SchemaVariant
semanticsValidationRejectedVariant =
  SchemaVariant "semantics-validation-rejected"

semanticsValidationUnavailableVariant :: SchemaVariant
semanticsValidationUnavailableVariant =
  SchemaVariant "semantics-validation-unavailable"

validateResultMachineSchema :: MachineSchema
validateResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.validate"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "7b11dbede900d8fee69043f7eae370f3615aadfd2466b45ff6692a1ac13f42b6"
          }
    , machineSchemaVariantsValue =
        notationValidationAcceptedVariant
          :| [ notationValidationRejectedVariant
             , profileValidationAcceptedVariant
             , profileValidationRejectedVariant
             , structureValidationAcceptedVariant
             , structureValidationRejectedVariant
             , semanticsValidationAcceptedVariant
             , semanticsValidationRejectedVariant
             , semanticsValidationUnavailableVariant
             ]
    }

tracePrerequisiteRejectedVariant :: SchemaVariant
tracePrerequisiteRejectedVariant = SchemaVariant "trace-prerequisite-rejected"

traceRejectedVariant :: SchemaVariant
traceRejectedVariant = SchemaVariant "trace-rejected"

traceAcceptedVariant :: SchemaVariant
traceAcceptedVariant = SchemaVariant "trace-accepted"

traceResultMachineSchema :: MachineSchema
traceResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.trace"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "c569a6270698d421cde569f003171c1ce46934f9d054cde97744ce7dbe89abc9"
          }
    , machineSchemaVariantsValue =
        tracePrerequisiteRejectedVariant
          :| [traceRejectedVariant, traceAcceptedVariant]
    }

qualifyPrerequisiteRejectedVariant :: SchemaVariant
qualifyPrerequisiteRejectedVariant =
  SchemaVariant "qualify-prerequisite-rejected"

qualifyCompletedVariant :: SchemaVariant
qualifyCompletedVariant = SchemaVariant "qualify-completed"

qualifyResultMachineSchema :: MachineSchema
qualifyResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.qualify"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "10d041e4415ab98bcdbcb21b8d6978756a72fb701f21ef82a74af716c39f82c7"
          }
    , machineSchemaVariantsValue =
        qualifyPrerequisiteRejectedVariant :| [qualifyCompletedVariant]
    }

readinessPrerequisiteRejectedVariant :: SchemaVariant
readinessPrerequisiteRejectedVariant =
  SchemaVariant "readiness-prerequisite-rejected"

readinessSubjectUnavailableVariant :: SchemaVariant
readinessSubjectUnavailableVariant =
  SchemaVariant "readiness-subject-unavailable"

readinessNotReadyVariant :: SchemaVariant
readinessNotReadyVariant = SchemaVariant "readiness-not-ready"

readinessReadyVariant :: SchemaVariant
readinessReadyVariant = SchemaVariant "readiness-ready"

readinessResultMachineSchema :: MachineSchema
readinessResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue =
              SchemaIdentity "o2i.operation.readiness"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "b70dc65ba4bedbb5bfc28e322d83209abf3fda4ea861f5f7089f5106ebf141c0"
          }
    , machineSchemaVariantsValue =
        readinessPrerequisiteRejectedVariant
          :| [ readinessSubjectUnavailableVariant
             , readinessNotReadyVariant
             , readinessReadyVariant
             ]
    }

assessPrerequisiteRejectedVariant :: SchemaVariant
assessPrerequisiteRejectedVariant = SchemaVariant "assess-prerequisite-rejected"

assessSubjectUnavailableVariant :: SchemaVariant
assessSubjectUnavailableVariant = SchemaVariant "assess-subject-unavailable"

assessCollectionInvalidVariant :: SchemaVariant
assessCollectionInvalidVariant = SchemaVariant "assess-collection-invalid"

assessObservationsInvalidVariant :: SchemaVariant
assessObservationsInvalidVariant = SchemaVariant "assess-observations-invalid"

assessCompletedVariant :: SchemaVariant
assessCompletedVariant = SchemaVariant "assess-completed"

assessResultMachineSchema :: MachineSchema
assessResultMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.assess"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "0d20115a25f2b1d0a6ecffcbe5cfd5e5858343ee9e43f571f6ba9a9206a9eaf7"
          }
    , machineSchemaVariantsValue =
        assessPrerequisiteRejectedVariant
          :| [ assessSubjectUnavailableVariant
             , assessCollectionInvalidVariant
             , assessObservationsInvalidVariant
             , assessCompletedVariant
             ]
    }

argumentInvalidVariant :: SchemaVariant
argumentInvalidVariant = SchemaVariant "argument-invalid"

commandFailedVariant :: SchemaVariant
commandFailedVariant = SchemaVariant "command-failed"

preparationFailedVariant :: SchemaVariant
preparationFailedVariant = SchemaVariant "preparation-failed"

validateFailedVariant :: SchemaVariant
validateFailedVariant = SchemaVariant "validate-failed"

qualifyFailedVariant :: SchemaVariant
qualifyFailedVariant = SchemaVariant "qualify-failed"

readinessFailedVariant :: SchemaVariant
readinessFailedVariant = SchemaVariant "readiness-failed"

assessFailedVariant :: SchemaVariant
assessFailedVariant = SchemaVariant "assess-failed"

qualificationSubjectsFailedVariant :: SchemaVariant
qualificationSubjectsFailedVariant =
  SchemaVariant "qualification-subjects-failed"

traceFailedVariant :: SchemaVariant
traceFailedVariant = SchemaVariant "trace-failed"

commandErrorMachineSchema :: MachineSchema
commandErrorMachineSchema =
  MachineSchema
    { machineSchemaAuthorityValue =
        SchemaAuthority
          { schemaAuthorityIdentityValue = SchemaIdentity "o2i.command-error"
          , schemaAuthorityVersionValue = SchemaVersion 1
          , schemaAuthorityDigestValue =
              SchemaDigest
                "216795aa6a36359ca8ae0dcfa87ce4767fb5dd069734f41837abfd88a7a16a19"
          }
    , machineSchemaVariantsValue =
        argumentInvalidVariant
          :| [ commandFailedVariant
             , preparationFailedVariant
             , validateFailedVariant
             , qualifyFailedVariant
             , readinessFailedVariant
             , assessFailedVariant
             , qualificationSubjectsFailedVariant
             , traceFailedVariant
             ]
    }

commandErrorSchemaBytes :: ByteString
commandErrorSchemaBytes =
  $(embedSchemaBytes
      "../../../../contract/schema/o2i.command-error-v1.schema.json")

diagnosticSchemaAuthority :: SchemaAuthority
diagnosticSchemaAuthority =
  SchemaAuthority
    { schemaAuthorityIdentityValue = SchemaIdentity "o2i.operation.diagnostic"
    , schemaAuthorityVersionValue = SchemaVersion 2
    , schemaAuthorityDigestValue =
        SchemaDigest
          "b187b2d429347474ba28d02bd73c173c508209636f950a054832926a5fc37121"
    }
