-- | Public facade for the O2I semantic language and validation core.
--
-- Language defines admissible O2I meaning, Graph represents concrete model
-- instances, and Validation establishes progressively stronger guarantees.
module O2I
  ( RawNodeId(..)
  , NodeId
  , unNodeId
  , ContextRef
  , contextRefId
  , Context(..)
  , Primitive(..)
  , Structuring(..)
  , PerformanceDimensionRole(..)
  , PerformanceDimensionRoleCode(..)
  , PerformanceDimensionRoleName(..)
  , SomePerformanceDimensionRole(..)
  , SituationAnchor(..)
  , NodeKind(..)
  , NodeKindValue(..)
  , SContext(..)
  , SPrimitive(..)
  , SSituationAnchor(..)
  , contextValue
  , primitiveValue
  , performanceDimensionRoleCode
  , performanceDimensionRoleCodeOf
  , performanceDimensionRoleName
  , performanceDimensionRoleNameOf
  , performanceDimensionRoleContext
  , performanceDimensionRoleMember
  , performanceDimensionMembershipRelationName
  , performanceDimensionRoleIdentity
  , allPerformanceDimensionRoles
  , reifyPerformanceDimensionRole
  , lookupPerformanceDimensionRole
  , nodeKindValue
  , InterpretationCode(..)
  , SomeInterpretation
  , interpretationCodeOf
  , interpretationIdentity
  , allInterpretations
  , lookupInterpretation
  , MacroClaim
  , MacroEvidenceRule
  , macroEvidenceRules
  , macroEvidenceRuleConclusion
  , macroClaimConclusion
  , Relation
  , SomeRelation
  , FixedRelationCode(..)
  , AnchorRelationFamily(..)
  , RelationCode(..)
  , RelationSemantics(..)
  , MacroEvidenceKind(..)
  , RelationName(..)
  , relationNameFor
  , relationNameOf
  , relationCodeOf
  , relationIdentity
  , guidesMission
  , groundsVision
  , guidesVision
  , orientsStrategy
  , directsStrategy
  , contributesToStrategy
  , qualifiesNeed
  , surfacesNeed
  , addressesNeed
  , directsIntervention
  , changesSituation
  , setsTargetForMeasure
  , measuresSituation
  , framesMeasure
  , constitutedByAnchor
  , guidesEthosPrincipleToMissionDriver
  , guidesEthosPrincipleToVisionObjective
  , groundsMissionDriverToVisionObjective
  , orientsVisionObjectiveToStrategyObjective
  , groundsStrategyDriverToObjective
  , substantiatesStrategyKeyResultObjective
  , guidesStrategyPrincipleToAction
  , contributesStrategyActionToKeyResult
  , guidesStrategyPrincipleToPrinciple
  , contributesStrategyKeyResultToKeyResult
  , contributesStrategyActionToAction
  , translatesStrategyKeyResultToNeedObjective
  , groundsNeedDriverToObjective
  , anchorsNeedDriver
  , indicatesMeasurePerformanceDimension
  , determinesMeasurePerformanceDimension
  , containsPerformanceDimension
  , guidesStrategyActionToInterventionAction
  , contributesInterventionActionToKeyResult
  , substantiatesInterventionKeyResultNeedObjective
  , contributesInterventionKeyResultToStrategyKeyResult
  , setsTargetForMeasureKPI
  , changesAnchor
  , measuresAnchor
  , allRelationCodes
  , allRelations
  , lookupRelations
  , module O2I.Graph
  , StrategyAnchoring(..)
  , RawStrategyFormulation(..)
  , StrategyFormulation
  , RawNeedQualificationProposal(..)
  , NeedQualificationSourceReference
  , NeedQualificationCandidate
  , NeedQualificationError(..)
  , StrategyTextField(..)
  , StrategyPrimitiveRole(..)
  , SemanticallyValidModel
  , strategyFormulations
  , strategyFormulationData
  , lookupSemanticContextRef
  , needQualificationCandidateStrategy
  , needQualificationCandidateNeed
  , needQualificationCandidateKeyResult
  , needQualificationCandidateObjective
  , needQualificationCandidateRationale
  , needQualificationCandidateSourceReference
  , needQualificationSourceReferenceText
  , validateNeedQualificationProposal
  , qualifyingStrategies
  , EffectTrace
  , EffectTraceId
  , SomeSituationAnchorRef
  , TraceableEffectModel
  , MacroEvidenceWitness
  , macroEvidenceWitnesses
  , witnessPremises
  , effectTraces
  , traceIdentifier
  , effectTraceIdText
  , lookupEffectTrace
  , traceVision
  , traceVisionObjective
  , traceStrategy
  , traceStrategyDriver
  , traceStrategyObjective
  , traceStrategyKeyResult
  , traceStrategyAction
  , traceNeed
  , traceNeedDriver
  , traceNeedObjective
  , traceIntervention
  , traceInterventionAction
  , traceInterventionKeyResult
  , traceMeasure
  , traceMeasurePerformanceDimension
  , traceKPI
  , traceSituation
  , traceSituationAnchor
  , situationAnchorRefId
  , situationAnchorRefKind
  , Unit(..)
  , Level(..)
  , Delta(..)
  , ValueDomain(..)
  , RelativeChange(..)
  , RawKPIDefinition(..)
  , KPIDefinition
  , kpiDefinitionKPI
  , kpiDefinitionUnit
  , kpiDefinitionDomain
  , kpiDefinitionMeasurementMethod
  , kpiDefinitionInterpretation
  , EvidenceSource(..)
  , Observation(..)
  , EffectCriterion(..)
  , TargetCriterion(..)
  , PlannedInterventionStart(..)
  , EvidencePlan(..)
  , EvidenceReadyModel
  , kpiDefinitions
  , lookupKPIDefinition
  , evidencePlans
  , readinessCheckedAt
  , plannedInterventionStarts
  , readyEffectTraces
  , readyInterventions
  , readyTracesForIntervention
  , ActualInterventionStart(..)
  , FollowUpObservation(..)
  , CriterionResult(..)
  , TargetResult(..)
  , EffectAssessment
  , assessedFollowUp
  , effectResult
  , targetResult
  , EvidenceAssessedModel
  , evidenceAssessedAt
  , actualInterventionStarts
  , effectAssessments
  , isEffectiveNeed
  , Validation(..)
  , Check
  , StructuralError(..)
  , StructureInternalError(..)
  , StructureResult(..)
  , ModelInvariantError(..)
  , TraceabilityError(..)
  , EvidenceReadinessError(..)
  , EvidenceError(..)
  , validateStructure
  , validateModelSemantics
  , validateTraceability
  , validateEvidenceReadinessAt
  , assessEffectEvidenceAt
  ) where

import O2I.Graph
import O2I.Language
import O2I.Validation
