{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by contract/compile.py. Do not edit.
module O2I.Operation.Rule.Generated where

import Data.List.NonEmpty (NonEmpty(..))
import Data.Text (Text)

operationContractIdentity :: Text
operationContractIdentity = "o2i.operation"

operationContractVersion :: Text
operationContractVersion = "0.3.0"

operationContractSha256 :: Text
operationContractSha256 =
  "81798862858111306bee2823c27696a036f8e8ddaf65d0bf6fd64e14fb43f1c4"

data GeneratedOperationRuleStage =
  GeneratedPreparationStage
  deriving (Bounded, Enum, Eq, Ord, Show)

data GeneratedOperationRule
  = GeneratedProfileAdapterId
  | GeneratedProfileAdapterNotation
  | GeneratedProfileInventoryIdentityTokenUniqueness
  | GeneratedProfileReferenceGrammar
  | GeneratedProfileReferenceMissing
  | GeneratedProfileReferencePropertyMultiplicity
  | GeneratedProfileReferenceUnknown
  | GeneratedProfileReferenceValueKind
  | GeneratedProfileReferenceValueMultiplicity
  deriving (Bounded, Enum, Eq, Ord, Show)

generatedOperationRuleId :: GeneratedOperationRule -> Text
generatedOperationRuleId value =
  case value of
    GeneratedProfileAdapterId -> "bootstrap.profile-adapter.adapter-id"
    GeneratedProfileAdapterNotation -> "bootstrap.profile-adapter.notation"
    GeneratedProfileInventoryIdentityTokenUniqueness ->
      "bootstrap.profile-inventory.identity-token-uniqueness"
    GeneratedProfileReferenceGrammar -> "bootstrap.profile-reference.grammar"
    GeneratedProfileReferenceMissing -> "bootstrap.profile-reference.missing"
    GeneratedProfileReferencePropertyMultiplicity ->
      "bootstrap.profile-reference.property-multiplicity"
    GeneratedProfileReferenceUnknown -> "bootstrap.profile-reference.unknown"
    GeneratedProfileReferenceValueKind ->
      "bootstrap.profile-reference.value-kind"
    GeneratedProfileReferenceValueMultiplicity ->
      "bootstrap.profile-reference.value-multiplicity"

generatedOperationRuleExpectation :: GeneratedOperationRule -> Text
generatedOperationRuleExpectation value =
  case value of
    GeneratedProfileAdapterId ->
      "The selected adapter identifier is admitted by the resolved compiled Profile."
    GeneratedProfileAdapterNotation ->
      "The selected adapter notation exactly equals the resolved compiled Profile notation."
    GeneratedProfileInventoryIdentityTokenUniqueness ->
      "Every compiled Profile has a unique identity and token pair in the static inventory."
    GeneratedProfileReferenceGrammar ->
      "The model Profile reference conforms to the canonical identity-at-token grammar."
    GeneratedProfileReferenceMissing ->
      "The model root declares exactly one O2I Profile reference."
    GeneratedProfileReferencePropertyMultiplicity ->
      "The model root contains exactly one o2i.profile property occurrence."
    GeneratedProfileReferenceUnknown ->
      "The model Profile reference exactly identifies one descriptor in the compiled inventory."
    GeneratedProfileReferenceValueKind ->
      "The o2i.profile property contains one textual scalar value."
    GeneratedProfileReferenceValueMultiplicity ->
      "The o2i.profile property contains exactly one value occurrence."

generatedOperationRuleMeaning :: GeneratedOperationRule -> Text
generatedOperationRuleMeaning value =
  case value of
    GeneratedProfileAdapterId ->
      "A Profile explicitly declares which compiled adapters may project its notation."
    GeneratedProfileAdapterNotation ->
      "Adapter and Profile must describe the same notation family before projection."
    GeneratedProfileInventoryIdentityTokenUniqueness ->
      "A Profile reference must resolve to at most one immutable compiled descriptor."
    GeneratedProfileReferenceGrammar ->
      "Canonical syntax makes Profile selection exact and deterministic."
    GeneratedProfileReferenceMissing ->
      "Operation cannot select a Profile without an explicit model-level reference."
    GeneratedProfileReferencePropertyMultiplicity ->
      "Multiple Profile properties make the model-level selection ambiguous."
    GeneratedProfileReferenceUnknown ->
      "Only compiled Profiles can supply executable mapping and validation contracts."
    GeneratedProfileReferenceValueKind ->
      "Profile resolution consumes one canonical textual reference rather than structured or numeric data."
    GeneratedProfileReferenceValueMultiplicity ->
      "Multiple values would request more than one Profile for the same model."

generatedOperationRuleAction :: GeneratedOperationRule -> Text
generatedOperationRuleAction value =
  case value of
    GeneratedProfileAdapterId ->
      "Select an admitted adapter or update the compiled Profile contract."
    GeneratedProfileAdapterNotation ->
      "Select a matching adapter and Profile pair."
    GeneratedProfileInventoryIdentityTokenUniqueness ->
      "Remove the duplicate compiled Profile identity or token."
    GeneratedProfileReferenceGrammar ->
      "Write the reference as the exact compiled Profile identity followed by @ and its token."
    GeneratedProfileReferenceMissing ->
      "Add one o2i.profile property to the model root."
    GeneratedProfileReferencePropertyMultiplicity ->
      "Retain one authoritative o2i.profile property occurrence."
    GeneratedProfileReferenceUnknown ->
      "Use an exact reference reported by the profiles discovery command."
    GeneratedProfileReferenceValueKind ->
      "Replace the property value with one textual Profile reference."
    GeneratedProfileReferenceValueMultiplicity ->
      "Retain one authoritative Profile reference value."

generatedOperationRuleStage ::
     GeneratedOperationRule -> GeneratedOperationRuleStage
generatedOperationRuleStage _ = GeneratedPreparationStage

generatedOperationRules :: NonEmpty GeneratedOperationRule
generatedOperationRules =
  GeneratedProfileAdapterId
    :| [ GeneratedProfileAdapterNotation
       , GeneratedProfileInventoryIdentityTokenUniqueness
       , GeneratedProfileReferenceGrammar
       , GeneratedProfileReferenceMissing
       , GeneratedProfileReferencePropertyMultiplicity
       , GeneratedProfileReferenceUnknown
       , GeneratedProfileReferenceValueKind
       , GeneratedProfileReferenceValueMultiplicity
       ]
